<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/pandas_data_preparation/for_practice/practice_all.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(42)

In [16]:
df1 = pd.DataFrame({
    "product": ["Phone","Laptop","Tablet","Monitor","Keyboard"],
    "price": [1200, None, 600, None, 80],
    "quantity": [5, 3, None, 4, 10]
})
df1

    product   price  quantity
0     Phone  1200.0       5.0
1    Laptop     NaN       3.0
2    Tablet   600.0       NaN
3   Monitor     NaN       4.0
4  Keyboard    80.0      10.0

In [17]:
# Determine how many blank values ​​are in which columns
df1.isnull().sum()

product     0
price       2
quantity    1
dtype: int64

In [18]:
# Check if total revenue is being calculated incorrectly due to empty values
df1['price'] * df1['quantity']

0    6000.0
1       NaN
2       NaN
3       NaN
4     800.0
dtype: float64

In [19]:
df1 = df1.dropna().copy()
df1

    product   price  quantity
0     Phone  1200.0       5.0
4  Keyboard    80.0      10.0

In [21]:
# recalculate total revenue based on the cleaned dataset
df1['revenue'] = df1['price'] * df1['quantity']
df1

    product   price  quantity  revenue
0     Phone  1200.0       5.0   6000.0
4  Keyboard    80.0      10.0    800.0

In [22]:
df2 = pd.DataFrame({
    "student": ["Ali","Vali","Ali","Hasan","Vali","Zafar"],
    "math": [85, 90, 85, 70, 90, 88]
})
df2

  student  math
0     Ali    85
1    Vali    90
2     Ali    85
3   Hasan    70
4    Vali    90
5   Zafar    88

In [34]:
# Identify duplicate entries
df2.duplicated()

0    False
1    False
2     True
3    False
4     True
5    False
dtype: bool

In [35]:
# Remove duplicate rows and determine how many unique students remain
len(df2.drop_duplicates())

4

In [36]:
df3 = pd.DataFrame({
    "gender": ["M","F","M","F","F","M"],
    "score": [78, 88, 90, 67, 95, 80]
})
df3

  gender  score
0      M     78
1      F     88
2      M     90
3      F     67
4      F     95
5      M     80

In [38]:
# Convert the values ​​in the Gender column to full word form
df3['gender'] = df3['gender'].replace({'M':'male', 'F':'female'})
df3

   gender  score
0    male     78
1  female     88
2    male     90
3  female     67
4  female     95
5    male     80

In [42]:
# Change values ​​below 80 in the Score column to “Low”, otherwise to “High”
df3['score'].map(lambda x: 'low' if x<80 else 'high')

0     low
1    high
2    high
3     low
4    high
5    high
Name: score, dtype: object

In [43]:
df4 = pd.DataFrame({
    "age": [15, 22, 37, 45, 18, 29, 60]
})
df4

   age
0   15
1   22
2   37
3   45
4   18
5   29
6   60

In [48]:
# Divide the ages into 3 intervals and count how many people are in each interval
bins = [14, 24, 44, 65]
df4['groups'] = pd.cut(df4['age'], bins, labels=['teenagers', 'middle-age', 'adults'])
df4

   age      groups
0   15   teenagers
1   22   teenagers
2   37  middle-age
3   45      adults
4   18   teenagers
5   29  middle-age
6   60      adults

In [49]:
df4['groups'].value_counts()

groups
teenagers     3
middle-age    2
adults        2
Name: count, dtype: int64

In [50]:
df5 = pd.DataFrame({
    "region": np.random.choice(["Toshkent","Samarqand","Buxoro"], 15),
    "sales": np.random.randint(1000, 5000, 15)
})
df5

       region  sales
0      Buxoro   4380
1    Toshkent   1769
2      Buxoro   3391
3      Buxoro   2515
4    Toshkent   4485
5    Toshkent   3853
6      Buxoro   3433
7   Samarqand   2215
8      Buxoro   1955
9      Buxoro   3324
10     Buxoro   2184
11     Buxoro   1459
12   Toshkent   4385
13     Buxoro   1021
14  Samarqand   3300

In [51]:
# Calculate the average sales for each region
df5.groupby('region')['sales'].mean()

region
Buxoro       2629.111111
Samarqand    2757.500000
Toshkent     3623.000000
Name: sales, dtype: float64

In [58]:
# Calculate the average sales for each region
df5.groupby('region')['sales'].sum().idxmax()

'Buxoro'