<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/pandas_data_preparation/for_practice/practice_all.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(42)

In [16]:
df1 = pd.DataFrame({
    "product": ["Phone","Laptop","Tablet","Monitor","Keyboard"],
    "price": [1200, None, 600, None, 80],
    "quantity": [5, 3, None, 4, 10]
})
df1

    product   price  quantity
0     Phone  1200.0       5.0
1    Laptop     NaN       3.0
2    Tablet   600.0       NaN
3   Monitor     NaN       4.0
4  Keyboard    80.0      10.0

In [17]:
# Determine how many blank values ​​are in which columns
df1.isnull().sum()

product     0
price       2
quantity    1
dtype: int64

In [18]:
# Check if total revenue is being calculated incorrectly due to empty values
df1['price'] * df1['quantity']

0    6000.0
1       NaN
2       NaN
3       NaN
4     800.0
dtype: float64

In [19]:
df1 = df1.dropna().copy()
df1

    product   price  quantity
0     Phone  1200.0       5.0
4  Keyboard    80.0      10.0

In [21]:
# recalculate total revenue based on the cleaned dataset
df1['revenue'] = df1['price'] * df1['quantity']
df1

    product   price  quantity  revenue
0     Phone  1200.0       5.0   6000.0
4  Keyboard    80.0      10.0    800.0

In [22]:
df2 = pd.DataFrame({
    "student": ["Ali","Vali","Ali","Hasan","Vali","Zafar"],
    "math": [85, 90, 85, 70, 90, 88]
})
df2

  student  math
0     Ali    85
1    Vali    90
2     Ali    85
3   Hasan    70
4    Vali    90
5   Zafar    88

In [34]:
# Identify duplicate entries
df2.duplicated()

0    False
1    False
2     True
3    False
4     True
5    False
dtype: bool

In [35]:
# Remove duplicate rows and determine how many unique students remain
len(df2.drop_duplicates())

4