<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/pandas_data_preparation/for_practice/practice_all.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(42)

In [3]:
df1 = pd.DataFrame({
    "product": ["Phone","Laptop","Tablet","Monitor","Keyboard"],
    "price": [1200, None, 600, None, 80],
    "quantity": [5, 3, None, 4, 10]
})
df1

    product   price  quantity
0     Phone  1200.0       5.0
1    Laptop     NaN       3.0
2    Tablet   600.0       NaN
3   Monitor     NaN       4.0
4  Keyboard    80.0      10.0

In [4]:
# Determine how many blank values ​​are in which columns
df1.isnull().sum()

product     0
price       2
quantity    1
dtype: int64

In [5]:
# Check if total revenue is being calculated incorrectly due to empty values
df1['price'] * df1['quantity']

0    6000.0
1       NaN
2       NaN
3       NaN
4     800.0
dtype: float64

In [6]:
df1 = df1.dropna().copy()
df1

    product   price  quantity
0     Phone  1200.0       5.0
4  Keyboard    80.0      10.0

In [7]:
# recalculate total revenue based on the cleaned dataset
df1['revenue'] = df1['price'] * df1['quantity']
df1

    product   price  quantity  revenue
0     Phone  1200.0       5.0   6000.0
4  Keyboard    80.0      10.0    800.0

In [8]:
df2 = pd.DataFrame({
    "student": ["Ali","Vali","Ali","Hasan","Vali","Zafar"],
    "math": [85, 90, 85, 70, 90, 88]
})
df2

  student  math
0     Ali    85
1    Vali    90
2     Ali    85
3   Hasan    70
4    Vali    90
5   Zafar    88

In [9]:
# Identify duplicate entries
df2.duplicated()

0    False
1    False
2     True
3    False
4     True
5    False
dtype: bool

In [10]:
# Remove duplicate rows and determine how many unique students remain
len(df2.drop_duplicates())

4

In [11]:
df3 = pd.DataFrame({
    "gender": ["M","F","M","F","F","M"],
    "score": [78, 88, 90, 67, 95, 80]
})
df3

  gender  score
0      M     78
1      F     88
2      M     90
3      F     67
4      F     95
5      M     80

In [12]:
# Convert the values ​​in the Gender column to full word form
df3['gender'] = df3['gender'].replace({'M':'male', 'F':'female'})
df3

   gender  score
0    male     78
1  female     88
2    male     90
3  female     67
4  female     95
5    male     80

In [13]:
# Change values ​​below 80 in the Score column to “Low”, otherwise to “High”
df3['score'].map(lambda x: 'low' if x<80 else 'high')

0     low
1    high
2    high
3     low
4    high
5    high
Name: score, dtype: object

In [14]:
df4 = pd.DataFrame({
    "age": [15, 22, 37, 45, 18, 29, 60]
})
df4

   age
0   15
1   22
2   37
3   45
4   18
5   29
6   60

In [15]:
# Divide the ages into 3 intervals and count how many people are in each interval
bins = [14, 24, 44, 65]
df4['groups'] = pd.cut(df4['age'], bins, labels=['teenagers', 'middle-age', 'adults'])
df4

   age      groups
0   15   teenagers
1   22   teenagers
2   37  middle-age
3   45      adults
4   18   teenagers
5   29  middle-age
6   60      adults

In [16]:
df4['groups'].value_counts()

groups
teenagers     3
middle-age    2
adults        2
Name: count, dtype: int64

In [17]:
df5 = pd.DataFrame({
    "region": np.random.choice(["Toshkent","Samarqand","Buxoro"], 15),
    "sales": np.random.randint(1000, 5000, 15)
})
df5

       region  sales
0      Buxoro   4380
1    Toshkent   1769
2      Buxoro   3391
3      Buxoro   2515
4    Toshkent   4485
5    Toshkent   3853
6      Buxoro   3433
7   Samarqand   2215
8      Buxoro   1955
9      Buxoro   3324
10     Buxoro   2184
11     Buxoro   1459
12   Toshkent   4385
13     Buxoro   1021
14  Samarqand   3300

In [18]:
# Calculate the average sales for each region
df5.groupby('region')['sales'].mean()

region
Buxoro       2629.111111
Samarqand    2757.500000
Toshkent     3623.000000
Name: sales, dtype: float64

In [19]:
# Calculate the average sales for each region
df5.groupby('region')['sales'].sum().idxmax()

'Buxoro'

In [20]:
df6 = pd.DataFrame({
    "income": [2000, 3000, 15000, 2500, 4000, 50000, 2700]
})
df6

   income
0    2000
1    3000
2   15000
3    2500
4    4000
5   50000
6    2700

In [21]:
# sort data
df6_sort = df6.sort_values(by='income', ascending=True)
df6_sort

   income
0    2000
3    2500
6    2700
1    3000
4    4000
2   15000
5   50000

- `IQR = Q3 - Q1`
- `Q1` - 25% , `Q3` - 75%

In [22]:
df6_sort.describe()

             income
count      7.000000
mean   11314.285714
std    17660.920000
min     2000.000000
25%     2600.000000
50%     3000.000000
75%     9500.000000
max    50000.000000

In [23]:
# Outlier detection using the IQR method
q1 = 2600
q3 = 9500
iqr = q3 - q1
up = q3 + (1.5 * iqr)
low = q1 - (1.5 * iqr) # If the answer is a negative number, it is taken as 0
print("upper: ", up)
print('lower: ', low)

upper:  19850.0
lower:  -7750.0

- There are only 50000 above 19850. Therefore, the outlier in our data is only 50000.

In [24]:
# determining the mean value together with the outlier
df6_sort['income'].mean()

np.float64(11314.285714285714)

In [25]:
# Removing extreme values
df6_sort[df6_sort['income'] > 19850]

   income
5   50000

In [26]:
df6_sort = df6_sort.drop(5)
df6_sort

   income
0    2000
3    2500
6    2700
1    3000
4    4000
2   15000

In [27]:
# determining the average value without outliers
df6_sort['income'].mean()

np.float64(4866.666666666667)

In [28]:
df7 = pd.DataFrame({
    "order_id": range(1, 21),
    "amount": np.random.randint(100, 1000, 20)
})
df7

    order_id  amount
0          1     847
1          2     956
2          3     660
3          4     574
4          5     158
5          6     610
6          7     781
7          8     575
8          9     799
9         10     882
10        11     289
11        12     786
12        13     662
13        14     975
14        15     666
15        16     343
16        17     931
17        18     604
18        19     230
19        20     584

In [29]:
# Extract 5 random orders from the table
df7_sample = df7.sample(5)
df7_sample

    order_id  amount
10        11     289
7          8     575
0          1     847
2          3     660
5          6     610

In [30]:
# Calculate the average sum of randomly selected orders
df7_sample['amount'].mean()

np.float64(596.2)

In [31]:
df8 = pd.DataFrame({
    "date": ["2025-01-05","2025-02-10","2025-03-15","2025-04-20"],
    "sales": [1000,1500,1200,1800]
})
df8

         date  sales
0  2025-01-05   1000
1  2025-02-10   1500
2  2025-03-15   1200
3  2025-04-20   1800

In [32]:
# Convert a date column to time format
df8['date'] = pd.to_datetime(df8['date'])
df8.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    4 non-null      datetime64[ns]
 1   sales   4 non-null      int64
dtypes: datetime64[ns](1), int64(1)
memory usage: 196.0 bytes

In [33]:
# separate the year as a separate column
df8['year'] = df8['date'].dt.year
df8

        date  sales  year
0 2025-01-05   1000  2025
1 2025-02-10   1500  2025
2 2025-03-15   1200  2025
3 2025-04-20   1800  2025

In [34]:
# Summarize sales by month
df8['month'] = df8['date'].dt.month_name()
df8.groupby('month')['sales'].sum()

month
April       1800
February    1500
January     1000
March       1200
Name: sales, dtype: int64

In [35]:
df9 = pd.DataFrame({
    'Name': ['Ali', 'Vali', 'Sardor', 'Jasur', 'Kamol'],
    'Age': [25, np.nan, 35, 28, np.nan],
    'Salary': [5000, 6000, np.nan, 7000, 6500],
    'City': ['Tashkent', 'Samarkand', np.nan, 'Bukhara', 'Fergana']
})
df9

     Name   Age  Salary       City
0     Ali  25.0  5000.0   Tashkent
1    Vali   NaN  6000.0  Samarkand
2  Sardor  35.0     NaN        NaN
3   Jasur  28.0  7000.0    Bukhara
4   Kamol   NaN  6500.0    Fergana

In [36]:
# Delete rows with all NaN values
df9.dropna()

    Name   Age  Salary      City
0    Ali  25.0  5000.0  Tashkent
3  Jasur  28.0  7000.0   Bukhara

In [38]:
df10 = pd.DataFrame({
    'Product': ['Laptop', 'Phone', 'Tablet', 'Watch', 'Camera'],
    'Price': [1200, np.nan, 450, 250, np.nan],
    'Stock': [50, 120, np.nan, 200, 45],
    'Rating': [4.5, 4.7, np.nan, 4.0, 4.8]
})
df10

  Product   Price  Stock  Rating
0  Laptop  1200.0   50.0     4.5
1   Phone     NaN  120.0     4.7
2  Tablet   450.0    NaN     NaN
3   Watch   250.0  200.0     4.0
4  Camera     NaN   45.0     4.8

In [41]:
# Delete rows with at least 2 NaN values
df10.dropna(thresh=3)

  Product   Price  Stock  Rating
0  Laptop  1200.0   50.0     4.5
1   Phone     NaN  120.0     4.7
3   Watch   250.0  200.0     4.0
4  Camera     NaN   45.0     4.8

In [42]:
df11 = pd.DataFrame({
    'Student': ['Ahmad', 'Zarina', 'Bekzod', 'Dilshod'],
    'Math': [85, np.nan, 78, 92],
    'Physics': [88, 85, np.nan, 87],
    'Chemistry': [90, 88, 85, np.nan]
})
df11

   Student  Math  Physics  Chemistry
0    Ahmad  85.0     88.0       90.0
1   Zarina   NaN     85.0       88.0
2   Bekzod  78.0      NaN       85.0
3  Dilshod  92.0     87.0        NaN

In [45]:
# Delete rows with NaN values ​​in all columns
df11.dropna(axis=1)

   Student
0    Ahmad
1   Zarina
2   Bekzod
3  Dilshod

In [46]:
df12 = pd.DataFrame({
    'Name': ['Ali', 'Vali', 'Sardor', 'Jasur', 'Kamol'],
    'Age': [25, np.nan, 35, 28, np.nan],
    'Salary': [5000, 6000, np.nan, 7000, 6500],
    'Experience': [3, 5, np.nan, 4, 6]
})
df12

     Name   Age  Salary  Experience
0     Ali  25.0  5000.0         3.0
1    Vali   NaN  6000.0         5.0
2  Sardor  35.0     NaN         NaN
3   Jasur  28.0  7000.0         4.0
4   Kamol   NaN  6500.0         6.0

In [49]:
# Fill in NaN values ​​in the Age column with the average value
df12['Age'] = df12['Age'].fillna(df12['Age'].mean())
df12

     Name        Age  Salary  Experience
0     Ali  25.000000  5000.0         3.0
1    Vali  29.333333  6000.0         5.0
2  Sardor  35.000000     NaN         NaN
3   Jasur  28.000000  7000.0         4.0
4   Kamol  29.333333  6500.0         6.0

In [51]:
# Fill in NaN values ​​in the Salary column with the median
df12['Salary'] = df12['Salary'].fillna(df12['Salary'].median())
df12

     Name        Age  Salary  Experience
0     Ali  25.000000  5000.0         3.0
1    Vali  29.333333  6000.0         5.0
2  Sardor  35.000000  6250.0         NaN
3   Jasur  28.000000  7000.0         4.0
4   Kamol  29.333333  6500.0         6.0

In [52]:
df13 = pd.DataFrame({
    'Product': ['Laptop', 'Phone', 'Tablet', 'Watch'],
    'Price': [1200, np.nan, 450, 250],
    'Category': ['Electronics', np.nan, 'Electronics', 'Accessories'],
    'Rating': [4.5, 4.7, np.nan, 4.0]
})
df13

  Product   Price     Category  Rating
0  Laptop  1200.0  Electronics     4.5
1   Phone     NaN          NaN     4.7
2  Tablet   450.0  Electronics     NaN
3   Watch   250.0  Accessories     4.0

In [53]:
# Fill NaN values ​​in the Price column with 0
df13['Price'].fillna(0)

0    1200.0
1       0.0
2     450.0
3     250.0
Name: Price, dtype: float64

In [55]:
# Fill in NaN values ​​in the Category column with 'Unknown'
df13['Category'].fillna('Unknown')

0    Electronics
1        Unknown
2    Electronics
3    Accessories
Name: Category, dtype: object

In [57]:
# Fill in NaN values ​​in the Rating column with the previous one
df13['Rating'].bfill()

0    4.5
1    4.7
2    4.0
3    4.0
Name: Rating, dtype: float64