<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/scikit-learn/simple_imputer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Ushbu sahifada SimpleImputer - NaN larni turli strategiya yordamida avtomatik to'ldirishni amaliyot qilamiz**

In [1]:
import numpy as np
import pandas as pd
import sklearn

In [8]:
df = pd.DataFrame({
    "age": [20, 25, np.nan, 35, 40],
    "salary": [2000, np.nan, 4000, 5000, 100000]
})
df

    age    salary
0  20.0    2000.0
1  25.0       NaN
2   NaN    4000.0
3  35.0    5000.0
4  40.0  100000.0

In [9]:
X = df[['age', 'salary']]

# train testlarga bo'lish
from sklearn.model_selection import train_test_split
X_train, X_test = train_test_split(X, random_state=42, test_size=0.2)

print("shape train:", X_train.shape)
print("shape test:", X_test.shape)

shape train: (4, 2)
shape test: (1, 2)

In [10]:
from sklearn.impute import SimpleImputer

# NaN lar bilan ishledigan obyekt yaratish
imputer = SimpleImputer(strategy='median')

X_train_imputed = imputer.fit_transform(X_train)
X_test_imputed = imputer.transform(X_test)

X_train_imputed

array([[4.0e+01, 1.0e+05],
       [3.5e+01, 4.0e+03],
       [2.0e+01, 2.0e+03],
       [3.5e+01, 5.0e+03]])

In [11]:
X_train

    age    salary
4  40.0  100000.0
2   NaN    4000.0
0  20.0    2000.0
3  35.0    5000.0

2-topshiriq

In [12]:
# eng ko'p takrorlangan qiymat bilan avtomatik to'ldirish
df_freq = pd.DataFrame({
    "city": ["Tashkent", "Samarkand", "Tashkent", np.nan, "Tashkent"],
    "gender": ["Male", "Female", np.nan, "Male", "Male"]
})
df_freq

        city  gender
0   Tashkent    Male
1  Samarkand  Female
2   Tashkent     NaN
3        NaN    Male
4   Tashkent    Male

In [13]:
X2 = df_freq[['city', 'gender']]

X2_train, X2_test = train_test_split(X2, random_state=42, test_size=0.2)

print("shape train:", X2_train.shape)
print("shape test:", X2_test.shape)

shape train: (4, 2)
shape test: (1, 2)

In [15]:
X2_train

       city gender
4  Tashkent   Male
2  Tashkent    NaN
0  Tashkent   Male
3       NaN   Male

In [14]:
imputer2 = SimpleImputer(strategy='most_frequent')

X2_train_imputed = imputer2.fit_transform(X2_train)
X2_test_imputed = imputer2.transform(X2_test)

X2_train_imputed

array([['Tashkent', 'Male'],
       ['Tashkent', 'Male'],
       ['Tashkent', 'Male'],
       ['Tashkent', 'Male']], dtype=object)

In [16]:
# Unknown bilan avtomatik to'ldirish
df_constant = pd.DataFrame({
    "city": ["Tashkent", "Samarkand", np.nan, "Bukhara", np.nan],
    "job": ["Data Scientist", np.nan, "ML Engineer", "Data Analyst", np.nan]
})
df_constant

        city             job
0   Tashkent  Data Scientist
1  Samarkand             NaN
2        NaN     ML Engineer
3    Bukhara    Data Analyst
4        NaN             NaN

In [17]:
X3 = df_constant[['city', 'job']]

X3_train, X3_test = train_test_split(X3, random_state=42, test_size=0.2)

print("shape train:", X3_train.shape)
print("shape test:", X3_test.shape)

shape train: (4, 2)
shape test: (1, 2)

In [18]:
X3_train

       city             job
4       NaN             NaN
2       NaN     ML Engineer
0  Tashkent  Data Scientist
3   Bukhara    Data Analyst

In [20]:
imputer3 = SimpleImputer(strategy='constant', fill_value='Unknown')

X3_train_imputed = imputer3.fit_transform(X3_train)
X3_test_imputed = imputer3.transform(X3_test)

X3_train_imputed

array([['Unknown', 'Unknown'],
       ['Unknown', 'ML Engineer'],
       ['Tashkent', 'Data Scientist'],
       ['Bukhara', 'Data Analyst']], dtype=object)