<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/pandas_data_preparation/concat3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Concat**

In [1]:
import numpy as np
import pandas as pd

**birinchi topshiriq**

In [2]:
df1 = pd.DataFrame({
    "name": ["Ali", "Vali", "Hasan"],
    "age": [20, 21, 22],
    "group": ["A", "B", "A"]
})

df2 = pd.DataFrame({
    "name": ["Husan", "Sardor"],
    "age": [23, 20],
    "group": ["C", "B"]
})
df1

    name  age group
0    Ali   20     A
1   Vali   21     B
2  Hasan   22     A

In [3]:
df2

     name  age group
0   Husan   23     C
1  Sardor   20     B

In [10]:
# df1 va df2dagi talabalarni bitta umumiy DataFramega birlashtiring
# Talabalar ustunlari bir xil. Natijada barcha 5 ta talaba bo‘lishi kerak
pd.concat([df1, df2]).sort_index(ascending=True)

     name  age group
0     Ali   20     A
0   Husan   23     C
1    Vali   21     B
1  Sardor   20     B
2   Hasan   22     A

**ikkinchi topshiriq**

In [11]:
students = pd.DataFrame({
    "name": ["Ali", "Vali", "Hasan"],
    "group": ["A", "B", "A"]
})

scores = pd.DataFrame({
    "math": [90, 85, 78],
    "english": [88, 92, 80]
})
students

    name group
0    Ali     A
1   Vali     B
2  Hasan     A

In [12]:
scores

   math  english
0    90       88
1    85       92
2    78       80

In [17]:
# students va scores ma'lumotlarini bitta DataFramega birlashtiring
pd.concat([students, scores]).sort_index(ascending=True)

    name group  math  english
0    Ali     A   NaN      NaN
0    NaN   NaN  90.0     88.0
1   Vali     B   NaN      NaN
1    NaN   NaN  85.0     92.0
2  Hasan     A   NaN      NaN
2    NaN   NaN  78.0     80.0

**uchinchi topshiriq**

In [18]:
january = pd.DataFrame({
    "product": ["Laptop", "Phone", "Tablet"],
    "quantity": [5, 10, 7],
    "revenue": [5000, 8000, 3500]
})

february = pd.DataFrame({
    "product": ["Laptop", "Phone", "Tablet"],
    "quantity": [8, 12, 9],
    "revenue": [8000, 9600, 4500]
})

march = pd.DataFrame({
    "product": ["Laptop", "Phone", "Tablet"],
    "quantity": [6, 15, 11],
    "revenue": [6000, 12000, 5500]
})
january

  product  quantity  revenue
0  Laptop         5     5000
1   Phone        10     8000
2  Tablet         7     3500

In [19]:
february

  product  quantity  revenue
0  Laptop         8     8000
1   Phone        12     9600
2  Tablet         9     4500

In [20]:
march

  product  quantity  revenue
0  Laptop         6     6000
1   Phone        15    12000
2  Tablet        11     5500

In [22]:
# Uch oyga tegishli sotuv ma'lumotlarini bitta umumiy DataFramega birlashtiring
pd.concat([january, february, march])

  product  quantity  revenue
0  Laptop         5     5000
1   Phone        10     8000
2  Tablet         7     3500
0  Laptop         8     8000
1   Phone        12     9600
2  Tablet         9     4500
0  Laptop         6     6000
1   Phone        15    12000
2  Tablet        11     5500