<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/pandas_data_preparation/data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

**Online Store data**

In [3]:
import pandas as pd

data = {
    "Customer_ID": [101, 102, 103, 104, 105, 106, 107, 108],
    "Name": ["Ali", "Vali", "Hasan", "Husan", "Ali", "Malika", "Vali", "Zarina"],
    "Age": [22, 25, -3, 31, 22, 150, 28, 24],
    "City": ["Tashkent", "Samarkand", "tashkent", "Bukhara", "Tashkent", "Samarkand", "Bukhara", "Tashkent"],
    "Product": ["Laptop", "Phone", "Tablet", "Laptop", "Laptop", "Phone", "Tablet", "Phone"],
    "Price": [800, 500, 300, -100, 800, 500, 300, 0]
}

df = pd.DataFrame(data)
df

   Customer_ID    Name  Age       City Product  Price
0          101     Ali   22   Tashkent  Laptop    800
1          102    Vali   25  Samarkand   Phone    500
2          103   Hasan   -3   tashkent  Tablet    300
3          104   Husan   31    Bukhara  Laptop   -100
4          105     Ali   22   Tashkent  Laptop    800
5          106  Malika  150  Samarkand   Phone    500
6          107    Vali   28    Bukhara  Tablet    300
7          108  Zarina   24   Tashkent   Phone      0

1. `Name` ustunida takrorlangan mijozlar bor ekan
2. `Age` ustunida noto'g'ri qiymatlar bor
3. `City` ustunidagi qiymatlar har xil yozilgan
4. `Price` ustunida ham noto'g'ri qiymatlar mavjud

In [4]:
# DF haqida umumiy ma'lumot olish
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Customer_ID  8 non-null      int64
 1   Name         8 non-null      object
 2   Age          8 non-null      int64
 3   City         8 non-null      object
 4   Product      8 non-null      object
 5   Price        8 non-null      int64
dtypes: int64(3), object(3)
memory usage: 516.0+ bytes

In [8]:
# takrorlangan mijozlarni aniqlash
df[df['Name'].duplicated(keep=False)]

   Customer_ID  Name  Age       City Product  Price
0          101   Ali   22   Tashkent  Laptop    800
1          102  Vali   25  Samarkand   Phone    500
4          105   Ali   22   Tashkent  Laptop    800
6          107  Vali   28    Bukhara  Tablet    300

- Do'konda bir nechta mijozlar takrorlanishi tabiiy , chunki bitta mijoz bir necha marta savdo qilgan bo'lishi mumkin