<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/pandas_data_preparation/merge_join2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [3]:
customers = pd.DataFrame({
    "customer_id": [101, 102, 103, 104, 105],
    "name": ["Ali", "Vali", "Hasan", "Sardor", "Madina"],
    "city": ["Toshkent", "Samarqand", "Buxoro", "Toshkent", "Andijon"]
})

orders = pd.DataFrame({
    "order_id": [1, 2, 3, 4, 5, 6],
    "customer_id": [101, 102, 101, 105, 106, 103],
    "amount": [250, 180, 320, 450, 200, 150]
})

customers

   customer_id    name       city
0          101     Ali   Toshkent
1          102    Vali  Samarqand
2          103   Hasan     Buxoro
3          104  Sardor   Toshkent
4          105  Madina    Andijon

In [4]:
orders

   order_id  customer_id  amount
0         1          101     250
1         2          102     180
2         3          101     320
3         4          105     450
4         5          106     200
5         6          103     150

In [8]:
# Buyurtmalar jadvaliga mijozlarning ismi va shahrini qo‘shib, bitta umumiy jadval hosil qiling
orders_customers = pd.merge(orders, customers, on='customer_id')
orders_customers

   order_id  customer_id  amount    name       city
0         1          101     250     Ali   Toshkent
1         2          102     180    Vali  Samarqand
2         3          101     320     Ali   Toshkent
3         4          105     450  Madina    Andijon
4         6          103     150   Hasan     Buxoro