<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/pandas_data_preparation/merge_join2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
customers = pd.DataFrame({
    "customer_id": [101, 102, 103, 104, 105],
    "name": ["Ali", "Vali", "Hasan", "Sardor", "Madina"],
    "city": ["Toshkent", "Samarqand", "Buxoro", "Toshkent", "Andijon"]
})

orders = pd.DataFrame({
    "order_id": [1, 2, 3, 4, 5, 6],
    "customer_id": [101, 102, 101, 105, 106, 103],
    "amount": [250, 180, 320, 450, 200, 150]
})

customers

   customer_id    name       city
0          101     Ali   Toshkent
1          102    Vali  Samarqand
2          103   Hasan     Buxoro
3          104  Sardor   Toshkent
4          105  Madina    Andijon

In [3]:
orders

   order_id  customer_id  amount
0         1          101     250
1         2          102     180
2         3          101     320
3         4          105     450
4         5          106     200
5         6          103     150

In [4]:
# Buyurtmalar jadvaliga mijozlarning ismi va shahrini qo‘shib, bitta umumiy jadval hosil qiling
orders_customers = pd.merge(orders, customers, on='customer_id')
orders_customers

   order_id  customer_id  amount    name       city
0         1          101     250     Ali   Toshkent
1         2          102     180    Vali  Samarqand
2         3          101     320     Ali   Toshkent
3         4          105     450  Madina    Andijon
4         6          103     150   Hasan     Buxoro

**2-topshiriq**

In [5]:
products = pd.DataFrame({
    "product_id": [1, 2, 3, 4, 5],
    "product": ["Laptop", "Telefon", "Tablet", "Monitor", "Keyboard"],
    "category": ["Computer", "Mobile", "Mobile", "Computer", "Accessory"],
    "price": [800, 500, 300, 250, 50]
})
sales = pd.DataFrame({
    "sale_id": [1001, 1002, 1003, 1004, 1005, 1006, 1007],
    "product_id": [1, 2, 1, 3, 5, 2, 6],
    "quantity": [2, 3, 1, 4, 10, 2, 5]
})
products

   product_id   product   category  price
0           1    Laptop   Computer    800
1           2   Telefon     Mobile    500
2           3    Tablet     Mobile    300
3           4   Monitor   Computer    250
4           5  Keyboard  Accessory     50

In [6]:
sales

   sale_id  product_id  quantity
0     1001           1         2
1     1002           2         3
2     1003           1         1
3     1004           3         4
4     1005           5        10
5     1006           2         2
6     1007           6         5

In [10]:
sales_products = pd.merge(sales, products, on='product_id')
sales_products

   sale_id  product_id  quantity   product   category  price
0     1001           1         2    Laptop   Computer    800
1     1002           2         3   Telefon     Mobile    500
2     1003           1         1    Laptop   Computer    800
3     1004           3         4    Tablet     Mobile    300
4     1005           5        10  Keyboard  Accessory     50
5     1006           2         2   Telefon     Mobile    500

In [11]:
sales_products['quantity'] * sales_products['price']

0    1600
1    1500
2     800
3    1200
4     500
5    1000
dtype: int64