<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/pandas_data_preparation/merge_join2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
customers = pd.DataFrame({
    "customer_id": [101, 102, 103, 104, 105],
    "name": ["Ali", "Vali", "Hasan", "Sardor", "Madina"],
    "city": ["Toshkent", "Samarqand", "Buxoro", "Toshkent", "Andijon"]
})

orders = pd.DataFrame({
    "order_id": [1, 2, 3, 4, 5, 6],
    "customer_id": [101, 102, 101, 105, 106, 103],
    "amount": [250, 180, 320, 450, 200, 150]
})

customers

   customer_id    name       city
0          101     Ali   Toshkent
1          102    Vali  Samarqand
2          103   Hasan     Buxoro
3          104  Sardor   Toshkent
4          105  Madina    Andijon

In [3]:
orders

   order_id  customer_id  amount
0         1          101     250
1         2          102     180
2         3          101     320
3         4          105     450
4         5          106     200
5         6          103     150

In [4]:
# Buyurtmalar jadvaliga mijozlarning ismi va shahrini qo‘shib, bitta umumiy jadval hosil qiling
orders_customers = pd.merge(orders, customers, on='customer_id')
orders_customers

   order_id  customer_id  amount    name       city
0         1          101     250     Ali   Toshkent
1         2          102     180    Vali  Samarqand
2         3          101     320     Ali   Toshkent
3         4          105     450  Madina    Andijon
4         6          103     150   Hasan     Buxoro

**2-topshiriq**

In [5]:
products = pd.DataFrame({
    "product_id": [1, 2, 3, 4, 5],
    "product": ["Laptop", "Telefon", "Tablet", "Monitor", "Keyboard"],
    "category": ["Computer", "Mobile", "Mobile", "Computer", "Accessory"],
    "price": [800, 500, 300, 250, 50]
})
sales = pd.DataFrame({
    "sale_id": [1001, 1002, 1003, 1004, 1005, 1006, 1007],
    "product_id": [1, 2, 1, 3, 5, 2, 6],
    "quantity": [2, 3, 1, 4, 10, 2, 5]
})
products

   product_id   product   category  price
0           1    Laptop   Computer    800
1           2   Telefon     Mobile    500
2           3    Tablet     Mobile    300
3           4   Monitor   Computer    250
4           5  Keyboard  Accessory     50

In [6]:
sales

   sale_id  product_id  quantity
0     1001           1         2
1     1002           2         3
2     1003           1         1
3     1004           3         4
4     1005           5        10
5     1006           2         2
6     1007           6         5

In [7]:
# Savdo ma’lumotlarini mahsulot ma’lumotlari bilan birlashtiring
sales_products = pd.merge(sales, products, on='product_id')
sales_products

   sale_id  product_id  quantity   product   category  price
0     1001           1         2    Laptop   Computer    800
1     1002           2         3   Telefon     Mobile    500
2     1003           1         1    Laptop   Computer    800
3     1004           3         4    Tablet     Mobile    300
4     1005           5        10  Keyboard  Accessory     50
5     1006           2         2   Telefon     Mobile    500

In [8]:
# Har bir savdo uchun umumiy savdo summasini hisoblang
sales_products['quantity'] * sales_products['price']

0    1600
1    1500
2     800
3    1200
4     500
5    1000
dtype: int64

**Uchinchi topshiriq**

In [9]:
students = pd.DataFrame({
    "student_id": [101, 102, 103, 104, 105],
    "name": ["Ali", "Vali", "Hasan", "Sardor", "Madina"],
    "group": ["A", "A", "B", "B", "C"]
})
courses = pd.DataFrame({
    "course_id": [1, 2, 3, 4],
    "course": ["Python", "Statistics", "SQL", "Machine Learning"],
    "teacher": ["Anvar", "Dilshod", "Anvar", "Kamola"]
})

enrollments = pd.DataFrame({
    "student_id": [101, 101, 102, 103, 103, 104, 106],
    "course_id": [1, 2, 1, 2, 3, 4, 1],
    "score": [92, 85, 88, 79, 91, 95, 70]
})

students

   student_id    name group
0         101     Ali     A
1         102    Vali     A
2         103   Hasan     B
3         104  Sardor     B
4         105  Madina     C

In [10]:
courses

   course_id            course  teacher
0          1            Python    Anvar
1          2        Statistics  Dilshod
2          3               SQL    Anvar
3          4  Machine Learning   Kamola

In [11]:
enrollments

   student_id  course_id  score
0         101          1     92
1         101          2     85
2         102          1     88
3         103          2     79
4         103          3     91
5         104          4     95
6         106          1     70

In [12]:
# students va enrollments jadvallarini birlashtirish
st_enroll = pd.merge(students, enrollments, on='student_id')
st_enroll

   student_id    name group  course_id  score
0         101     Ali     A          1     92
1         101     Ali     A          2     85
2         102    Vali     A          1     88
3         103   Hasan     B          2     79
4         103   Hasan     B          3     91
5         104  Sardor     B          4     95

In [13]:
# yuqorida birlashtirilgan jadvalga uchinchi DF ni qo'shish
three_df = pd.merge(st_enroll, courses, on='course_id')
three_df

   student_id    name group  course_id  score            course  teacher
0         101     Ali     A          1     92            Python    Anvar
1         101     Ali     A          2     85        Statistics  Dilshod
2         102    Vali     A          1     88            Python    Anvar
3         103   Hasan     B          2     79        Statistics  Dilshod
4         103   Hasan     B          3     91               SQL    Anvar
5         104  Sardor     B          4     95  Machine Learning   Kamola

In [14]:
# talabaning ismi, guruhi, kurs nomi , o'qituvchisi , balini olish
three_df[['name', 'group', 'course', 'teacher', 'score']]

     name group            course  teacher  score
0     Ali     A            Python    Anvar     92
1     Ali     A        Statistics  Dilshod     85
2    Vali     A            Python    Anvar     88
3   Hasan     B        Statistics  Dilshod     79
4   Hasan     B               SQL    Anvar     91
5  Sardor     B  Machine Learning   Kamola     95

In [15]:
# Hosil bo‘lgan jadvaldan Ali qaysi kurslarda o‘qiyotgani va har bir kursdan olgan balini ko‘rish mumkin bo‘lsin
ali = three_df[three_df['name'] == 'Ali']
ali[['course', 'score']]

       course  score
0      Python     92
1  Statistics     85

In [16]:
# course_id = 4 bo‘lgan kursga yozilgan talabaning ismi va bahosini toping
three_df[three_df['course_id'] == 4][['name', 'score']]

     name  score
5  Sardor     95

**To'rtinchi topshiriq**

In [17]:
customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4, 5],
    "customer_name": ["Aziza", "Bekzod", "Dilnoza", "Jasur", "Malika"],
    "region": ["Toshkent", "Samarqand", "Toshkent", "Buxoro", "Andijon"]
})

orders = pd.DataFrame({
    "order_id": [1001, 1002, 1003, 1004, 1005, 1006],
    "customer_id": [1, 2, 1, 5, 7, 3],
    "product_id": [101, 102, 103, 101, 104, 102],
    "quantity": [2, 1, 3, 2, 5, 1]
})

products = pd.DataFrame({
    "product_id": [101, 102, 103, 104, 105],
    "product_name": ["Laptop", "Telefon", "Tablet", "Monitor", "Keyboard"],
    "category": ["Computer", "Mobile", "Mobile", "Computer", "Accessory"],
    "price": [800, 500, 300, 250, 50]
})

customers

   customer_id customer_name     region
0            1         Aziza   Toshkent
1            2        Bekzod  Samarqand
2            3       Dilnoza   Toshkent
3            4         Jasur     Buxoro
4            5        Malika    Andijon

In [18]:
orders

   order_id  customer_id  product_id  quantity
0      1001            1         101         2
1      1002            2         102         1
2      1003            1         103         3
3      1004            5         101         2
4      1005            7         104         5
5      1006            3         102         1

In [19]:
products

   product_id product_name   category  price
0         101       Laptop   Computer    800
1         102      Telefon     Mobile    500
2         103       Tablet     Mobile    300
3         104      Monitor   Computer    250
4         105     Keyboard  Accessory     50

In [20]:
# customers va orders jadvallarini birlashtirish
custom_orders = pd.merge(customers, orders, on='customer_id')
custom_orders

   customer_id customer_name     region  order_id  product_id  quantity
0            1         Aziza   Toshkent      1001         101         2
1            1         Aziza   Toshkent      1003         103         3
2            2        Bekzod  Samarqand      1002         102         1
3            3       Dilnoza   Toshkent      1006         102         1
4            5        Malika    Andijon      1004         101         2

In [21]:
# yuqoridagi jadvalga products jadvalini qo'shish
main_df = pd.merge(custom_orders, products, on='product_id')
df1 = main_df[['order_id', 'customer_name', 'region', 'product_name', 'category', 'quantity', 'price']]
df1

   order_id customer_name     region product_name  category  quantity  price
0      1001         Aziza   Toshkent       Laptop  Computer         2    800
1      1003         Aziza   Toshkent       Tablet    Mobile         3    300
2      1002        Bekzod  Samarqand      Telefon    Mobile         1    500
3      1006       Dilnoza   Toshkent      Telefon    Mobile         1    500
4      1004        Malika    Andijon       Laptop  Computer         2    800

In [22]:
# har bir buyurtma uchun umumiy buyurtma summasini hisoblang
main_df['quantity']*main_df['price']

0    1600
1     900
2     500
3     500
4    1600
dtype: int64

In [23]:
# Hech qanday buyurtma qilmagan mijozlar ham yakuniy jadvalda ko‘rinsin
pd.merge(customers, orders, on='customer_id', how='left')

   customer_id customer_name     region  order_id  product_id  quantity
0            1         Aziza   Toshkent    1001.0       101.0       2.0
1            1         Aziza   Toshkent    1003.0       103.0       3.0
2            2        Bekzod  Samarqand    1002.0       102.0       1.0
3            3       Dilnoza   Toshkent    1006.0       102.0       1.0
4            4         Jasur     Buxoro       NaN         NaN       NaN
5            5        Malika    Andijon    1004.0       101.0       2.0

In [24]:
# Hech qachon sotilmagan mahsulotlar ham yakuniy natijada ko‘rinsin
pd.merge(custom_orders, products, on='product_id', how='right')

,customer_id,customer_name,region,order_id,product_id,quantity,product_name,category,price
0,1.0,Aziza,Toshkent,1001.0,101,2.0,Laptop,Computer,800
1,5.0,Malika,Andijon,1004.0,101,2.0,Laptop,Computer,800
2,2.0,Bekzod,Samarqand,1002.0,102,1.0,Telefon,Mobile,500
3,3.0,Dilnoza,Toshkent,1006.0,102,1.0,Telefon,Mobile,500
4,1.0,Aziza,Toshkent,1003.0,103,3.0,Tablet,Mobile,300
5,NaN,NaN,NaN,NaN,104,NaN,Monitor,Computer,250
6,NaN,NaN,NaN,NaN,105,NaN,Keyboard,Accessory,50

In [25]:
# customer_id = 7 bo‘lgan buyurtmani tekshiring
pd.merge(customers, orders, on='customer_id', how='right')

   customer_id customer_name     region  order_id  product_id  quantity
0            1         Aziza   Toshkent      1001         101         2
1            2        Bekzod  Samarqand      1002         102         1
2            1         Aziza   Toshkent      1003         103         3
3            5        Malika    Andijon      1004         101         2
4            7           NaN        NaN      1005         104         5
5            3       Dilnoza   Toshkent      1006         102         1

In [26]:
# product_id = 105 bo‘lgan mahsulotni tekshiring
pd.merge(custom_orders, products, on='product_id', how='right')

,customer_id,customer_name,region,order_id,product_id,quantity,product_name,category,price
0,1.0,Aziza,Toshkent,1001.0,101,2.0,Laptop,Computer,800
1,5.0,Malika,Andijon,1004.0,101,2.0,Laptop,Computer,800
2,2.0,Bekzod,Samarqand,1002.0,102,1.0,Telefon,Mobile,500
3,3.0,Dilnoza,Toshkent,1006.0,102,1.0,Telefon,Mobile,500
4,1.0,Aziza,Toshkent,1003.0,103,3.0,Tablet,Mobile,300
5,NaN,NaN,NaN,NaN,104,NaN,Monitor,Computer,250
6,NaN,NaN,NaN,NaN,105,NaN,Keyboard,Accessory,50

In [27]:
# Mijoz + buyurtma + mahsulot — hammasi mavjud
main_df[['customer_name', 'order_id', 'product_name']]

  customer_name  order_id product_name
0         Aziza      1001       Laptop
1         Aziza      1003       Tablet
2        Bekzod      1002      Telefon
3       Dilnoza      1006      Telefon
4        Malika      1004       Laptop

In [28]:
# Mijoz mavjud, lekin buyurtmasi yo‘q
pd.merge(customers, orders, on='customer_id', how='left')

   customer_id customer_name     region  order_id  product_id  quantity
0            1         Aziza   Toshkent    1001.0       101.0       2.0
1            1         Aziza   Toshkent    1003.0       103.0       3.0
2            2        Bekzod  Samarqand    1002.0       102.0       1.0
3            3       Dilnoza   Toshkent    1006.0       102.0       1.0
4            4         Jasur     Buxoro       NaN         NaN       NaN
5            5        Malika    Andijon    1004.0       101.0       2.0

In [29]:
# Buyurtma mavjud, lekin mijoz ma'lumoti topilmagan
pd.merge(customers, orders, on='customer_id', how='right')

   customer_id customer_name     region  order_id  product_id  quantity
0            1         Aziza   Toshkent      1001         101         2
1            2        Bekzod  Samarqand      1002         102         1
2            1         Aziza   Toshkent      1003         103         3
3            5        Malika    Andijon      1004         101         2
4            7           NaN        NaN      1005         104         5
5            3       Dilnoza   Toshkent      1006         102         1

**Beshinchi topshiriq**

In [30]:
students = pd.DataFrame({
    "name": ["Ali", "Vali", "Hasan", "Husan"],
    "group": ["A", "B", "A", "C"]
}, index=[101, 102, 103, 104])

scores = pd.DataFrame({
    "score": [92, 85, 78],
    "exam": ["Midterm", "Midterm", "Midterm"]
}, index=[101, 102, 103])
students

      name group
101    Ali     A
102   Vali     B
103  Hasan     A
104  Husan     C

In [31]:
scores

     score     exam
101     92  Midterm
102     85  Midterm
103     78  Midterm

In [32]:
# Talabalar va ularning imtihon natijalarini indekslar orqali birlashtiring
# Talabalar ro‘yxatidagi barcha talabalar saqlanishi kerak
pd.merge(students, scores, left_index=True, right_index=True, how='left')

      name group  score     exam
101    Ali     A   92.0  Midterm
102   Vali     B   85.0  Midterm
103  Hasan     A   78.0  Midterm
104  Husan     C    NaN      NaN

In [45]:
products = pd.DataFrame({
    "product_name": ["Laptop", "Phone", "Tablet"],
    "category": ["Computer", "Mobile", "Computer"]
}, index=[201, 202, 203])

sales = pd.DataFrame({
    "quantity": [5, 8, 3, 10],
    "revenue": [5000, 8000, 2400, 9000]
}, index=[202, 203, 204, 205])
products

    product_name  category
201       Laptop  Computer
202        Phone    Mobile
203       Tablet  Computer

In [46]:
sales

     quantity  revenue
202         5     5000
203         8     8000
204         3     2400
205        10     9000

In [48]:
# Mahsulotlar va sotuvlar haqidagi ma'lumotlarni indekslar orqali birlashtiring
# sotuvlar jadvalidagi barcha ma'lumotlar saqlanishi kerak
pd.merge(products, sales, left_index=True, right_index=True, how='right')

    product_name  category  quantity  revenue
202        Phone    Mobile         5     5000
203       Tablet  Computer         8     8000
204          NaN       NaN         3     2400
205          NaN       NaN        10     9000

In [49]:
employees = pd.DataFrame({
    "name": ["Ali", "Vali", "Hasan", "Husan"],
    "department": ["IT", "HR", "IT", "Finance"]
}, index=[301, 302, 303, 304])

bonuses = pd.DataFrame({
    "bonus": [500, 700, 900, 1000],
    "year": [2025, 2025, 2025, 2025]
}, index=[302, 303, 305, 306])
employees

      name department
301    Ali         IT
302   Vali         HR
303  Hasan         IT
304  Husan    Finance

In [50]:
bonuses

     bonus  year
302    500  2025
303    700  2025
305    900  2025
306   1000  2025

In [51]:
# Xodimlar va bonuslar ma'lumotlarini indekslar asosida birlashtiring
# Ikkala DataFrame'dagi barcha indekslar natijada saqlanishi kerak
pd.merge(employees, bonuses, left_index=True, right_index=True, how='outer')

      name department   bonus    year
301    Ali         IT     NaN     NaN
302   Vali         HR   500.0  2025.0
303  Hasan         IT   700.0  2025.0
304  Husan    Finance     NaN     NaN
305    NaN        NaN   900.0  2025.0
306    NaN        NaN  1000.0  2025.0

####**Join**

In [33]:
students = pd.DataFrame({
    "name": ["Ali", "Vali", "Hasan", "Husan"],
    "group": ["A", "B", "A", "C"]
}, index=[101, 102, 103, 104])

scores = pd.DataFrame({
    "score": [90, 85, 78],
    "attendance": [95, 88, 92]
}, index=[101, 102, 103])
students

      name group
101    Ali     A
102   Vali     B
103  Hasan     A
104  Husan     C

In [34]:
scores

     score  attendance
101     90          95
102     85          88
103     78          92

In [35]:
# sutdents asosiy bo'lsin va scores bilan indeks bo'yicha bog'lansin
students.join(scores, how='left')

      name group  score  attendance
101    Ali     A   90.0        95.0
102   Vali     B   85.0        88.0
103  Hasan     A   78.0        92.0
104  Husan     C    NaN         NaN

In [36]:
employees = pd.DataFrame({
    "name": ["Ali", "Vali", "Hasan", "Husan"],
    "department": ["IT", "HR", "IT", "Finance"]
}, index=[1, 2, 3, 4])

salary = pd.DataFrame({
    "salary": [800, 1000, 1200, 1500],
    "bonus": [100, 150, 200, 250]
}, index=[2, 3, 5, 6])
employees

    name department
1    Ali         IT
2   Vali         HR
3  Hasan         IT
4  Husan    Finance

In [37]:
salary

   salary  bonus
2     800    100
3    1000    150
5    1200    200
6    1500    250

In [38]:
# xodimlar va maoshlarni birlashtiring , faqat ikkala DataFrame’da ham mavjud bo‘lgan xodimlar qolishi kerak
employees.join(salary, how='inner')

    name department  salary  bonus
2   Vali         HR     800    100
3  Hasan         IT    1000    150

In [39]:
products = pd.DataFrame({
    "product_name": ["Laptop", "Phone", "Tablet"],
    "category": ["Electronics", "Electronics", "Electronics"]
}, index=[101, 102, 103])

sales = pd.DataFrame({
    "quantity": [5, 8, 3, 10],
    "revenue": [5000, 8000, 2400, 9000]
}, index=[102, 103, 104, 105])
products

    product_name     category
101       Laptop  Electronics
102        Phone  Electronics
103       Tablet  Electronics

In [40]:
sales

     quantity  revenue
102         5     5000
103         8     8000
104         3     2400
105        10     9000

In [41]:
# Sotuvlar jadvalidagi barcha ma’lumotlar yo‘qolmasligi kerak
products.join(sales, how='right')

    product_name     category  quantity  revenue
102        Phone  Electronics         5     5000
103       Tablet  Electronics         8     8000
104          NaN          NaN         3     2400
105          NaN          NaN        10     9000

In [42]:
customers = pd.DataFrame({
    "name": ["Ali", "Vali", "Hasan"],
    "city": ["Toshkent", "Samarqand", "Buxoro"]
}, index=[1, 2, 3])

orders = pd.DataFrame({
    "product": ["Laptop", "Phone", "Tablet"],
    "amount": [1200, 800, 500]
}, index=[2, 3, 4])
customers

    name       city
1    Ali   Toshkent
2   Vali  Samarqand
3  Hasan     Buxoro

In [43]:
orders

  product  amount
2  Laptop    1200
3   Phone     800
4  Tablet     500

In [44]:
# Ikkala DataFrame’dagi barcha indekslar natijada saqlanishi kerak
customers.join(orders, how='outer')

    name       city product  amount
1    Ali   Toshkent     NaN     NaN
2   Vali  Samarqand  Laptop  1200.0
3  Hasan     Buxoro   Phone   800.0
4    NaN        NaN  Tablet   500.0