<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/pandas_data_preparation/multi_columns.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

**Do'kon savdolari ma'lumotlari**

In [2]:
columns = pd.MultiIndex.from_tuples(
    [
        ("Sotuv", "Laptop"),
        ("Sotuv", "Telefon"),
        ("Sotuv", "Tablet"),
        ("Daromad", "Laptop"),
        ("Daromad", "Telefon"),
        ("Daromad", "Tablet")
    ],
    names=["Ko‘rsatkich", "Mahsulot"]
)

data = [
    [120, 180, 90, 12000, 18000, 9000],
    [150, 210, 110, 15000, 21000, 11000],
    [170, 230, 130, 17000, 23000, 13000],
    [140, 190, 100, 14000, 19000, 10000]
]

index = ["Toshkent", "Samarqand", "Buxoro", "Fargona"]

sales = pd.DataFrame(data, index=index, columns=columns)
sales

Ko‘rsatkich  Sotuv                Daromad
Mahsulot    Laptop Telefon Tablet  Laptop Telefon Tablet
Toshkent       120     180     90   12000   18000   9000
Samarqand      150     210    110   15000   21000  11000
Buxoro         170     230    130   17000   23000  13000
Fargona        140     190    100   14000   19000  10000

In [3]:
# Faqat Sotuv ko‘rsatkichiga tegishli barcha mahsulotlarni oling
sales['Sotuv']

Mahsulot   Laptop  Telefon  Tablet
Toshkent      120      180      90
Samarqand     150      210     110
Buxoro        170      230     130
Fargona       140      190     100

In [4]:
# Faqat Laptop mahsulotining Sotuv va Daromad ma’lumotlarini oling
sales.xs('Laptop', level='Mahsulot', axis=1)

Ko‘rsatkich  Sotuv  Daromad
Toshkent       120    12000
Samarqand      150    15000
Buxoro         170    17000
Fargona        140    14000

In [5]:
# Faqat Telefon uchun Daromad qiymatlarini oling
sales[('Daromad', 'Telefon')]

Toshkent     18000
Samarqand    21000
Buxoro       23000
Fargona      19000
Name: (Daromad, Telefon), dtype: int64

In [6]:
# Toshkent va Buxoro hududlarining faqat Sotuv ma’lumotlarini oling
sales.loc[['Toshkent', 'Buxoro'], 'Sotuv']

Mahsulot  Laptop  Telefon  Tablet
Toshkent     120      180      90
Buxoro       170      230     130

**2-topshiriq**

In [7]:
columns = pd.MultiIndex.from_tuples(
    [
        (2023, "Sotuv"),
        (2023, "Daromad"),
        (2023, "Buyurtma"),
        (2024, "Sotuv"),
        (2024, "Daromad"),
        (2024, "Buyurtma")
    ],
    names=["Yil", "Ko‘rsatkich"]
)

data = [
    [120, 12000, 12, 150, 15000, 15],
    [100, 10000, 10, 140, 14000, 14],
    [90, 9000, 9, 130, 13000, 13],
    [110, 11000, 11, 160, 16000, 16]
]

df = pd.DataFrame(
    data,
    index=["Toshkent", "Samarqand", "Buxoro", "Fargona"],
    columns=columns
)
df

Yil          2023                   2024
Ko‘rsatkich Sotuv Daromad Buyurtma Sotuv Daromad Buyurtma
Toshkent      120   12000       12   150   15000       15
Samarqand     100   10000       10   140   14000       14
Buxoro         90    9000        9   130   13000       13
Fargona       110   11000       11   160   16000       16

In [8]:
# Faqat 2023-yil ma’lumotlarini oling
df[2023]

Ko‘rsatkich  Sotuv  Daromad  Buyurtma
Toshkent       120    12000        12
Samarqand      100    10000        10
Buxoro          90     9000         9
Fargona        110    11000        11

In [9]:
# Faqat Daromad ko‘rsatkichining 2023 va 2024-yillardagi qiymatlarini oling
df.xs('Daromad', level='Ko‘rsatkich', axis=1)

Yil         2023   2024
Toshkent   12000  15000
Samarqand  10000  14000
Buxoro      9000  13000
Fargona    11000  16000

In [13]:
# Faqat 2024-yil Sotuv ma’lumotlarini oling
df[(2024, 'Sotuv')]

Toshkent     150
Samarqand    140
Buxoro       130
Fargona      160
Name: (2024, Sotuv), dtype: int64

In [11]:
# Toshkent uchun 2023 va 2024-yillardagi barcha ma’lumotlarni oling
df.loc['Toshkent']

Yil   Ko‘rsatkich
2023  Sotuv            120
      Daromad        12000
      Buyurtma          12
2024  Sotuv            150
      Daromad        15000
      Buyurtma          15
Name: Toshkent, dtype: int64

In [12]:
# Buxoro uchun faqat 2024-yil ma’lumotlarini oling
df.loc['Buxoro', 2024]

Ko‘rsatkich
Sotuv         130
Daromad     13000
Buyurtma       13
Name: Buxoro, dtype: int64

**3-topshiriq**

In [14]:
columns = pd.MultiIndex.from_tuples(
    [
        ("Laptop", "Sotuv"),
        ("Laptop", "Daromad"),
        ("Laptop", "Buyurtma"),
        ("Telefon", "Sotuv"),
        ("Telefon", "Daromad"),
        ("Telefon", "Buyurtma"),
        ("Tablet", "Sotuv"),
        ("Tablet", "Daromad"),
        ("Tablet", "Buyurtma")
    ],
    names=["Mahsulot", "Ko‘rsatkich"]
)

data = [
    [120, 12000, 12, 180, 18000, 18, 90, 9000, 9],
    [150, 15000, 15, 210, 21000, 21, 110, 11000, 11],
    [100, 10000, 10, 160, 16000, 16, 80, 8000, 8],
    [140, 14000, 14, 200, 20000, 20, 100, 10000, 10]
]

df3 = pd.DataFrame(
    data,
    index=["Toshkent", "Samarqand", "Buxoro", "Fargona"],
    columns=columns
)
df3

Mahsulot    Laptop                  Telefon                  Tablet          \
Ko‘rsatkich  Sotuv Daromad Buyurtma   Sotuv Daromad Buyurtma  Sotuv Daromad
Toshkent       120   12000       12     180   18000       18     90    9000
Samarqand      150   15000       15     210   21000       21    110   11000
Buxoro         100   10000       10     160   16000       16     80    8000
Fargona        140   14000       14     200   20000       20    100   10000

Mahsulot
Ko‘rsatkich Buyurtma
Toshkent           9
Samarqand         11
Buxoro             8
Fargona           10

In [22]:
# Ustunlarning darajalarini shunday almashtiringki, Ko‘rsatkich birinchi daraja, Mahsulot ikkinchi daraja bo‘lsin
df3_swap = df3.swaplevel("Mahsulot", "Ko‘rsatkich", axis=1)
df3_swap

Ko‘rsatkich,Sotuv,Daromad,Buyurtma,Sotuv,Daromad,Buyurtma,Sotuv,Daromad,Buyurtma
Mahsulot,Laptop,Laptop,Laptop,Telefon,Telefon,Telefon,Tablet,Tablet,Tablet
Toshkent,120,12000,12,180,18000,18,90,9000,9
Samarqand,150,15000,15,210,21000,21,110,11000,11
Buxoro,100,10000,10,160,16000,16,80,8000,8
Fargona,140,14000,14,200,20000,20,100,10000,10

In [24]:
# Hosil bo‘lgan jadvalni ustunlar bo‘yicha tartibli holatga keltiring
df3_swap.sort_index(axis=1, level=0)

Ko‘rsatkich Buyurtma                Daromad                 Sotuv         \
Mahsulot      Laptop Tablet Telefon  Laptop Tablet Telefon Laptop Tablet
Toshkent          12      9      18   12000   9000   18000    120     90
Samarqand         15     11      21   15000  11000   21000    150    110
Buxoro            10      8      16   10000   8000   16000    100     80
Fargona           14     10      20   14000  10000   20000    140    100

Ko‘rsatkich
Mahsulot    Telefon
Toshkent        180
Samarqand       210
Buxoro          160
Fargona         200

**4-topshiriq**

In [25]:
columns = pd.MultiIndex.from_tuples(
    [
        ("2024", "Laptop", "Sotuv"),
        ("2024", "Laptop", "Daromad"),
        ("2024", "Telefon", "Sotuv"),
        ("2024", "Telefon", "Daromad"),

        ("2023", "Laptop", "Sotuv"),
        ("2023", "Laptop", "Daromad"),
        ("2023", "Telefon", "Sotuv"),
        ("2023", "Telefon", "Daromad")
    ],
    names=["Yil", "Mahsulot", "Ko‘rsatkich"]
)

data = [
    [150, 15000, 220, 22000, 120, 12000, 180, 18000],
    [170, 17000, 250, 25000, 140, 14000, 200, 20000],
    [130, 13000, 190, 19000, 100, 10000, 160, 16000],
    [160, 16000, 230, 23000, 130, 13000, 190, 19000]
]

df4 = pd.DataFrame(
    data,
    index=["Toshkent", "Samarqand", "Buxoro", "Fargona"],
    columns=columns
)
df4

Yil           2024                           2023
Mahsulot    Laptop         Telefon         Laptop         Telefon
Ko‘rsatkich  Sotuv Daromad   Sotuv Daromad  Sotuv Daromad   Sotuv Daromad
Toshkent       150   15000     220   22000    120   12000     180   18000
Samarqand      170   17000     250   25000    140   14000     200   20000
Buxoro         130   13000     190   19000    100   10000     160   16000
Fargona        160   16000     230   23000    130   13000     190   19000

In [28]:
# Faqat 2024-yil ma’lumotlarini oling
df4['2024']

Mahsulot    Laptop         Telefon
Ko‘rsatkich  Sotuv Daromad   Sotuv Daromad
Toshkent       150   15000     220   22000
Samarqand      170   17000     250   25000
Buxoro         130   13000     190   19000
Fargona        160   16000     230   23000

In [31]:
# Faqat 2023-yildagi Telefon ma’lumotlarini oling
df4.xs('Telefon', level='Mahsulot', axis=1)['2023']

Ko‘rsatkich  Sotuv  Daromad
Toshkent       180    18000
Samarqand      200    20000
Buxoro         160    16000
Fargona        190    19000

In [34]:
# Faqat 2024-yildagi Laptop → Sotuv qiymatlarini oling
df4[('2024', 'Laptop', 'Sotuv')]

Toshkent     150
Samarqand    170
Buxoro       130
Fargona      160
Name: (2024, Laptop, Sotuv), dtype: int64

In [45]:
# Ustunlar tartibini shunday o‘zgartiringki, Ko‘rsatkich → Mahsulot → Yil tartibida bo‘lsin
df4_swap = df4.swaplevel(2, 0, axis=1).sort_index(axis=1)
df4_swap

Ko‘rsatkich Daromad                        Sotuv
Mahsulot     Laptop        Telefon        Laptop      Telefon
Yil            2023   2024    2023   2024   2023 2024    2023 2024
Toshkent      12000  15000   18000  22000    120  150     180  220
Samarqand     14000  17000   20000  25000    140  170     200  250
Buxoro        10000  13000   16000  19000    100  130     160  190
Fargona       13000  16000   19000  23000    130  160     190  230

In [47]:
# Yakuniy jadvaldan faqat Sotuv ma’lumotlarini ajrating
df4_swap['Sotuv']

Mahsulot  Laptop      Telefon
Yil         2023 2024    2023 2024
Toshkent     120  150     180  220
Samarqand    140  170     200  250
Buxoro       100  130     160  190
Fargona      130  160     190  230

In [52]:
# Yakuniy jadvalda Laptop va Telefon sotuvlarini 2023 va 2024 yillar bo‘yicha bir qarashda taqqoslash mumkin bo‘lsin
sotuv = df4_swap['Sotuv']
sotuv.stack(level='Mahsulot', future_stack=True)

Yil                 2023  2024
          Mahsulot
Toshkent  Laptop     120   150
          Telefon    180   220
Samarqand Laptop     140   170
          Telefon    200   250
Buxoro    Laptop     100   130
          Telefon    160   190
Fargona   Laptop     130   160
          Telefon    190   230