<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/pandas_data_preparation/multi_columns.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

**Do'kon savdolari ma'lumotlari**

In [2]:
columns = pd.MultiIndex.from_tuples(
    [
        ("Sotuv", "Laptop"),
        ("Sotuv", "Telefon"),
        ("Sotuv", "Tablet"),
        ("Daromad", "Laptop"),
        ("Daromad", "Telefon"),
        ("Daromad", "Tablet")
    ],
    names=["Ko‘rsatkich", "Mahsulot"]
)

data = [
    [120, 180, 90, 12000, 18000, 9000],
    [150, 210, 110, 15000, 21000, 11000],
    [170, 230, 130, 17000, 23000, 13000],
    [140, 190, 100, 14000, 19000, 10000]
]

index = ["Toshkent", "Samarqand", "Buxoro", "Fargona"]

sales = pd.DataFrame(data, index=index, columns=columns)
sales

Ko‘rsatkich  Sotuv                Daromad
Mahsulot    Laptop Telefon Tablet  Laptop Telefon Tablet
Toshkent       120     180     90   12000   18000   9000
Samarqand      150     210    110   15000   21000  11000
Buxoro         170     230    130   17000   23000  13000
Fargona        140     190    100   14000   19000  10000

In [3]:
# Faqat Sotuv ko‘rsatkichiga tegishli barcha mahsulotlarni oling
sales['Sotuv']

Mahsulot   Laptop  Telefon  Tablet
Toshkent      120      180      90
Samarqand     150      210     110
Buxoro        170      230     130
Fargona       140      190     100

In [7]:
# Faqat Laptop mahsulotining Sotuv va Daromad ma’lumotlarini oling
sales.xs('Laptop', level='Mahsulot', axis=1)

Ko‘rsatkich  Sotuv  Daromad
Toshkent       120    12000
Samarqand      150    15000
Buxoro         170    17000
Fargona        140    14000

In [10]:
# Faqat Telefon uchun Daromad qiymatlarini oling
sales[('Daromad', 'Telefon')]

Toshkent     18000
Samarqand    21000
Buxoro       23000
Fargona      19000
Name: (Daromad, Telefon), dtype: int64

In [12]:
# Toshkent va Buxoro hududlarining faqat Sotuv ma’lumotlarini oling
sales.loc[['Toshkent', 'Buxoro'], 'Sotuv']

Mahsulot  Laptop  Telefon  Tablet
Toshkent     120      180      90
Buxoro       170      230     130