<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/pandas_data_preparation/multi_index2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

**Talabalarning fanlar bo‘yicha natijalari**

In [2]:
data = {
    "Ball": [86, 91, 78, 88, 95, 82, 76, 89],
    "Davomat": [92, 96, 85, 90, 98, 88, 80, 94]
}

index = pd.MultiIndex.from_tuples(
    [
        ("Ali", "Matematika"),
        ("Ali", "Python"),
        ("Vali", "Matematika"),
        ("Vali", "Python"),
        ("Hasan", "Matematika"),
        ("Hasan", "Python"),
        ("Sardor", "Matematika"),
        ("Sardor", "Python")
    ],
    names=["Talaba", "Fan"]
)

df = pd.DataFrame(data, index=index)
df

                   Ball  Davomat
Talaba Fan
Ali    Matematika    86       92
       Python        91       96
Vali   Matematika    78       85
       Python        88       90
Hasan  Matematika    95       98
       Python        82       88
Sardor Matematika    76       80
       Python        89       94

In [3]:
# indeksni tekshirish
df.index

MultiIndex([(   'Ali', 'Matematika'),
            (   'Ali',     'Python'),
            (  'Vali', 'Matematika'),
            (  'Vali',     'Python'),
            ( 'Hasan', 'Matematika'),
            ( 'Hasan',     'Python'),
            ('Sardor', 'Matematika'),
            ('Sardor',     'Python')],
           names=['Talaba', 'Fan'])

In [5]:
# Faqat Alining barcha fanlar bo‘yicha ma’lumotlarini olish
df.loc['Ali']

            Ball  Davomat
Fan
Matematika    86       92
Python        91       96

In [8]:
# Faqat Python fanidan barcha talabalar natijasini olish
df.xs('Python', level=1)

        Ball  Davomat
Talaba
Ali       91       96
Vali      88       90
Hasan     82       88
Sardor    89       94

In [11]:
# Alining faqat Python fanidagi Ball qiymatini olish
df.loc['Ali', 'Python']['Ball']

np.int64(91)

In [13]:
# Matematika fanidan barcha talabalarni va ularning Ball hamda Davomat qiymatlarini olish
df.xs('Matematika', level=1)

        Ball  Davomat
Talaba
Ali       86       92
Vali      78       85
Hasan     95       98
Sardor    76       80

**Do‘kon savdolari ma'lumotlari**

In [14]:
data = {
    "Sotuv": [120, 150, 90, 200, 180, 110, 250, 210],
    "Daromad": [1200, 1500, 900, 2000, 1800, 1100, 2500, 2100]
}

index = pd.MultiIndex.from_tuples(
    [
        ("Toshkent", "Yanvar"),
        ("Toshkent", "Fevral"),
        ("Toshkent", "Mart"),
        ("Samarqand", "Yanvar"),
        ("Samarqand", "Fevral"),
        ("Samarqand", "Mart"),
        ("Buxoro", "Yanvar"),
        ("Buxoro", "Fevral")
    ],
    names=["Shahar", "Oy"]
)

sales = pd.DataFrame(data, index=index)
sales

                  Sotuv  Daromad
Shahar    Oy
Toshkent  Yanvar    120     1200
          Fevral    150     1500
          Mart       90      900
Samarqand Yanvar    200     2000
          Fevral    180     1800
          Mart      110     1100
Buxoro    Yanvar    250     2500
          Fevral    210     2100

In [16]:
# Faqat Toshkent shahrining barcha oylaridagi ma’lumotlarni olish
sales.loc['Toshkent']

        Sotuv  Daromad
Oy
Yanvar    120     1200
Fevral    150     1500
Mart       90      900

In [17]:
# Faqat Fevral oyidagi barcha shaharlar ma’lumotlarini olish
sales.xs('Fevral', level=1)

           Sotuv  Daromad
Shahar
Toshkent     150     1500
Samarqand    180     1800
Buxoro       210     2100

In [19]:
# Samarqand Mart ma'lumotlarini oling
sales.loc['Samarqand', 'Mart']

Sotuv       110
Daromad    1100
Name: (Samarqand, Mart), dtype: int64

In [21]:
# Buxoro shahrining barcha ma’lumotlarini oling
sales.loc['Buxoro']

        Sotuv  Daromad
Oy
Yanvar    250     2500
Fevral    210     2100