<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/pandas_data_preparation/multi_columns.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

**Do'kon savdolari ma'lumotlari**

In [2]:
columns = pd.MultiIndex.from_tuples(
    [
        ("Sotuv", "Laptop"),
        ("Sotuv", "Telefon"),
        ("Sotuv", "Tablet"),
        ("Daromad", "Laptop"),
        ("Daromad", "Telefon"),
        ("Daromad", "Tablet")
    ],
    names=["Ko‘rsatkich", "Mahsulot"]
)

data = [
    [120, 180, 90, 12000, 18000, 9000],
    [150, 210, 110, 15000, 21000, 11000],
    [170, 230, 130, 17000, 23000, 13000],
    [140, 190, 100, 14000, 19000, 10000]
]

index = ["Toshkent", "Samarqand", "Buxoro", "Fargona"]

sales = pd.DataFrame(data, index=index, columns=columns)
sales

Ko‘rsatkich  Sotuv                Daromad
Mahsulot    Laptop Telefon Tablet  Laptop Telefon Tablet
Toshkent       120     180     90   12000   18000   9000
Samarqand      150     210    110   15000   21000  11000
Buxoro         170     230    130   17000   23000  13000
Fargona        140     190    100   14000   19000  10000

In [3]:
# Faqat Sotuv ko‘rsatkichiga tegishli barcha mahsulotlarni oling
sales['Sotuv']

Mahsulot   Laptop  Telefon  Tablet
Toshkent      120      180      90
Samarqand     150      210     110
Buxoro        170      230     130
Fargona       140      190     100

In [4]:
# Faqat Laptop mahsulotining Sotuv va Daromad ma’lumotlarini oling
sales.xs('Laptop', level='Mahsulot', axis=1)

Ko‘rsatkich  Sotuv  Daromad
Toshkent       120    12000
Samarqand      150    15000
Buxoro         170    17000
Fargona        140    14000

In [5]:
# Faqat Telefon uchun Daromad qiymatlarini oling
sales[('Daromad', 'Telefon')]

Toshkent     18000
Samarqand    21000
Buxoro       23000
Fargona      19000
Name: (Daromad, Telefon), dtype: int64

In [6]:
# Toshkent va Buxoro hududlarining faqat Sotuv ma’lumotlarini oling
sales.loc[['Toshkent', 'Buxoro'], 'Sotuv']

Mahsulot  Laptop  Telefon  Tablet
Toshkent     120      180      90
Buxoro       170      230     130

**2-topshiriq**

In [7]:
columns = pd.MultiIndex.from_tuples(
    [
        (2023, "Sotuv"),
        (2023, "Daromad"),
        (2023, "Buyurtma"),
        (2024, "Sotuv"),
        (2024, "Daromad"),
        (2024, "Buyurtma")
    ],
    names=["Yil", "Ko‘rsatkich"]
)

data = [
    [120, 12000, 12, 150, 15000, 15],
    [100, 10000, 10, 140, 14000, 14],
    [90, 9000, 9, 130, 13000, 13],
    [110, 11000, 11, 160, 16000, 16]
]

df = pd.DataFrame(
    data,
    index=["Toshkent", "Samarqand", "Buxoro", "Fargona"],
    columns=columns
)
df

Yil          2023                   2024
Ko‘rsatkich Sotuv Daromad Buyurtma Sotuv Daromad Buyurtma
Toshkent      120   12000       12   150   15000       15
Samarqand     100   10000       10   140   14000       14
Buxoro         90    9000        9   130   13000       13
Fargona       110   11000       11   160   16000       16

In [9]:
# Faqat 2023-yil ma’lumotlarini oling
df[2023]

Ko‘rsatkich  Sotuv  Daromad  Buyurtma
Toshkent       120    12000        12
Samarqand      100    10000        10
Buxoro          90     9000         9
Fargona        110    11000        11

In [11]:
# Faqat Daromad ko‘rsatkichining 2023 va 2024-yillardagi qiymatlarini oling
df.xs('Daromad', level='Ko‘rsatkich', axis=1)

Yil         2023   2024
Toshkent   12000  15000
Samarqand  10000  14000
Buxoro      9000  13000
Fargona    11000  16000

In [12]:
# Faqat 2024-yil Sotuv ma’lumotlarini oling
df[2024]

Ko‘rsatkich  Sotuv  Daromad  Buyurtma
Toshkent       150    15000        15
Samarqand      140    14000        14
Buxoro         130    13000        13
Fargona        160    16000        16

In [14]:
# Toshkent uchun 2023 va 2024-yillardagi barcha ma’lumotlarni oling
df.loc['Toshkent']

Yil   Ko‘rsatkich
2023  Sotuv            120
      Daromad        12000
      Buyurtma          12
2024  Sotuv            150
      Daromad        15000
      Buyurtma          15
Name: Toshkent, dtype: int64

In [17]:
# Buxoro uchun faqat 2024-yil ma’lumotlarini oling
df.loc['Buxoro', 2024]

Ko‘rsatkich
Sotuv         130
Daromad     13000
Buyurtma       13
Name: Buxoro, dtype: int64