<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/pandas_data_preparation/multi_index2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

**Talabalarning fanlar bo‘yicha natijalari**

In [2]:
data = {
    "Ball": [86, 91, 78, 88, 95, 82, 76, 89],
    "Davomat": [92, 96, 85, 90, 98, 88, 80, 94]
}

index = pd.MultiIndex.from_tuples(
    [
        ("Ali", "Matematika"),
        ("Ali", "Python"),
        ("Vali", "Matematika"),
        ("Vali", "Python"),
        ("Hasan", "Matematika"),
        ("Hasan", "Python"),
        ("Sardor", "Matematika"),
        ("Sardor", "Python")
    ],
    names=["Talaba", "Fan"]
)

df = pd.DataFrame(data, index=index)
df

                   Ball  Davomat
Talaba Fan
Ali    Matematika    86       92
       Python        91       96
Vali   Matematika    78       85
       Python        88       90
Hasan  Matematika    95       98
       Python        82       88
Sardor Matematika    76       80
       Python        89       94

In [3]:
# indeksni tekshirish
df.index

MultiIndex([(   'Ali', 'Matematika'),
            (   'Ali',     'Python'),
            (  'Vali', 'Matematika'),
            (  'Vali',     'Python'),
            ( 'Hasan', 'Matematika'),
            ( 'Hasan',     'Python'),
            ('Sardor', 'Matematika'),
            ('Sardor',     'Python')],
           names=['Talaba', 'Fan'])

In [5]:
# Faqat Alining barcha fanlar bo‘yicha ma’lumotlarini olish
df.loc['Ali']

            Ball  Davomat
Fan
Matematika    86       92
Python        91       96

In [8]:
# Faqat Python fanidan barcha talabalar natijasini olish
df.xs('Python', level=1)

        Ball  Davomat
Talaba
Ali       91       96
Vali      88       90
Hasan     82       88
Sardor    89       94

In [11]:
# Alining faqat Python fanidagi Ball qiymatini olish
df.loc['Ali', 'Python']['Ball']

np.int64(91)

In [13]:
# Matematika fanidan barcha talabalarni va ularning Ball hamda Davomat qiymatlarini olish
df.xs('Matematika', level=1)

        Ball  Davomat
Talaba
Ali       86       92
Vali      78       85
Hasan     95       98
Sardor    76       80

**Do‘kon savdolari ma'lumotlari**

In [14]:
data = {
    "Sotuv": [120, 150, 90, 200, 180, 110, 250, 210],
    "Daromad": [1200, 1500, 900, 2000, 1800, 1100, 2500, 2100]
}

index = pd.MultiIndex.from_tuples(
    [
        ("Toshkent", "Yanvar"),
        ("Toshkent", "Fevral"),
        ("Toshkent", "Mart"),
        ("Samarqand", "Yanvar"),
        ("Samarqand", "Fevral"),
        ("Samarqand", "Mart"),
        ("Buxoro", "Yanvar"),
        ("Buxoro", "Fevral")
    ],
    names=["Shahar", "Oy"]
)

sales = pd.DataFrame(data, index=index)
sales

                  Sotuv  Daromad
Shahar    Oy
Toshkent  Yanvar    120     1200
          Fevral    150     1500
          Mart       90      900
Samarqand Yanvar    200     2000
          Fevral    180     1800
          Mart      110     1100
Buxoro    Yanvar    250     2500
          Fevral    210     2100

In [16]:
# Faqat Toshkent shahrining barcha oylaridagi ma’lumotlarni olish
sales.loc['Toshkent']

        Sotuv  Daromad
Oy
Yanvar    120     1200
Fevral    150     1500
Mart       90      900

In [17]:
# Faqat Fevral oyidagi barcha shaharlar ma’lumotlarini olish
sales.xs('Fevral', level=1)

           Sotuv  Daromad
Shahar
Toshkent     150     1500
Samarqand    180     1800
Buxoro       210     2100

In [19]:
# Samarqand Mart ma'lumotlarini oling
sales.loc['Samarqand', 'Mart']

Sotuv       110
Daromad    1100
Name: (Samarqand, Mart), dtype: int64

In [23]:
# Faqat Daromad ustunidan foydalanib, barcha shaharlar bo‘yicha ma'lumot olish
sales['Daromad']

Shahar     Oy
Toshkent   Yanvar    1200
           Fevral    1500
           Mart       900
Samarqand  Yanvar    2000
           Fevral    1800
           Mart      1100
Buxoro     Yanvar    2500
           Fevral    2100
Name: Daromad, dtype: int64

In [21]:
# Buxoro shahrining barcha ma’lumotlarini oling
sales.loc['Buxoro']

        Sotuv  Daromad
Oy
Yanvar    250     2500
Fevral    210     2100

**`stack`/`unstack` amaliyoti**

In [24]:
data2 = {
    "Q1": [120, 150, 100, 130],
    "Q2": [140, 170, 110, 145],
    "Q3": [160, 180, 125, 155],
    "Q4": [190, 210, 140, 170]
}

index2 = pd.MultiIndex.from_tuples(
    [
        ("Ali", "Laptop"),
        ("Ali", "Telefon"),
        ("Vali", "Laptop"),
        ("Vali", "Telefon")
    ],
    names=["Sotuvchi", "Mahsulot"]
)

df2 = pd.DataFrame(data2, index=index2)

df2

                    Q1   Q2   Q3   Q4
Sotuvchi Mahsulot
Ali      Laptop    120  140  160  190
         Telefon   150  170  180  210
Vali     Laptop    100  110  125  140
         Telefon   130  145  155  170

In [27]:
# Jadvalni shunday ko‘rinishga keltiringki, choraklar ham indeks darajasiga o'tsin
df2_stack = df2.stack()
df2_stack

Sotuvchi  Mahsulot
Ali       Laptop    Q1    120
                    Q2    140
                    Q3    160
                    Q4    190
          Telefon   Q1    150
                    Q2    170
                    Q3    180
                    Q4    210
Vali      Laptop    Q1    100
                    Q2    110
                    Q3    125
                    Q4    140
          Telefon   Q1    130
                    Q2    145
                    Q3    155
                    Q4    170
dtype: int64

In [28]:
# Hosil bo‘lgan jadvaldan foydalanib, uni yana dastlabki ko‘rinishga qaytaring
df2_stack.unstack()

                    Q1   Q2   Q3   Q4
Sotuvchi Mahsulot
Ali      Laptop    120  140  160  190
         Telefon   150  170  180  210
Vali     Laptop    100  110  125  140
         Telefon   130  145  155  170

In [29]:
# Faqat Laptop mahsulotlari bo‘yicha choraklar kesimidagi ma’lumotlarni ko‘rishga harakat qiling
df2.xs('Laptop', level=1)

           Q1   Q2   Q3   Q4
Sotuvchi
Ali       120  140  160  190
Vali      100  110  125  140

In [30]:
# Jadvalni shunday o‘zgartiringki, Mahsulot indeks emas, ustunlar darajasida joylashsin
df2.unstack(level=1)

             Q1             Q2             Q3             Q4
Mahsulot Laptop Telefon Laptop Telefon Laptop Telefon Laptop Telefon
Sotuvchi
Ali         120     150    140     170    160     180    190     210
Vali        100     130    110     145    125     155    140     170

**4-topshiriq**

In [31]:
data3 = {
    "Marketing": [12000, 15000, 18000, 14000, 17000, 21000, 13000, 16000],
    "IT": [25000, 28000, 30000, 27000, 31000, 35000, 24000, 29000],
    "HR": [8000, 9000, 9500, 8500, 10000, 11000, 7800, 9200]
}

index3 = pd.MultiIndex.from_tuples(
    [
        ("Toshkent", 2023),
        ("Toshkent", 2024),
        ("Samarqand", 2023),
        ("Samarqand", 2024),
        ("Buxoro", 2023),
        ("Buxoro", 2024),
        ("Fargona", 2023),
        ("Fargona", 2024)
    ],
    names=["Hudud", "Yil"]
)

expenses = pd.DataFrame(data3, index=index3)
expenses

                Marketing     IT     HR
Hudud     Yil
Toshkent  2023      12000  25000   8000
          2024      15000  28000   9000
Samarqand 2023      18000  30000   9500
          2024      14000  27000   8500
Buxoro    2023      17000  31000  10000
          2024      21000  35000  11000
Fargona   2023      13000  24000   7800
          2024      16000  29000   9200

In [33]:
# Faqat 2024-yil ma’lumotlarini ajratib oling
expenses.xs(2024, level=1)

           Marketing     IT     HR
Hudud
Toshkent       15000  28000   9000
Samarqand      14000  27000   8500
Buxoro         21000  35000  11000
Fargona        16000  29000   9200

In [35]:
# Faqat Toshkent va Buxoro hududlarini ajratib oling
expenses.loc[['Toshkent', 'Buxoro']]

               Marketing     IT     HR
Hudud    Yil
Toshkent 2023      12000  25000   8000
         2024      15000  28000   9000
Buxoro   2023      17000  31000  10000
         2024      21000  35000  11000

In [37]:
# Samarqand — 2023 yil ma’lumotlarini oling
expenses.loc['Samarqand', 2023]

Marketing    18000
IT           30000
HR            9500
Name: (Samarqand, 2023), dtype: int64

In [38]:
# Yil alohida indeks darajasi sifatida emas, ustunlar tomonida joylashsin
expenses.unstack(level=1)

          Marketing            IT            HR
Yil            2023   2024   2023   2024   2023   2024
Hudud
Buxoro        17000  21000  31000  35000  10000  11000
Fargona       13000  16000  24000  29000   7800   9200
Samarqand     18000  14000  30000  27000   9500   8500
Toshkent      12000  15000  25000  28000   8000   9000

**5-topshiriq**

- Quyidagi DataFrame kompaniyaning hudud → yil → mahsulot kesimidagi savdo ma’lumotlari

In [39]:
data4 = {
    "Sotuv": [
        120, 150, 200,
        180, 210, 250,
        100, 130, 170,
        160, 190, 230
    ],
    "Buyurtmalar": [
        12, 15, 20,
        18, 21, 25,
        10, 13, 17,
        16, 19, 23
    ]
}

index4 = pd.MultiIndex.from_tuples(
    [
        ("Toshkent", 2023, "Laptop"),
        ("Toshkent", 2023, "Telefon"),
        ("Toshkent", 2023, "Tablet"),

        ("Toshkent", 2024, "Laptop"),
        ("Toshkent", 2024, "Telefon"),
        ("Toshkent", 2024, "Tablet"),

        ("Samarqand", 2023, "Laptop"),
        ("Samarqand", 2023, "Telefon"),
        ("Samarqand", 2023, "Tablet"),

        ("Samarqand", 2024, "Laptop"),
        ("Samarqand", 2024, "Telefon"),
        ("Samarqand", 2024, "Tablet")
    ],
    names=["Hudud", "Yil", "Mahsulot"]
)

sales = pd.DataFrame(data4, index=index4)
sales

                         Sotuv  Buyurtmalar
Hudud     Yil  Mahsulot
Toshkent  2023 Laptop      120           12
               Telefon     150           15
               Tablet      200           20
          2024 Laptop      180           18
               Telefon     210           21
               Tablet      250           25
Samarqand 2023 Laptop      100           10
               Telefon     130           13
               Tablet      170           17
          2024 Laptop      160           16
               Telefon     190           19
               Tablet      230           23

In [41]:
# Faqat Toshkent → 2024 → Telefon ma’lumotlarini oling
sales.loc[('Toshkent', 2024, 'Telefon')]

Sotuv          210
Buyurtmalar     21
Name: (Toshkent, 2024, Telefon), dtype: int64

In [42]:
# Faqat Samarqand hududidagi barcha ma’lumotlarni oling
sales.loc['Samarqand']

               Sotuv  Buyurtmalar
Yil  Mahsulot
2023 Laptop      100           10
     Telefon     130           13
     Tablet      170           17
2024 Laptop      160           16
     Telefon     190           19
     Tablet      230           23

In [43]:
# Faqat 2023-yil ma’lumotlarini ajrating
sales.xs(2023, level=1)

                    Sotuv  Buyurtmalar
Hudud     Mahsulot
Toshkent  Laptop      120           12
          Telefon     150           15
          Tablet      200           20
Samarqand Laptop      100           10
          Telefon     130           13
          Tablet      170           17

In [45]:
# Mahsulot indeksdan ustunlar tomoniga o'tadigan ko‘rinish hosil qiling
sales_unstack = sales.unstack(level=2)
sales_unstack

                Sotuv                Buyurtmalar
Mahsulot       Laptop Tablet Telefon      Laptop Tablet Telefon
Hudud     Yil
Samarqand 2023    100    170     130          10     17      13
          2024    160    230     190          16     23      19
Toshkent  2023    120    200     150          12     20      15
          2024    180    250     210          18     25      21

In [46]:
# Endi Yil ham alohida ustunlar darajasida ko‘rinadigan qilib jadvalni o‘zgartiring
sales_unstack.unstack(level=1)

           Sotuv                               Buyurtmalar                   \
Mahsulot  Laptop      Tablet      Telefon           Laptop      Tablet
Yil         2023 2024   2023 2024    2023 2024        2023 2024   2023 2024
Hudud
Samarqand    100  160    170  230     130  190          10   16     17   23
Toshkent     120  180    200  250     150  210          12   18     20   25


Mahsulot  Telefon
Yil          2023 2024
Hudud
Samarqand      13   19
Toshkent       15   21

In [52]:
sales_unstack.stack(future_stack=True)

                         Sotuv  Buyurtmalar
Hudud     Yil  Mahsulot
Samarqand 2023 Laptop      100           10
               Tablet      170           17
               Telefon     130           13
          2024 Laptop      160           16
               Tablet      230           23
               Telefon     190           19
Toshkent  2023 Laptop      120           12
               Tablet      200           20
               Telefon     150           15
          2024 Laptop      180           18
               Tablet      250           25
               Telefon     210           21