<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/pandas_data_preparation/pivot3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({
    "Talaba": ["Ali", "Ali", "Vali", "Vali", "Hasan", "Hasan"],
    "Fan": ["Matematika", "Ingliz tili",
            "Matematika", "Ingliz tili",
            "Matematika", "Ingliz tili"],
    "Ball": [90, 85, 78, 92, 88, 80]
})
df

  Talaba          Fan  Ball
0    Ali   Matematika    90
1    Ali  Ingliz tili    85
2   Vali   Matematika    78
3   Vali  Ingliz tili    92
4  Hasan   Matematika    88
5  Hasan  Ingliz tili    80

In [3]:
# har bir talaba alohida qator bo‘lsin
# fanlar alohida ustunlarga aylansin
# kataklarda talabaning shu fandagi bali tursin
df.pivot(index='Talaba', columns='Fan', values='Ball')

Fan     Ingliz tili  Matematika
Talaba
Ali              85          90
Hasan            80          88
Vali             92          78

In [4]:
sales = pd.DataFrame({
    "Shahar": ["Toshkent", "Toshkent", "Samarqand",
               "Samarqand", "Buxoro", "Buxoro"],
    "Mahsulot": ["Laptop", "Telefon",
                 "Laptop", "Telefon",
                 "Laptop", "Telefon"],
    "Sotuv": [10, 20, 15, 25, 8, 18]
})
sales

      Shahar Mahsulot  Sotuv
0   Toshkent   Laptop     10
1   Toshkent  Telefon     20
2  Samarqand   Laptop     15
3  Samarqand  Telefon     25
4     Buxoro   Laptop      8
5     Buxoro  Telefon     18

In [5]:
# shaharlar qatorlarda bo‘lsin;
# mahsulotlar ustunlarda bo‘lsin;
# kataklarda sotuv miqdori ko‘rinsin
sales.pivot(index='Shahar', columns='Mahsulot', values='Sotuv')

Mahsulot   Laptop  Telefon
Shahar
Buxoro          8       18
Samarqand      15       25
Toshkent       10       20

In [6]:
revenue = pd.DataFrame({
    "Do‘kon": ["A", "A", "A",
               "B", "B", "B",
               "C", "C", "C"],
    "Oy": ["Yanvar", "Fevral", "Mart",
           "Yanvar", "Fevral", "Mart",
           "Yanvar", "Fevral", "Mart"],
    "Daromad": [12000, 15000, 18000,
                10000, 14000, 16000,
                8000, 11000, 13000]
})
revenue

  Do‘kon      Oy  Daromad
0      A  Yanvar    12000
1      A  Fevral    15000
2      A    Mart    18000
3      B  Yanvar    10000
4      B  Fevral    14000
5      B    Mart    16000
6      C  Yanvar     8000
7      C  Fevral    11000
8      C    Mart    13000

In [7]:
# har bir do‘kon alohida qator bo‘lsin;
# oylar alohida ustunlarga aylansin;
# kataklarda tegishli oyning daromadi tursin
revenue.pivot(index="Do‘kon", columns='Oy', values='Daromad')

Oy      Fevral   Mart  Yanvar
Do‘kon
A        15000  18000   12000
B        14000  16000   10000
C        11000  13000    8000

**to'rtinchi topshiriq**

In [8]:
df = pd.DataFrame({
    "Talaba": ["Ali", "Ali", "Vali", "Vali", "Hasan", "Hasan"],
    "Fan": ["Matematika", "Python", "Matematika", "Python", "Matematika", "Python"],
    "Ball": [90, 85, 78, 92, 88, 95]
})
df

  Talaba         Fan  Ball
0    Ali  Matematika    90
1    Ali      Python    85
2   Vali  Matematika    78
3   Vali      Python    92
4  Hasan  Matematika    88
5  Hasan      Python    95

In [9]:
# har bir talaba alohida qatorda bo‘lsin
# fanlar alohida ustunlarga aylansin
# kataklarda talabalar olgan ballari tursin
df.pivot(index='Talaba', columns='Fan', values='Ball')

Fan     Matematika  Python
Talaba
Ali             90      85
Hasan           88      95
Vali            78      92

**beshinchi topshiriq**

In [10]:
sales = pd.DataFrame({
    "Shahar": [
        "Toshkent", "Toshkent",
        "Toshkent", "Toshkent",
        "Buxoro", "Buxoro",
        "Buxoro", "Buxoro"
    ],
    "Mahsulot": [
        "Laptop", "Laptop",
        "Telefon", "Telefon",
        "Laptop", "Laptop",
        "Telefon", "Telefon"
    ],
    "Sotuv": [5, 7, 10, 12, 3, 5, 8, 10]
})
sales

     Shahar Mahsulot  Sotuv
0  Toshkent   Laptop      5
1  Toshkent   Laptop      7
2  Toshkent  Telefon     10
3  Toshkent  Telefon     12
4    Buxoro   Laptop      3
5    Buxoro   Laptop      5
6    Buxoro  Telefon      8
7    Buxoro  Telefon     10

In [12]:
# shaharlar qatorlarda bo‘lsin
# mahsulotlar ustunlarga aylansin
# har bir shaharda har bir mahsulot bo‘yicha o‘rtacha sotuv ko‘rinsin

sales.pivot_table(index='Shahar', columns='Mahsulot', values='Sotuv', aggfunc='mean')

Mahsulot  Laptop  Telefon
Shahar
Buxoro       4.0      9.0
Toshkent     6.0     11.0