<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/pandas/practice/practice_all_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    'Name': ['John', 'Alice', 'Bob'],
    'Age': [25, 30, 35],
    'City': ['New York', 'London', 'Paris']
}

# Create a DataFrame from this dictionary and display it
df = pd.DataFrame(data)
df

    Name  Age      City
0   John   25  New York
1  Alice   30    London
2    Bob   35     Paris

In [3]:
students = [
    ['Ahmad', 85, 'Math'],
    ['Zarina', 92, 'Physics'],
    ['Bekzod', 78, 'Chemistry']
]

# Create a DataFrame from this list. Columns: 'Student', 'Score', 'Subject
df2 = pd.DataFrame(students, columns=['Student', 'Score', 'Subject'])
df2

  Student  Score    Subject
0   Ahmad     85       Math
1  Zarina     92    Physics
2  Bekzod     78  Chemistry

In [4]:
df3 = pd.DataFrame({
    'ProductID': [101, 102, 103, 104, 105],
    'ProductName': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Headphones'],
    'Price': [1200, 25, 75, 300, 150],
    'Stock': [50, 200, 150, 80, 120],
    'Category': ['Electronics', 'Accessories', 'Accessories', 'Electronics', 'Accessories']
})
df3

   ProductID ProductName  Price  Stock     Category
0        101      Laptop   1200     50  Electronics
1        102       Mouse     25    200  Accessories
2        103    Keyboard     75    150  Accessories
3        104     Monitor    300     80  Electronics
4        105  Headphones    150    120  Accessories

In [5]:
# Select only the columns 'ProductName', 'Price' and 'Stock'
df3[['ProductName', 'Price', 'Stock']]

  ProductName  Price  Stock
0      Laptop   1200     50
1       Mouse     25    200
2    Keyboard     75    150
3     Monitor    300     80
4  Headphones    150    120

In [6]:
# Select columns 1, 3, and 4 by number
df3.iloc[:, [0, 2, 3]]

   ProductID  Price  Stock
0        101   1200     50
1        102     25    200
2        103     75    150
3        104    300     80
4        105    150    120

In [7]:
df4 = pd.DataFrame({
    'A': [10, 20, 30, 40, 50],
    'B': [15, 25, 35, 45, 55],
    'C': [12, 22, 32, 42, 52],
    'D': [18, 28, 38, 48, 58]
})
df4

    A   B   C   D
0  10  15  12  18
1  20  25  22  28
2  30  35  32  38
3  40  45  42  48
4  50  55  52  58

In [8]:
# Select all even-numbered columns (0, 2)
df4.iloc[:, [0, 2]]

    A   C
0  10  12
1  20  22
2  30  32
3  40  42
4  50  52

In [9]:
# Select columns 'B' through 'D'
df4.loc[:, 'B':'D']

    B   C   D
0  15  12  18
1  25  22  28
2  35  32  38
3  45  42  48
4  55  52  58

In [10]:
sales_data = {
    'region': {
        'north': {'q1': 15000, 'q2': 18000},
        'south': {'q1': 12000, 'q2': 14000}
    },
    'employees': {
        'north': {'q1': 25, 'q2': 28},
        'south': {'q1': 20, 'q2': 22}
    }
}

# bajarolmadim

In [11]:
# Task 6

In [12]:
df6 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Salary': [5000, 6000, 5500, 7000, 6500]
})
df6

      Name  Salary
0    Alice    5000
1      Bob    6000
2  Charlie    5500
3    David    7000
4      Eve    6500

In [13]:
# Set the 'Name' column as index
df6.set_index('Name', inplace=True)

In [14]:
df6

         Salary
Name
Alice      5000
Bob        6000
Charlie    5500
David      7000
Eve        6500

In [15]:
# Rename the index to 'Employee'
df6.rename_axis('Employee', inplace=True)

In [16]:
df6

          Salary
Employee
Alice       5000
Bob         6000
Charlie     5500
David       7000
Eve         6500

In [17]:
df7 = pd.DataFrame({
    'Product': ['A', 'B', 'C', 'D'],
    'Price': [100, 200, 150, 300]
}, index=[10, 20, 30, 40])
df7

   Product  Price
10       A    100
20       B    200
30       C    150
40       D    300

In [18]:
# Change the indices to ['P1', 'P2', 'P3', 'P4']
df7.index = ['P1', 'P2', 'P3', 'P4']

In [19]:
df7

   Product  Price
P1       A    100
P2       B    200
P3       C    150
P4       D    300

In [20]:
# Renumber the index starting from 0.
df7.reset_index(drop=True)

  Product  Price
0       A    100
1       B    200
2       C    150
3       D    300

In [21]:
df8 = pd.DataFrame({
    'Name': ['Ali', 'Vali', 'Sardor', 'Jasur', 'Kamol'],
    'Age': [25, 30, 35, 28, 32]
}, index=[101, 102, 103, 104, 105])
df8

       Name  Age
101     Ali   25
102    Vali   30
103  Sardor   35
104   Jasur   28
105   Kamol   32

In [22]:
# Output the row with index 103
df8.loc[103]

Name    Sardor
Age         35
Name: 103, dtype: object

In [23]:
# Extract rows from index 102 to 104
df8.loc[102:104]

       Name  Age
102    Vali   30
103  Sardor   35
104   Jasur   28

In [24]:
df9 = pd.DataFrame({
    'Product': ['Laptop', 'Phone', 'Tablet', 'Watch'],
    'Price': [1000, 500, 300, 200]
}, index=['A', 'B', 'C', 'D'])
df9

  Product  Price
A  Laptop   1000
B   Phone    500
C  Tablet    300
D   Watch    200

In [25]:
# Output the array with index B'
df9.loc['B']

Product    Phone
Price        500
Name: B, dtype: object

In [26]:
# Output the rows from 'A' to 'C' (C is included)
df9.loc['A':'C']

  Product  Price
A  Laptop   1000
B   Phone    500
C  Tablet    300

In [27]:
# Extract the 2nd row by position
df9.iloc[1]

Product    Phone
Price        500
Name: B, dtype: object

In [28]:
df10 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, 30, 35, 28, 32],
    'Salary': [5000, 6000, 5500, 7000, 6500],
    'Department': ['IT', 'HR', 'IT', 'Sales', 'HR']
})
df10

      Name  Age  Salary Department
0    Alice   25    5000         IT
1      Bob   30    6000         HR
2  Charlie   35    5500         IT
3    David   28    7000      Sales
4      Eve   32    6500         HR

In [29]:
# Find employees over 30 years old
df10[df10['Age'] > 30]

      Name  Age  Salary Department
2  Charlie   35    5500         IT
4      Eve   32    6500         HR

In [30]:
# Find those who work in IT and have a salary above 5500
df10[(df10['Department'] == 'IT') & (df10['Salary'] > 5500)]

Empty DataFrame
Columns: [Name, Age, Salary, Department]
Index: []

In [31]:
df11 = pd.DataFrame({
    'Student': ['Ahmad', 'Zarina', 'Bekzod', 'Dilshod'],
    'Math': [85, 92, 78, 88],
    'Physics': [88, 85, 90, 87],
    'Chemistry': [90, 88, 85, 89]
})
df11

   Student  Math  Physics  Chemistry
0    Ahmad    85       88         90
1   Zarina    92       85         88
2   Bekzod    78       90         85
3  Dilshod    88       87         89

In [32]:
# Find students with a Math score above 80 AND a Physics score below 87
df11[(df11['Math'] > 80) & (df11['Physics'] < 87)]

  Student  Math  Physics  Chemistry
1  Zarina    92       85         88

In [33]:
# Find students who scored above 90 in Mathematics or Physics
df11[(df11['Math'] > 90) | (df11['Physics'] > 90)]

  Student  Math  Physics  Chemistry
1  Zarina    92       85         88

In [34]:
df12 = pd.DataFrame({
    'Name': ['Laptop', 'Phone', 'Tablet', 'Watch'],
    'Price': [1200, 800, 450, 250]
})
df12

     Name  Price
0  Laptop   1200
1   Phone    800
2  Tablet    450
3   Watch    250

In [35]:
# Sort by Price in descending order
df12.sort_values(by='Price', ascending=False)

     Name  Price
0  Laptop   1200
1   Phone    800
2  Tablet    450
3   Watch    250

In [36]:
# Sort alphabetically by Name
df12.sort_values(by='Name')

     Name  Price
0  Laptop   1200
1   Phone    800
2  Tablet    450
3   Watch    250

In [37]:
df13 = pd.DataFrame({
    'Student': ['Ali', 'Vali', 'Sardor', 'Jasur', 'Kamol'],
    'Math': [85, 90, 85, 92, 85],
    'Physics': [88, 85, 90, 87, 91],
    'Age': [20, 19, 21, 20, 19]
})
df13

  Student  Math  Physics  Age
0     Ali    85       88   20
1    Vali    90       85   19
2  Sardor    85       90   21
3   Jasur    92       87   20
4   Kamol    85       91   19

In [38]:
# Sort first by Math in descending order, then by Physics in ascending order
df13.sort_values(by=['Math', 'Physics'], ascending=[False, True])

  Student  Math  Physics  Age
3   Jasur    92       87   20
1    Vali    90       85   19
0     Ali    85       88   20
2  Sardor    85       90   21
4   Kamol    85       91   19

In [39]:
# Sort by Age in ascending order, starting the index at 0 again
df13.sort_values(by='Age', ascending=True, ignore_index=True)

  Student  Math  Physics  Age
0    Vali    90       85   19
1   Kamol    85       91   19
2   Jasur    92       87   20
3     Ali    85       88   20
4  Sardor    85       90   21

In [40]:
df14 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50]
})
df14

   A   B
0  1  10
1  2  20
2  3  30
3  4  40
4  5  50

In [41]:
# Multiply the values ​​in column A' by 3
df14['A']*3

0     3
1     6
2     9
3    12
4    15
Name: A, dtype: int64

In [42]:
# Create a new column 'C': A + B
df14['C'] = df14['A'] + df14['B']
df14

   A   B   C
0  1  10  11
1  2  20  22
2  3  30  33
3  4  40  44
4  5  50  55

In [43]:
# Subtract 5 from each value in column B'
df14['B'] - 5

0     5
1    15
2    25
3    35
4    45
Name: B, dtype: int64

In [44]:
df15 = pd.DataFrame({
    'Name': ['Ali', 'Vali', 'Sardor'],
    'Age': [25, 30, 35],
    'Salary': [5000, 6000, 5500]
})
df15

     Name  Age  Salary
0     Ali   25    5000
1    Vali   30    6000
2  Sardor   35    5500

In [45]:
# Create a new 'Category' column based on the Age column: 'Young' if under 30, 'Senior' otherwise
df15['Category'] = np.where(df15['Age']<30, 'young', 'senior')
df15

     Name  Age  Salary Category
0     Ali   25    5000    young
1    Vali   30    6000   senior
2  Sardor   35    5500   senior

In [46]:
df16 = pd.DataFrame({
    'Department': ['IT', 'HR', 'IT', 'Sales', 'HR', 'IT'],
    'Employee': ['Ali', 'Vali', 'Sardor', 'Jasur', 'Kamol', 'Nodir'],
    'Salary': [5000, 4000, 5500, 4500, 4200, 6000]
})
df16

  Department Employee  Salary
0         IT      Ali    5000
1         HR     Vali    4000
2         IT   Sardor    5500
3      Sales    Jasur    4500
4         HR    Kamol    4200
5         IT    Nodir    6000

In [47]:
# Group by department and calculate the average salary in each department
df16.groupby('Department')['Salary'].mean()

Department
HR       4100.0
IT       5500.0
Sales    4500.0
Name: Salary, dtype: float64

In [48]:
# Group by Department and find the number of employees in each department
df16.groupby('Department')['Employee'].count()

Department
HR       2
IT       3
Sales    1
Name: Employee, dtype: int64

In [49]:
# Group by department and find maximum and minimum salaries
df16.groupby('Department')['Salary'].agg(['max', 'min'])

             max   min
Department
HR          4200  4000
IT          6000  5000
Sales       4500  4500

In [50]:
df17 = pd.DataFrame({
    'Product': ['Laptop', 'Phone', 'Laptop', 'Tablet', 'Phone', 'Laptop'],
    'Store': ['A', 'A', 'B', 'A', 'B', 'A'],
    'Sales': [5, 8, 3, 6, 9, 4],
    'Revenue': [5000, 4000, 3000, 1800, 4500, 4000]
})
df17

  Product Store  Sales  Revenue
0  Laptop     A      5     5000
1   Phone     A      8     4000
2  Laptop     B      3     3000
3  Tablet     A      6     1800
4   Phone     B      9     4500
5  Laptop     A      4     4000

In [51]:
# Group by Product and Store and calculate total sales (Sales)
df17.groupby(['Product', 'Store'])['Sales'].sum()

Product  Store
Laptop   A        9
         B        3
Phone    A        8
         B        9
Tablet   A        6
Name: Sales, dtype: int64

In [52]:
# Group by Product and find the average revenue (Revenue)
df17.groupby('Product')['Revenue'].mean()

Product
Laptop    4000.0
Phone     4250.0
Tablet    1800.0
Name: Revenue, dtype: float64

In [53]:
# Group by Store and calculate total revenue, average sales, and maximum revenue at the same time
df17.groupby('Store').agg({
    'Revenue':['sum', 'max'],
    'Sales':'mean'
})

      Revenue       Sales
          sum   max  mean
Store
A       14800  5000  5.75
B        7500  4500  6.00

In [54]:
df18 = pd.DataFrame({
    'Name': ['Ali', 'Vali', 'Sardor'],
    'Age': [25, 30, 35]
})
df18

     Name  Age
0     Ali   25
1    Vali   30
2  Sardor   35

In [55]:
# Change the value of 'Age' in line 2 to 32
df18.at[1, 'Age'] = 32

In [56]:
df18

     Name  Age
0     Ali   25
1    Vali   32
2  Sardor   35

In [57]:
# Update all values ​​in row 1: Name='Valijon', Age=31
df18.iloc[0] = ['Valijon', 31]
df18

      Name  Age
0  Valijon   31
1     Vali   32
2   Sardor   35

In [58]:
df19 = pd.DataFrame({
    'Product': ['Laptop', 'Phone', 'Tablet'],
    'Price': [1000, 500, 300]
}, index=['A', 'B', 'C'])
df19

  Product  Price
A  Laptop   1000
B   Phone    500
C  Tablet    300

In [59]:
# Change 'Price' in the row with index 'B' to 550
df19.at['B', 'Price'] = 550

In [60]:
df19

  Product  Price
A  Laptop   1000
B   Phone    550
C  Tablet    300

In [61]:
# Replace all values ​​of the array with index C': Product='Tablet Pro', Price=350
df19.iloc[-1] = ['Tablet Pro', 350]
df19

      Product  Price
A      Laptop   1000
B       Phone    550
C  Tablet Pro    350

In [62]:
df20 = pd.DataFrame({
    'A': [10, 20, 30],
    'B': [15, 25, 35]
})
df20

    A   B
0  10  15
1  20  25
2  30  35

In [63]:
# Calculate the sum of the values ​​in each row
np.sum(df20, axis=1)

0    25
1    45
2    65
dtype: int64

In [64]:
# Calculate the product of the values ​​in each column
np.prod(df20, axis=0)

A     6000
B    13125
dtype: int64

In [65]:
np.random.seed(42)

students = pd.DataFrame({
    "student_id": range(1, 16),
    "name": ["Ali","Vali","Hasan","Husan","Olim","Zafar","Bekzod","Jamshid","Sardor","Akmal",
             "Dilshod","Javohir","Aziz","Bobur","Sanjar"],
    "math": np.random.randint(50, 100, 15),
    "english": np.random.randint(50, 100, 15),
    "physics": np.random.randint(50, 100, 15),
    "attendance": np.random.randint(60, 100, 15)
})
students

    student_id     name  math  english  physics  attendance
0            1      Ali    88       52       76          84
1            2     Vali    78       71       91          73
2            3    Hasan    64       51       77          68
3            4    Husan    92       73       65          85
4            5     Olim    57       93       64          61
5            6    Zafar    70       79       96          79
6            7   Bekzod    88       87       93          87
7            8  Jamshid    68       51       52          66
8            9   Sardor    72       70       86          67
9           10    Akmal    60       82       56          94
10          11  Dilshod    60       61       70          73
11          12  Javohir    73       71       58          76
12          13     Aziz    85       93       88          95
13          14    Bobur    89       74       67          99
14          15   Sanjar    73       98       53          63

In [79]:
# Calculate the average grade for each student in three subjects
students['mean_score'] = np.mean(students[['math', 'english', 'physics']], axis=1)
students

    student_id     name  math  english  physics  attendance  mean_score
0            1      Ali    88       52       76          84   72.000000
1            2     Vali    78       71       91          73   80.000000
2            3    Hasan    64       51       77          68   64.000000
3            4    Husan    92       73       65          85   76.666667
4            5     Olim    57       93       64          61   71.333333
5            6    Zafar    70       79       96          79   81.666667
6            7   Bekzod    88       87       93          87   89.333333
7            8  Jamshid    68       51       52          66   57.000000
8            9   Sardor    72       70       86          67   76.000000
9           10    Akmal    60       82       56          94   66.000000
10          11  Dilshod    60       61       70          73   63.666667
11          12  Javohir    73       71       58          76   67.333333
12          13     Aziz    85       93       88          95   88.666667
13          14    Bobur    89       74       67          99   76.666667
14          15   Sanjar    73       98       53          63   74.666667

In [81]:
# Identify the 5 students with the highest average
top_students = students[['name', 'mean_score']]
top_students['mean_score'].nlargest(5)

6     89.333333
12    88.666667
5     81.666667
1     80.000000
3     76.666667
Name: mean_score, dtype: float64

In [83]:
# Rank students based on their Math scores, and have students with the same score rank in the same order
students['math_rank'] = students['math'].rank(method='dense')
students

,student_id,name,math,english,physics,attendance,mean_score,math_rank
0,1,Ali,88,52,76,84,72.000000,10.0
1,2,Vali,78,71,91,73,80.000000,8.0
2,3,Hasan,64,51,77,68,64.000000,3.0
3,4,Husan,92,73,65,85,76.666667,12.0
4,5,Olim,57,93,64,61,71.333333,1.0
5,6,Zafar,70,79,96,79,81.666667,5.0
6,7,Bekzod,88,87,93,87,89.333333,10.0
7,8,Jamshid,68,51,52,66,57.000000,4.0
8,9,Sardor,72,70,86,67,76.000000,6.0
9,10,Akmal,60,82,56,94,66.000000,2.0
10,11,Dilshod,60,61,70,73,63.666667,2.0
11,12,Javohir,73,71,58,76,67.333333,7.0
12,13,Aziz,85,93,88,95,88.666667,9.0
13,14,Bobur,89,74,67,99,76.666667,11.0
14,15,Sanjar,73,98,53,63,74.666667,7.0

In [84]:
np.random.seed(42)
sales = pd.DataFrame({
    "order_id": range(1001, 1021),
    "region": np.random.choice(["Toshkent","Samarqand","Buxoro","Fargona"], 20),
    "product": np.random.choice(["Phone","Laptop","Tablet"], 20),
    "price": np.random.randint(300, 2000, 20),
    "quantity": np.random.randint(1, 5, 20),
    "discount": np.random.choice([0,5,10,15], 20)
})
sales

    order_id     region product  price  quantity  discount
0       1001     Buxoro  Laptop    986         2         5
1       1002    Fargona   Phone   1257         1         5
2       1003   Toshkent  Laptop    862         2         5
3       1004     Buxoro  Laptop   1890         4         5
4       1005     Buxoro  Laptop   1567         4        15
5       1006    Fargona  Laptop   1131         3         5
6       1007   Toshkent   Phone   1828         4         0
7       1008   Toshkent   Phone   1454         3        10
8       1009     Buxoro  Laptop   1808         4         5
9       1010  Samarqand  Laptop    946         1         5
10      1011     Buxoro   Phone    320         4        15
11      1012     Buxoro   Phone   1140         3         5
12      1013     Buxoro   Phone    466         3         5
13      1014     Buxoro  Tablet   1597         2         5
14      1015    Fargona  Tablet    687         1        15
15      1016   Toshkent  Tablet    900         4         5
16      1017    Fargona  Laptop    615         2        10
17      1018    Fargona  Tablet    313         4        15
18      1019    Fargona  Laptop    541         4        10
19      1020     Buxoro  Laptop   1076         2        15

In [94]:
# Calculate the total revenue (price quantity) in the Sales table
sales['revenue'] = sales['price'] * sales['quantity']

In [95]:
# Determine which order has the highest revenue
sales.loc[sales['revenue'].idxmax(), 'order_id']

np.int64(1004)

In [97]:
np.random.seed(42)
employees = pd.DataFrame({
    "emp_id": range(1, 13),
    "department": np.random.choice(["IT","HR","Finance","Marketing"], 12),
    "salary": np.random.randint(2000, 8000, 12),
    "experience_year": np.random.randint(1, 15, 12),
    "age": np.random.randint(22, 50, 12)
})
employees

    emp_id department  salary  experience_year  age
0        1    Finance    6426               12   31
1        2  Marketing    7578                5   49
2        3         IT    5444                1   49
3        4    Finance    5171               12   37
4        5    Finance    4919               10   36
5        6  Marketing    2130                6   36
6        7         IT    3685               13   40
7        8         IT    2769               12   33
8        9    Finance    4391                9   44
9       10         HR    7611                1   41
10      11    Finance    4433               11   46
11      12    Finance    7311               11   24

In [99]:
# Determine the average, highest, and lowest salaries for each department in the Employees table
employees.groupby('department')['salary'].agg(['mean', 'max', 'min'])

                   mean   max   min
department
Finance     5441.833333  7311  4391
HR          7611.000000  7611  7611
IT          3966.000000  5444  2769
Marketing   4854.000000  7578  2130

In [100]:
students

,student_id,name,math,english,physics,attendance,mean_score,math_rank
0,1,Ali,88,52,76,84,72.000000,10.0
1,2,Vali,78,71,91,73,80.000000,8.0
2,3,Hasan,64,51,77,68,64.000000,3.0
3,4,Husan,92,73,65,85,76.666667,12.0
4,5,Olim,57,93,64,61,71.333333,1.0
5,6,Zafar,70,79,96,79,81.666667,5.0
6,7,Bekzod,88,87,93,87,89.333333,10.0
7,8,Jamshid,68,51,52,66,57.000000,4.0
8,9,Sardor,72,70,86,67,76.000000,6.0
9,10,Akmal,60,82,56,94,66.000000,2.0
10,11,Dilshod,60,61,70,73,63.666667,2.0
11,12,Javohir,73,71,58,76,67.333333,7.0
12,13,Aziz,85,93,88,95,88.666667,9.0
13,14,Bobur,89,74,67,99,76.666667,11.0
14,15,Sanjar,73,98,53,63,74.666667,7.0

In [102]:
# Determine the degree of correlation between the math, english, and physics columns in the Students table
students[['math', 'english', 'physics']].corr()

             math   english   physics
math     1.000000  0.054455  0.307296
english  0.054455  1.000000  0.056224
physics  0.307296  0.056224  1.000000

- *Calculate the relationship between salary and experience_year in the Employees table and determine whether it is positive or negative*

In [104]:
employees[['salary', 'experience_year']].corr()

                   salary  experience_year
salary           1.000000        -0.338742
experience_year -0.338742         1.000000