<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/pandas/projects/company_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**On this page, I will prepare a business analysis for an e-commerce company for the year 2024. The data is obtained from artificial intelligence. I need to analyze the data and present a report to the director.**

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Orders ma'lumotlari yaratish
np.random.seed(42)

order_ids = range(1001, 1501)
customer_ids = np.random.choice(['C001', 'C002', 'C003', 'C004', 'C005', 'C006', 'C007', 'C008', 'C009', 'C010'], 500)
product_ids = np.random.choice(['P001', 'P002', 'P003', 'P004', 'P005', 'P006', 'P007', 'P008'], 500)
order_dates = pd.date_range('2024-01-01', '2024-12-31', periods=500)
quantities = np.random.randint(1, 10, 500)
prices = np.random.choice([50, 100, 150, 200, 250, 300, 500, 1000], 500)
regions = np.random.choice(['North', 'South', 'East', 'West'], 500)
statuses = np.random.choice(['Completed', 'Pending', 'Cancelled', 'Returned'], 500, p=[0.7, 0.15, 0.1, 0.05])

orders = pd.DataFrame({
    'OrderID': order_ids,
    'CustomerID': customer_ids,
    'ProductID': product_ids,
    'OrderDate': order_dates,
    'Quantity': quantities,
    'Price': prices,
    'Region': regions,
    'Status': statuses
})

# Ba'zi qiymatlarni NaN qilish
orders.loc[np.random.choice(orders.index, 20), 'Quantity'] = np.nan
orders.loc[np.random.choice(orders.index, 15), 'Region'] = np.nan

# Takroriy qatorlar qo'shish
duplicate_rows = orders.sample(10)
orders = pd.concat([orders, duplicate_rows], ignore_index=True)

# faylga saqlash
orders.to_csv('orders.csv', index=False)
print("orders.csv: yaratildi.")

orders.csv: yaratildi.

In [3]:
# customers csv
customers = pd.DataFrame({
    'CustomerID': ['C001', 'C002', 'C003', 'C004', 'C005', 'C006', 'C007', 'C008', 'C009', 'C010'],
    'CustomerName': ['Ali Khan', 'Vali Karimov', 'Sardor Toshmatov', 'Jasur Aliyev', 'Kamol Rashidov',
                     'Nodir Sultonov', 'Aziz Mahmudov', 'Bobur Yusupov', 'Davron Ismoilov', 'Eldor Nabiyev'],
    'Email': ['ali@example.com', 'vali@test.com', 'sardor@mail.uz', 'jasur@inbox.com', 'kamol@company.uz',
              'nodir@business.com', 'aziz@enterprise.net', 'bobur@client.org', 'davron@partner.io', 'eldor@shop.com'],
    'City': ['Tashkent', 'Samarkand', 'Bukhara', 'Tashkent', 'Fergana', 'Namangan', 'Tashkent', 'Andijan', 'Samarkand', 'Bukhara'],
    'JoinDate': pd.to_datetime(['2020-03-15', '2019-07-22', '2021-11-08', '2020-05-10', '2022-01-20',
                                '2021-06-15', '2020-09-30', '2022-04-12', '2021-08-25', '2022-11-05']),
    'Age': [28, 35, 42, 31, 26, 38, 45, 29, 33, 40],
    'Membership': ['Gold', 'Silver', 'Gold', 'Bronze', 'Silver', 'Gold', 'Platinum', 'Bronze', 'Silver', 'Gold']
})

customers.to_csv('customers.csv', index=False)
print("customers.csv yaratildi!")

customers.csv yaratildi!

In [4]:
# products csv
products = pd.DataFrame({
    'ProductID': ['P001', 'P002', 'P003', 'P004', 'P005', 'P006', 'P007', 'P008'],
    'ProductName': ['Laptop Pro', 'Phone X', 'Tablet Max', 'Watch Smart', 'Camera HD', 'Headphones Wireless', 'Speaker Bluetooth', 'Monitor 4K'],
    'Category': ['Electronics', 'Electronics', 'Electronics', 'Accessories', 'Electronics', 'Accessories', 'Accessories', 'Electronics'],
    'Price': [1000, 500, 300, 200, 800, 150, 100, 600],
    'Stock': [50, 120, 80, 200, 45, 150, 100, 70],
    'Rating': [4.5, 4.7, 4.2, 4.0, 4.8, 4.3, 4.1, 4.6]
})

products.to_csv('products.csv', index=False)
print("products.csv yaratildi!")

products.csv yaratildi!

##### 1. **Ma'lumotlarni yuklash va tushunish**

In [5]:
# barcha fayllarni o'qish
df_customers = pd.read_csv('customers.csv')
df_orders = pd.read_csv("orders.csv")
df_products = pd.read_csv("products.csv")

In [6]:
# customers jadvalini o'rganish
df_customers.head()

,CustomerID,CustomerName,Email,City,JoinDate,Age,Membership
0,C001,Ali Khan,ali@example.com,Tashkent,2020-03-15,28,Gold
1,C002,Vali Karimov,vali@test.com,Samarkand,2019-07-22,35,Silver
2,C003,Sardor Toshmatov,sardor@mail.uz,Bukhara,2021-11-08,42,Gold
3,C004,Jasur Aliyev,jasur@inbox.com,Tashkent,2020-05-10,31,Bronze
4,C005,Kamol Rashidov,kamol@company.uz,Fergana,2022-01-20,26,Silver

In [7]:
df_customers.shape

(10, 7)

In [8]:
df_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    10 non-null     object
 1   CustomerName  10 non-null     object
 2   Email         10 non-null     object
 3   City          10 non-null     object
 4   JoinDate      10 non-null     object
 5   Age           10 non-null     int64
 6   Membership    10 non-null     object
dtypes: int64(1), object(6)
memory usage: 692.0+ bytes

- `JoinDate` ustunining ma'lumot turini datetime formatiga o'tkizish kerak

In [9]:
# orders jadvalini o'rganish
df_orders.head()

,OrderID,CustomerID,ProductID,OrderDate,Quantity,Price,Region,Status
0,1001,C007,P001,2024-01-01 00:00:00.000000000,4.0,100,West,Completed
1,1002,C004,P006,2024-01-01 17:33:18.396793587,6.0,300,North,Completed
2,1003,C008,P001,2024-01-02 11:06:36.793587174,2.0,250,North,Cancelled
3,1004,C005,P001,2024-01-03 04:39:55.190380761,8.0,50,North,Completed
4,1005,C007,P006,2024-01-03 22:13:13.587174348,8.0,1000,East,Completed

In [10]:
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 510 entries, 0 to 509
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   OrderID     510 non-null    int64
 1   CustomerID  510 non-null    object
 2   ProductID   510 non-null    object
 3   OrderDate   510 non-null    object
 4   Quantity    490 non-null    float64
 5   Price       510 non-null    int64
 6   Region      495 non-null    object
 7   Status      510 non-null    object
dtypes: float64(1), int64(2), object(5)
memory usage: 32.0+ KB

- `OrderDate` ustunini datetime formatiga o'tkizish kerak

In [11]:
df_orders.shape

(510, 8)

In [12]:
# products jadvalini o'rganish
df_products.head()

  ProductID  ProductName     Category  Price  Stock  Rating
0      P001   Laptop Pro  Electronics   1000     50     4.5
1      P002      Phone X  Electronics    500    120     4.7
2      P003   Tablet Max  Electronics    300     80     4.2
3      P004  Watch Smart  Accessories    200    200     4.0
4      P005    Camera HD  Electronics    800     45     4.8

In [13]:
df_products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ProductID    8 non-null      object
 1   ProductName  8 non-null      object
 2   Category     8 non-null      object
 3   Price        8 non-null      int64
 4   Stock        8 non-null      int64
 5   Rating       8 non-null      float64
dtypes: float64(1), int64(2), object(3)
memory usage: 516.0+ bytes

#####2. **MA'LUMOTLARNI TOZALASH**

- Email ustunidan faqat domen nomlarini ajratib, yangi EmailDomain ustuni yaratish

In [14]:
df_customers['Domen_email'] = df_customers['Email'].str.split('@').str[1]
df_customers.head()

,CustomerID,CustomerName,Email,City,JoinDate,Age,Membership,Domen_email
0,C001,Ali Khan,ali@example.com,Tashkent,2020-03-15,28,Gold,example.com
1,C002,Vali Karimov,vali@test.com,Samarkand,2019-07-22,35,Silver,test.com
2,C003,Sardor Toshmatov,sardor@mail.uz,Bukhara,2021-11-08,42,Gold,mail.uz
3,C004,Jasur Aliyev,jasur@inbox.com,Tashkent,2020-05-10,31,Bronze,inbox.com
4,C005,Kamol Rashidov,kamol@company.uz,Fergana,2022-01-20,26,Silver,company.uz

- CustomerName ustunidan faqatgina ismlarni ajratib yangi ustun yaratish

In [15]:
df_customers['First_name'] = df_customers['CustomerName'].str.split().str[0]
df_customers

,CustomerID,CustomerName,Email,City,JoinDate,Age,Membership,Domen_email,First_name
0,C001,Ali Khan,ali@example.com,Tashkent,2020-03-15,28,Gold,example.com,Ali
1,C002,Vali Karimov,vali@test.com,Samarkand,2019-07-22,35,Silver,test.com,Vali
2,C003,Sardor Toshmatov,sardor@mail.uz,Bukhara,2021-11-08,42,Gold,mail.uz,Sardor
3,C004,Jasur Aliyev,jasur@inbox.com,Tashkent,2020-05-10,31,Bronze,inbox.com,Jasur
4,C005,Kamol Rashidov,kamol@company.uz,Fergana,2022-01-20,26,Silver,company.uz,Kamol
5,C006,Nodir Sultonov,nodir@business.com,Namangan,2021-06-15,38,Gold,business.com,Nodir
6,C007,Aziz Mahmudov,aziz@enterprise.net,Tashkent,2020-09-30,45,Platinum,enterprise.net,Aziz
7,C008,Bobur Yusupov,bobur@client.org,Andijan,2022-04-12,29,Bronze,client.org,Bobur
8,C009,Davron Ismoilov,davron@partner.io,Samarkand,2021-08-25,33,Silver,partner.io,Davron
9,C010,Eldor Nabiyev,eldor@shop.com,Bukhara,2022-11-05,40,Gold,shop.com,Eldor

- Age ustunini guruhlash : 25 dan kichik `young` , 25-35 `adult` , 35 dan katta `senior`

In [16]:
groups = [-np.inf, 25, 35, np.inf]
group_names = ['young', 'adult', 'senior']
df_customers['Age_group'] = pd.cut(df_customers['Age'], bins=groups, labels=group_names)
df_customers.head()

,CustomerID,CustomerName,Email,City,JoinDate,Age,Membership,Domen_email,First_name,Age_group
0,C001,Ali Khan,ali@example.com,Tashkent,2020-03-15,28,Gold,example.com,Ali,adult
1,C002,Vali Karimov,vali@test.com,Samarkand,2019-07-22,35,Silver,test.com,Vali,adult
2,C003,Sardor Toshmatov,sardor@mail.uz,Bukhara,2021-11-08,42,Gold,mail.uz,Sardor,senior
3,C004,Jasur Aliyev,jasur@inbox.com,Tashkent,2020-05-10,31,Bronze,inbox.com,Jasur,adult
4,C005,Kamol Rashidov,kamol@company.uz,Fergana,2022-01-20,26,Silver,company.uz,Kamol,adult

- Orders jadvalidagi NaN qiymatlarni aniqlash

In [17]:
df_orders.isna().sum()

OrderID        0
CustomerID     0
ProductID      0
OrderDate      0
Quantity      20
Price          0
Region        15
Status         0
dtype: int64

- `quantity` ustunidagi mavjud bo'lmagan qiymatlarni , shu ustun o'rtacha qiymati bilan to'ldirish

In [18]:
df_orders['Quantity'].mean()

np.float64(4.987755102040817)

In [19]:
df_orders['Quantity'].fillna(df_orders['Quantity'].mean(), inplace=True)

/tmp/ipykernel_1466/1111262266.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_orders['Quantity'].fillna(df_orders['Quantity'].mean(), inplace=True)

In [21]:
df_orders.isna().sum()

OrderID        0
CustomerID     0
ProductID      0
OrderDate      0
Quantity       0
Price          0
Region        15
Status         0
dtype: int64

- Region ustunidagi NaN larni , ushbu ustunda eng ko'p uchraydigan qiymat bilan to'ldirish

In [22]:
df_orders['Region'].value_counts()

Region
North    132
South    125
West     121
East     117
Name: count, dtype: int64

In [23]:
df_orders['Region'] = df_orders['Region'].fillna(df_orders['Region'].mode()[0])
df_orders['Region'].isna().sum()

np.int64(0)

In [24]:
df_orders.duplicated().sum()

np.int64(10)

- takrorlangan qatorlarni o'chirish

In [25]:
df_orders = df_orders.drop_duplicates()
df_orders.duplicated().sum()

np.int64(0)

In [26]:
df_products.head(3)

  ProductID ProductName     Category  Price  Stock  Rating
0      P001  Laptop Pro  Electronics   1000     50     4.5
1      P002     Phone X  Electronics    500    120     4.7
2      P003  Tablet Max  Electronics    300     80     4.2

- `df_products` jadvalidagi ProductName larni katta harf qilish

In [28]:
df_products['ProductName'] = df_products['ProductName'].str.upper()
df_products.head(3)

  ProductID ProductName     Category  Price  Stock  Rating
0      P001  LAPTOP PRO  Electronics   1000     50     4.5
1      P002     PHONE X  Electronics    500    120     4.7
2      P003  TABLET MAX  Electronics    300     80     4.2

- yangi `stock_status` ustuni yaratish

In [29]:
groups_product = [-np.inf, 50, 100, np.inf]
group_names_product = ['Low stock', 'Medium stock', 'High stock']
df_products['Stock_status'] = pd.cut(df_products['Stock'], bins=groups_product, labels=group_names_product)
df_products.head()

  ProductID  ProductName     Category  Price  Stock  Rating  Stock_status
0      P001   LAPTOP PRO  Electronics   1000     50     4.5     Low stock
1      P002      PHONE X  Electronics    500    120     4.7    High stock
2      P003   TABLET MAX  Electronics    300     80     4.2  Medium stock
3      P004  WATCH SMART  Accessories    200    200     4.0    High stock
4      P005    CAMERA HD  Electronics    800     45     4.8     Low stock

#####3. **Ma'lumotlarni birlashtirish**

- orders va product jadvallarini ProductId ustuni yordamida birlashtirish

In [33]:
df_orders_product = pd.merge(df_orders, df_products, on='ProductID', how='inner')
df_orders_product.head()

,OrderID,CustomerID,ProductID,OrderDate,Quantity,Price_x,Region,Status,ProductName,Category,Price_y,Stock,Rating,Stock_status
0,1001,C007,P001,2024-01-01 00:00:00.000000000,4.0,100,West,Completed,LAPTOP PRO,Electronics,1000,50,4.5,Low stock
1,1002,C004,P006,2024-01-01 17:33:18.396793587,6.0,300,North,Completed,HEADPHONES WIRELESS,Accessories,150,150,4.3,High stock
2,1003,C008,P001,2024-01-02 11:06:36.793587174,2.0,250,North,Cancelled,LAPTOP PRO,Electronics,1000,50,4.5,Low stock
3,1004,C005,P001,2024-01-03 04:39:55.190380761,8.0,50,North,Completed,LAPTOP PRO,Electronics,1000,50,4.5,Low stock
4,1005,C007,P006,2024-01-03 22:13:13.587174348,8.0,1000,East,Completed,HEADPHONES WIRELESS,Accessories,150,150,4.3,High stock

In [34]:
df_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    10 non-null     object
 1   CustomerName  10 non-null     object
 2   Email         10 non-null     object
 3   City          10 non-null     object
 4   JoinDate      10 non-null     object
 5   Age           10 non-null     int64
 6   Membership    10 non-null     object
 7   Domen_email   10 non-null     object
 8   First_name    10 non-null     object
 9   Age_group     10 non-null     category
dtypes: category(1), int64(1), object(8)
memory usage: 994.0+ bytes

- yuqoridagi yangi jadvalga `customers` jadvalini CustomerID ustuni yordamida birlashtirish

In [36]:
df_orders_product_customer = pd.merge(df_orders_product, df_customers, on='CustomerID', how='inner')
df_orders_product_customer.head()

,OrderID,CustomerID,ProductID,OrderDate,Quantity,Price_x,Region,Status,ProductName,Category,...,Stock_status,CustomerName,Email,City,JoinDate,Age,Membership,Domen_email,First_name,Age_group
0,1001,C007,P001,2024-01-01 00:00:00.000000000,4.0,100,West,Completed,LAPTOP PRO,Electronics,...,Low stock,Aziz Mahmudov,aziz@enterprise.net,Tashkent,2020-09-30,45,Platinum,enterprise.net,Aziz,senior
1,1002,C004,P006,2024-01-01 17:33:18.396793587,6.0,300,North,Completed,HEADPHONES WIRELESS,Accessories,...,High stock,Jasur Aliyev,jasur@inbox.com,Tashkent,2020-05-10,31,Bronze,inbox.com,Jasur,adult
2,1003,C008,P001,2024-01-02 11:06:36.793587174,2.0,250,North,Cancelled,LAPTOP PRO,Electronics,...,Low stock,Bobur Yusupov,bobur@client.org,Andijan,2022-04-12,29,Bronze,client.org,Bobur,adult
3,1004,C005,P001,2024-01-03 04:39:55.190380761,8.0,50,North,Completed,LAPTOP PRO,Electronics,...,Low stock,Kamol Rashidov,kamol@company.uz,Fergana,2022-01-20,26,Silver,company.uz,Kamol,adult
4,1005,C007,P006,2024-01-03 22:13:13.587174348,8.0,1000,East,Completed,HEADPHONES WIRELESS,Accessories,...,High stock,Aziz Mahmudov,aziz@enterprise.net,Tashkent,2020-09-30,45,Platinum,enterprise.net,Aziz,senior

In [37]:
# katta jadvalda nanlarni tekshirish
df_orders_product_customer.isna().sum()

OrderID         0
CustomerID      0
ProductID       0
OrderDate       0
Quantity        0
Price_x         0
Region          0
Status          0
ProductName     0
Category        0
Price_y         0
Stock           0
Rating          0
Stock_status    0
CustomerName    0
Email           0
City            0
JoinDate        0
Age             0
Membership      0
Domen_email     0
First_name      0
Age_group       0
dtype: int64

In [39]:
df = df_orders_product_customer
df.head()

,OrderID,CustomerID,ProductID,OrderDate,Quantity,Price_x,Region,Status,ProductName,Category,...,Stock_status,CustomerName,Email,City,JoinDate,Age,Membership,Domen_email,First_name,Age_group
0,1001,C007,P001,2024-01-01 00:00:00.000000000,4.0,100,West,Completed,LAPTOP PRO,Electronics,...,Low stock,Aziz Mahmudov,aziz@enterprise.net,Tashkent,2020-09-30,45,Platinum,enterprise.net,Aziz,senior
1,1002,C004,P006,2024-01-01 17:33:18.396793587,6.0,300,North,Completed,HEADPHONES WIRELESS,Accessories,...,High stock,Jasur Aliyev,jasur@inbox.com,Tashkent,2020-05-10,31,Bronze,inbox.com,Jasur,adult
2,1003,C008,P001,2024-01-02 11:06:36.793587174,2.0,250,North,Cancelled,LAPTOP PRO,Electronics,...,Low stock,Bobur Yusupov,bobur@client.org,Andijan,2022-04-12,29,Bronze,client.org,Bobur,adult
3,1004,C005,P001,2024-01-03 04:39:55.190380761,8.0,50,North,Completed,LAPTOP PRO,Electronics,...,Low stock,Kamol Rashidov,kamol@company.uz,Fergana,2022-01-20,26,Silver,company.uz,Kamol,adult
4,1005,C007,P006,2024-01-03 22:13:13.587174348,8.0,1000,East,Completed,HEADPHONES WIRELESS,Accessories,...,High stock,Aziz Mahmudov,aziz@enterprise.net,Tashkent,2020-09-30,45,Platinum,enterprise.net,Aziz,senior

In [40]:
del df_orders_product_customer

In [41]:
df['Price_x']

0       100
1       300
2       250
3        50
4      1000
       ...
495     150
496     100
497     300
498     200
499     500
Name: Price_x, Length: 500, dtype: int64

In [42]:
df['Price_y']

0      1000
1       150
2      1000
3      1000
4       150
       ...
495     500
496     300
497    1000
498     800
499     500
Name: Price_y, Length: 500, dtype: int64