<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/pandas/projects/E_Commerce_Store_Sales_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [3]:
# Store sales data tables for one day
raw_data = {
    'Customer_ID': [101, 102, 103, 104, 105, 106],
    'Name': ['Anvar', 'Malika', None, 'Shaxzod', 'Zilola', 'Anvar'],
    'Product': ['Yengil Oyoq kiyim', 'Sumka', 'Telefon', 'Ko\'ylak', 'Sumka', 'Yengil Oyoq kiyim'],
    'Price': [45.0, np.nan, 800.0, 30.0, 65.0, 45.0],
    'Quantity': [2, 1, 1, 3, 2, 1],
    'Status': ['Yetkazildi', 'Bekor qilindi', 'Yetkazildi', 'Yetkazildi', 'Kutilmoqda', 'Yetkazildi']
}

df = pd.DataFrame(raw_data)
print(df)

   Customer_ID     Name            Product  Price  Quantity         Status
0          101    Anvar  Yengil Oyoq kiyim   45.0         2     Yetkazildi
1          102   Malika              Sumka    NaN         1  Bekor qilindi
2          103     None            Telefon  800.0         1     Yetkazildi
3          104  Shaxzod            Ko'ylak   30.0         3     Yetkazildi
4          105   Zilola              Sumka   65.0         2     Kutilmoqda
5          106    Anvar  Yengil Oyoq kiyim   45.0         1     Yetkazildi

In [4]:
df.head(3)

   Customer_ID    Name            Product  Price  Quantity         Status
0          101   Anvar  Yengil Oyoq kiyim   45.0         2     Yetkazildi
1          102  Malika              Sumka    NaN         1  Bekor qilindi
2          103    None            Telefon  800.0         1     Yetkazildi

In [5]:
df.shape

(6, 6)

In [12]:
# identify unnamed line
df[df['Name'].isna()]

   Customer_ID  Name  Product  Price  Quantity      Status
2          103  None  Telefon  800.0         1  Yetkazildi

- change the unnamed buyer to an unknown buyer

In [16]:
df.loc[[2], ['Name']] = "Noma'lum_xaridor"

In [17]:
df

,Customer_ID,Name,Product,Price,Quantity,Status
0,101,Anvar,Yengil Oyoq kiyim,45.0,2,Yetkazildi
1,102,Malika,Sumka,NaN,1,Bekor qilindi
2,103,Noma'lum_xaridor,Telefon,800.0,1,Yetkazildi
3,104,Shaxzod,Ko'ylak,30.0,3,Yetkazildi
4,105,Zilola,Sumka,65.0,2,Kutilmoqda
5,106,Anvar,Yengil Oyoq kiyim,45.0,1,Yetkazildi

In [18]:
df[df['Price'].isna()]

   Customer_ID    Name Product  Price  Quantity         Status
1          102  Malika   Sumka    NaN         1  Bekor qilindi

- According to the table, the price of Malika's bag is not written. Fill it in with the price of Zilola's bag

In [19]:
df[df['Product'] == 'Sumka']

   Customer_ID    Name Product  Price  Quantity         Status
1          102  Malika   Sumka    NaN         1  Bekor qilindi
4          105  Zilola   Sumka   65.0         2     Kutilmoqda

In [21]:
bag_price = df.loc[4, 'Price']
df.loc[1, 'Price'] = bag_price

In [22]:
df

,Customer_ID,Name,Product,Price,Quantity,Status
0,101,Anvar,Yengil Oyoq kiyim,45.0,2,Yetkazildi
1,102,Malika,Sumka,65.0,1,Bekor qilindi
2,103,Noma'lum_xaridor,Telefon,800.0,1,Yetkazildi
3,104,Shaxzod,Ko'ylak,30.0,3,Yetkazildi
4,105,Zilola,Sumka,65.0,2,Kutilmoqda
5,106,Anvar,Yengil Oyoq kiyim,45.0,1,Yetkazildi

In [26]:
# detecting duplicate data
df[df.duplicated(subset=['Name'])]

   Customer_ID   Name            Product  Price  Quantity      Status
5          106  Anvar  Yengil Oyoq kiyim   45.0         1  Yetkazildi

In [27]:
# delete duplicate information
df.drop_duplicates(subset=['Name'], inplace=True)

In [28]:
df

,Customer_ID,Name,Product,Price,Quantity,Status
0,101,Anvar,Yengil Oyoq kiyim,45.0,2,Yetkazildi
1,102,Malika,Sumka,65.0,1,Bekor qilindi
2,103,Noma'lum_xaridor,Telefon,800.0,1,Yetkazildi
3,104,Shaxzod,Ko'ylak,30.0,3,Yetkazildi
4,105,Zilola,Sumka,65.0,2,Kutilmoqda

In [29]:
# determine how much money each customer spent in total and save the data to a new table
df['Total_spent'] = df['Price'] * df['Quantity']
df

,Customer_ID,Name,Product,Price,Quantity,Status,Total_spent
0,101,Anvar,Yengil Oyoq kiyim,45.0,2,Yetkazildi,90.0
1,102,Malika,Sumka,65.0,1,Bekor qilindi,65.0
2,103,Noma'lum_xaridor,Telefon,800.0,1,Yetkazildi,800.0
3,104,Shaxzod,Ko'ylak,30.0,3,Yetkazildi,90.0
4,105,Zilola,Sumka,65.0,2,Kutilmoqda,130.0

In [30]:
# Customers whose products are shipped and whose purchase amount is over 50
df[(df['Status'] == 'Yetkazildi') & (df['Total_spent'] > 50)]

,Customer_ID,Name,Product,Price,Quantity,Status,Total_spent
0,101,Anvar,Yengil Oyoq kiyim,45.0,2,Yetkazildi,90.0
2,103,Noma'lum_xaridor,Telefon,800.0,1,Yetkazildi,800.0
3,104,Shaxzod,Ko'ylak,30.0,3,Yetkazildi,90.0