<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/pandas/projects/FinTech_Banking_Customers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
# 1-Jadval: Mijozlar bazasi (Users)
users_data = {
    'User_ID': [1, 2, 3, 4, 5],
    'Age': [28, 34, np.nan, 45, 22], # 3-mijozning yoshi yo'q
    'City': ['Tashkent', 'Samarkand', 'Bukhara', 'Tashkent', 'Samarkand'],
    'Segment': ['Silver', 'Gold', 'Silver', 'Platinum', 'Silver']
}
df_users = pd.DataFrame(users_data)

# 2-Jadval: Tranzaksiyalar tarixi (Transactions)
tx_data = {
    'Tx_ID': [1001, 1002, 1003, 1004, 1005, 1006, 1007],
    'User_ID': [1, 2, 1, 3, 4, 2, 99], # 99-ID li foydalanuvchi bizning bazada yo'q!
    'Amount': [150.0, 500.0, 45.0, 1200.0, 300.0, np.nan, 80.0], # 1006-tx da summa yo'q
    'Category': ['Electronics', 'Travel', 'Grocery', 'Electronics', 'Clothes', 'Travel', 'Grocery'],
    'Date': ['2026-01-15', '2026-01-16', '2026-02-10', '2026-02-11', '2026-03-01', '2026-03-02', '2026-03-15']
}
df_tx = pd.DataFrame(tx_data)

In [3]:
df_users.head()

   User_ID   Age       City   Segment
0        1  28.0   Tashkent    Silver
1        2  34.0  Samarkand      Gold
2        3   NaN    Bukhara    Silver
3        4  45.0   Tashkent  Platinum
4        5  22.0  Samarkand    Silver

In [4]:
df_users.shape

(5, 4)

In [5]:
df_tx

   Tx_ID  User_ID  Amount     Category        Date
0   1001        1   150.0  Electronics  2026-01-15
1   1002        2   500.0       Travel  2026-01-16
2   1003        1    45.0      Grocery  2026-02-10
3   1004        3  1200.0  Electronics  2026-02-11
4   1005        4   300.0      Clothes  2026-03-01
5   1006        2     NaN       Travel  2026-03-02
6   1007       99    80.0      Grocery  2026-03-15

In [6]:
df_tx.shape

(7, 5)

In [7]:
# Filling in the information (age) of a customer whose age is not recorded
df_users['Age'] = df_users['Age'].fillna(df_users['Age'].mean())
df_users

   User_ID    Age       City   Segment
0        1  28.00   Tashkent    Silver
1        2  34.00  Samarkand      Gold
2        3  32.25    Bukhara    Silver
3        4  45.00   Tashkent  Platinum
4        5  22.00  Samarkand    Silver

In [8]:
# convert customer ages to integer format
df_users['Age'] = df_users['Age'].astype(int)
df_users

   User_ID  Age       City   Segment
0        1   28   Tashkent    Silver
1        2   34  Samarkand      Gold
2        3   32    Bukhara    Silver
3        4   45   Tashkent  Platinum
4        5   22  Samarkand    Silver

In [9]:
df_tx

   Tx_ID  User_ID  Amount     Category        Date
0   1001        1   150.0  Electronics  2026-01-15
1   1002        2   500.0       Travel  2026-01-16
2   1003        1    45.0      Grocery  2026-02-10
3   1004        3  1200.0  Electronics  2026-02-11
4   1005        4   300.0      Clothes  2026-03-01
5   1006        2     NaN       Travel  2026-03-02
6   1007       99    80.0      Grocery  2026-03-15

In [10]:
# fill in a transaction with no amount
df_tx['Amount'] = df_tx.groupby('Category')['Amount'].ffill()
df_tx

   Tx_ID  User_ID  Amount     Category        Date
0   1001        1   150.0  Electronics  2026-01-15
1   1002        2   500.0       Travel  2026-01-16
2   1003        1    45.0      Grocery  2026-02-10
3   1004        3  1200.0  Electronics  2026-02-11
4   1005        4   300.0      Clothes  2026-03-01
5   1006        2   500.0       Travel  2026-03-02
6   1007       99    80.0      Grocery  2026-03-15

In [11]:
# Converting the Date column in the df_tx table to datetime format
df_tx['Date'] = pd.to_datetime(df_tx['Date'])
df_tx

   Tx_ID  User_ID  Amount     Category       Date
0   1001        1   150.0  Electronics 2026-01-15
1   1002        2   500.0       Travel 2026-01-16
2   1003        1    45.0      Grocery 2026-02-10
3   1004        3  1200.0  Electronics 2026-02-11
4   1005        4   300.0      Clothes 2026-03-01
5   1006        2   500.0       Travel 2026-03-02
6   1007       99    80.0      Grocery 2026-03-15

In [12]:
# Extract only the month names from the date column and place them in a new column
df_tx['Month'] = df_tx['Date'].dt.month_name()
df_tx

   Tx_ID  User_ID  Amount     Category       Date     Month
0   1001        1   150.0  Electronics 2026-01-15   January
1   1002        2   500.0       Travel 2026-01-16   January
2   1003        1    45.0      Grocery 2026-02-10  February
3   1004        3  1200.0  Electronics 2026-02-11  February
4   1005        4   300.0      Clothes 2026-03-01     March
5   1006        2   500.0       Travel 2026-03-02     March
6   1007       99    80.0      Grocery 2026-03-15     March

In [13]:
# merge tables of customers and their transactions
df_bank = pd.merge(df_users, df_tx, on='User_ID', how='inner')
df_bank

,User_ID,Age,City,Segment,Tx_ID,Amount,Category,Date,Month
0,1,28,Tashkent,Silver,1001,150.0,Electronics,2026-01-15,January
1,1,28,Tashkent,Silver,1003,45.0,Grocery,2026-02-10,February
2,2,34,Samarkand,Gold,1002,500.0,Travel,2026-01-16,January
3,2,34,Samarkand,Gold,1006,500.0,Travel,2026-03-02,March
4,3,32,Bukhara,Silver,1004,1200.0,Electronics,2026-02-11,February
5,4,45,Tashkent,Platinum,1005,300.0,Clothes,2026-03-01,March

In [14]:
# Determine how much money was spent in total in each city and how many transactions were made in total
df_bank.groupby('City')['Amount'].agg(total_amount='sum', transactions='count').reset_index()

        City  total_amount  transactions
0    Bukhara        1200.0             1
1  Samarkand        1000.0             2
2   Tashkent         495.0             3

In [17]:
# determine how much money each customer segment spent on each category
segment_cat = pd.pivot_table(df_bank, values='Amount', index='Segment', columns='Category', aggfunc='sum', fill_value=0)
segment_cat

Category  Clothes  Electronics  Grocery  Travel
Segment
Gold          0.0          0.0      0.0  1000.0
Platinum    300.0          0.0      0.0     0.0
Silver        0.0       1350.0     45.0     0.0

In [18]:
df_bank[(df_bank['Age'] > 30) & (df_bank['Amount'] > 200)]

,User_ID,Age,City,Segment,Tx_ID,Amount,Category,Date,Month
2,2,34,Samarkand,Gold,1002,500.0,Travel,2026-01-16,January
3,2,34,Samarkand,Gold,1006,500.0,Travel,2026-03-02,March
4,3,32,Bukhara,Silver,1004,1200.0,Electronics,2026-02-11,February
5,4,45,Tashkent,Platinum,1005,300.0,Clothes,2026-03-01,March