<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/pandas/football_Liga_datasets_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
! wget https://raw.githubusercontent.com/datasets/football-datasets/refs/heads/main/datasets/premier-league/season-0001.csv
! wget https://raw.githubusercontent.com/datasets/football-datasets/refs/heads/main/datasets/la-liga/season-0001.csv
! wget https://raw.githubusercontent.com/datasets/football-datasets/refs/heads/main/datasets/bundesliga/season-0001.csv

--2026-10-19 04:05:39--  https://raw.githubusercontent.com/datasets/football-datasets/refs/heads/main/datasets/premier-league/season-0001.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 31022 (30K) [text/plain]
Saving to: ‘season-0001.csv’

season-0001.csv     100%[===================>]  30.29K  --.-KB/s    in 0.002s

2026-10-19 04:05:40 (14.5 MB/s) - ‘season-0001.csv’ saved [31022/31022]

--2026-10-19 04:05:40--  https://raw.githubusercontent.com/datasets/football-datasets/refs/heads/main/datasets/la-liga/season-0001.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20769 (20K) [text/plain]
Saving to: ‘season-0001.csv.1’

season-0001.csv.1   100%[===================>]  20.28K  --.-KB/s    in 0.001s

2026-10-19 04:05:40 (28.3 MB/s) - ‘season-0001.csv.1’ saved [20769/20769]

--2026-10-19 04:05:40--  https://raw.githubusercontent.com/datasets/football-datasets/refs/heads/main/datasets/bundesliga/season-0001.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 27037 (26K) [text/plain]
Saving to: ‘season-0001.csv.2’

season-0001.csv.2   100%[===================>]  26.40K  --.-KB/s    in 0.02s

2026-10-19 04:05:40 (1.48 MB/s) - ‘season-0001.csv.2’ saved [27037/27037]

In [3]:
# Premier Liga
df1 = pd.read_csv("/content/season-0001.csv")
df1.head()

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
0,2000-08-19,Charlton,Man City,4,0,H,2,0,H,Rob Harris,...,14,4,13,12,6,6,1,2,0,0
1,2000-08-19,Chelsea,West Ham,4,2,H,1,0,H,Graham Barber,...,10,5,19,14,7,7,1,2,0,0
2,2000-08-19,Coventry,Middlesbrough,1,3,A,1,1,D,Barry Knight,...,3,9,15,21,8,4,5,3,1,0
3,2000-08-19,Derby,Southampton,2,2,D,1,2,A,Andy D'Urso,...,4,6,11,13,5,8,1,1,0,0
4,2000-08-19,Leeds,Everton,2,0,H,2,0,H,Dermot Gallagher,...,8,6,21,20,6,4,1,3,0,0

In [4]:
# LaLiga dataset
df2 = pd.read_csv("/content/season-0001.csv.1")
df2.head()

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
0,2000-09-09,Barcelona,Malaga,2,1,H,2,0,H,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000-09-09,La Coruna,Ath Bilbao,2,0,H,0,0,D,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000-09-09,Real Madrid,Valencia,2,1,H,0,0,D,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000-09-09,Sociedad,Santander,2,2,D,0,0,D,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2000-09-09,Zaragoza,Espanol,1,2,A,0,0,D,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# BundesLiga dataset
df3 = pd.read_csv("/content/season-0001.csv.2")
df3.head()

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
0,2000-08-11,Dortmund,Hansa Rostock,1,0,H,0,0,D,Jörg Kessler,...,7,2,25,19,7,3,1,5,0,0
1,2000-08-12,Bayern Munich,Hertha,4,1,H,1,0,H,Markus Merk,...,6,5,13,12,4,9,1,0,0,0
2,2000-08-12,Freiburg,Stuttgart,4,0,H,2,0,H,Helmut Krug,...,7,5,22,17,4,7,1,1,0,0
3,2000-08-12,Hamburg,Munich 1860,2,2,D,2,2,D,Herbert Fandel,...,5,7,0,0,5,3,2,2,0,1
4,2000-08-12,Kaiserslautern,Bochum,0,1,A,0,0,D,Helmut Fleischer,...,2,2,9,8,5,5,1,0,0,0

**DF ustunlari**

- FTHG (Full Time Home Team Goals): Meybon jamoasining to'liq o'yin (90 daqiqa) davomida urgan gollari soni.   
- FTAG (Full Time Away Team Goals): Mehmon jamoasining to'liq o'yin davomida urgan gollari soni.   
- FTR (Full Time Result): O'yinning yakuniy natijasi:H = Home Win (Meybon jamoa g'alabasi)   A = Away Win (Mehmon jamoa g'alabasi)   D = Draw (Durang)   
- HTHG (Half Time Home Team Goals): Birinchi bo'limda (taymda) mezbon jamoa urgan gollar soni.   
- HTAG (Half Time Away Team Goals): Birinchi bo'limda mehmon jamoa urgan gollar soni.   
- HTR (Half Time Result): Birinchi bo'lim yakuniy natijasi (H, A yoki D)


- HS (Home Shots): Mezbon jamoaning darvoza tomonga yo'llagan barcha zarbalari soni.
- AS (Away Shots): Mehmon jamoaning darvoza tomonga yo'llagan barcha zarbalari soni.
- HST (Home Shots on Target): Mezbon jamoaning aniq (darvoza sohasiga borgan) zarbalari soni.   
- AST (Away Shots on Target): Mehmon jamoaning aniq zarbalari soni.   
- HF (Home Fouls): Mezbon jamoa tomonidan ishlatilgan fol (qoida buzilish)lar soni.   
- AF (Away Fouls): Mehmon jamoa tomonidan ishlatilgan follar soni.   
- HC (Home Corners): Mezbon jamoaning burchak zarbalari (korner) soni.   
- AC (Away Corners): Mehmon jamoaning burchak zarbalari soni

In [6]:
# LaLiga ohirgi 5 ta qator ma'lumotlarini ko'rish
df2.tail()

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
375,2001-06-17,La Coruna,Malaga,4,0,H,1,0,H,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
376,2001-06-17,Mallorca,Oviedo,4,2,H,1,0,H,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
377,2001-06-17,Real Madrid,Valladolid,2,1,H,1,0,H,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
378,2001-06-17,Sociedad,Osasuna,0,1,A,0,1,A,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
379,2001-06-17,Zaragoza,Celta,1,1,D,0,0,D,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df2.sample(5)

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
101,2000-11-18,Las Palmas,Mallorca,1,0,H,0,0,D,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
326,2001-05-06,Vallecano,La Coruna,1,1,D,0,0,D,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
207,2001-02-04,Sociedad,Celta,2,2,D,1,0,H,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145,2000-12-17,Osasuna,Numancia,2,0,H,0,0,D,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,2000-11-05,Sociedad,Mallorca,0,1,A,0,0,D,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# LaLiga datasetini hajmi
df2.shape

(380, 22)

In [9]:
# Primier ligani hajmi
df1.shape

(380, 22)

In [10]:
# bundesligani hajmi
df3.shape

(306, 22)

- BundesLiga datasetining ma'lumotlari qolgan ikki datasetnikidan kamroq ekan

In [11]:
# primier liga dataseti umumiy ma'lumotlari
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 380 entries, 0 to 379
Data columns (total 22 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      380 non-null    object
 1   HomeTeam  380 non-null    object
 2   AwayTeam  380 non-null    object
 3   FTHG      380 non-null    int64
 4   FTAG      380 non-null    int64
 5   FTR       380 non-null    object
 6   HTHG      380 non-null    int64
 7   HTAG      380 non-null    int64
 8   HTR       380 non-null    object
 9   Referee   380 non-null    object
 10  HS        380 non-null    int64
 11  AS        380 non-null    int64
 12  HST       380 non-null    int64
 13  AST       380 non-null    int64
 14  HF        380 non-null    int64
 15  AF        380 non-null    int64
 16  HC        380 non-null    int64
 17  AC        380 non-null    int64
 18  HY        380 non-null    int64
 19  AY        380 non-null    int64
 20  HR        380 non-null    int64
 21  AR        380 non-null    int64
dtypes: int64(16), object(6)
memory usage: 65.4+ KB

1. Date ustuni objectda turibdi , uni date formatida qilish kerak

In [12]:
# LaLiga dataseti umumiy ma'lumotlari
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 380 entries, 0 to 379
Data columns (total 22 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      380 non-null    object
 1   HomeTeam  380 non-null    object
 2   AwayTeam  380 non-null    object
 3   FTHG      380 non-null    int64
 4   FTAG      380 non-null    int64
 5   FTR       380 non-null    object
 6   HTHG      380 non-null    int64
 7   HTAG      380 non-null    int64
 8   HTR       380 non-null    object
 9   Referee   0 non-null      float64
 10  HS        0 non-null      float64
 11  AS        0 non-null      float64
 12  HST       0 non-null      float64
 13  AST       0 non-null      float64
 14  HF        0 non-null      float64
 15  AF        0 non-null      float64
 16  HC        0 non-null      float64
 17  AC        0 non-null      float64
 18  HY        0 non-null      float64
 19  AY        0 non-null      float64
 20  HR        0 non-null      float64
 21  AR        0 non-null      float64
dtypes: float64(13), int64(4), object(5)
memory usage: 65.4+ KB

1. Date ustuni objectda turibdi , date formatiga o'tkizish kerak
2. Referee ustunidan boshlab qolgan barcha ustunlar NaN lar bilan to'lgan

In [13]:
# BundesLiga dataseti umumiy ma'lumotlari
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 306 entries, 0 to 305
Data columns (total 22 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      306 non-null    object
 1   HomeTeam  306 non-null    object
 2   AwayTeam  306 non-null    object
 3   FTHG      306 non-null    int64
 4   FTAG      306 non-null    int64
 5   FTR       306 non-null    object
 6   HTHG      306 non-null    int64
 7   HTAG      306 non-null    int64
 8   HTR       306 non-null    object
 9   Referee   305 non-null    object
 10  HS        306 non-null    int64
 11  AS        306 non-null    int64
 12  HST       306 non-null    int64
 13  AST       306 non-null    int64
 14  HF        306 non-null    int64
 15  AF        306 non-null    int64
 16  HC        306 non-null    int64
 17  AC        306 non-null    int64
 18  HY        306 non-null    int64
 19  AY        306 non-null    int64
 20  HR        306 non-null    int64
 21  AR        306 non-null    int64
dtypes: int64(16), object(6)
memory usage: 52.7+ KB

1. Bunda ham Date usutni objectda

In [14]:
# PremierLiga ma'lumotlari
df1.describe()

,FTHG,FTAG,HTHG,HTAG,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
count,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000
mean,1.544737,1.065789,0.686842,0.476316,12.792105,9.378947,6.163158,4.531579,12.978947,13.944737,6.289474,4.647368,1.347368,1.794737,0.084211,0.081579
std,1.285436,1.029070,0.843623,0.694469,4.859117,3.609366,2.991582,2.239382,4.164757,4.382695,3.001388,2.742583,1.260468,1.309585,0.287402,0.292704
min,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,0.000000,0.000000,9.000000,7.000000,4.000000,3.000000,10.000000,11.000000,4.000000,3.000000,0.000000,1.000000,0.000000,0.000000
50%,1.000000,1.000000,0.000000,0.000000,12.000000,9.000000,6.000000,4.000000,13.000000,13.000000,6.000000,4.000000,1.000000,2.000000,0.000000,0.000000
75%,2.000000,2.000000,1.000000,1.000000,16.000000,12.000000,8.000000,6.000000,16.000000,17.000000,8.000000,6.000000,2.000000,3.000000,0.000000,0.000000
max,6.000000,4.000000,5.000000,4.000000,33.000000,24.000000,19.000000,14.000000,25.000000,28.000000,17.000000,14.000000,7.000000,7.000000,2.000000,2.000000

In [15]:
df1.describe(include='all')

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
count,380,380,380,380.000000,380.000000,380,380.000000,380.000000,380,380,...,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000
unique,97,20,20,NaN,NaN,3,NaN,NaN,3,29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2001-05-19,Charlton,Man City,NaN,NaN,H,NaN,NaN,D,Alan Wiley,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,10,19,19,NaN,NaN,184,NaN,NaN,152,23,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,1.544737,1.065789,NaN,0.686842,0.476316,NaN,NaN,...,6.163158,4.531579,12.978947,13.944737,6.289474,4.647368,1.347368,1.794737,0.084211,0.081579
std,NaN,NaN,NaN,1.285436,1.029070,NaN,0.843623,0.694469,NaN,NaN,...,2.991582,2.239382,4.164757,4.382695,3.001388,2.742583,1.260468,1.309585,0.287402,0.292704
min,NaN,NaN,NaN,0.000000,0.000000,NaN,0.000000,0.000000,NaN,NaN,...,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,NaN,1.000000,0.000000,NaN,0.000000,0.000000,NaN,NaN,...,4.000000,3.000000,10.000000,11.000000,4.000000,3.000000,0.000000,1.000000,0.000000,0.000000
50%,NaN,NaN,NaN,1.000000,1.000000,NaN,0.000000,0.000000,NaN,NaN,...,6.000000,4.000000,13.000000,13.000000,6.000000,4.000000,1.000000,2.000000,0.000000,0.000000
75%,NaN,NaN,NaN,2.000000,2.000000,NaN,1.000000,1.000000,NaN,NaN,...,8.000000,6.000000,16.000000,17.000000,8.000000,6.000000,2.000000,3.000000,0.000000,0.000000
max,NaN,NaN,NaN,6.000000,4.000000,NaN,5.000000,4.000000,NaN,NaN,...,19.000000,14.000000,25.000000,28.000000,17.000000,14.000000,7.000000,7.000000,2.000000,2.000000

In [16]:
# LaLiga ma'lumotlari
df2.describe(include='all')

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
count,380,380,380,380.000000,380.000000,380,380.000000,380.000000,380,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
unique,79,20,20,NaN,NaN,3,NaN,NaN,3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2001-06-10,Barcelona,Malaga,NaN,NaN,H,NaN,NaN,H,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,10,19,19,NaN,NaN,199,NaN,NaN,156,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,1.768421,1.113158,NaN,0.794737,0.450000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,1.321250,1.045324,NaN,0.877736,0.685411,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,0.000000,0.000000,NaN,0.000000,0.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,1.000000,0.000000,NaN,0.000000,0.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,2.000000,1.000000,NaN,1.000000,0.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,3.000000,2.000000,NaN,1.000000,1.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,7.000000,6.000000,NaN,6.000000,6.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
# BundesLiga ma'lumotlari
df3.describe(include='all')

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
count,306,306,306,306.000000,306.000000,306,306.000000,306.000000,306,305,...,306.000000,306.00000,306.000000,306.000000,306.000000,306.000000,306.000000,306.000000,306.000000,306.000000
unique,97,18,18,NaN,NaN,3,NaN,NaN,3,24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2001-05-19,Dortmund,Hansa Rostock,NaN,NaN,H,NaN,NaN,D,Helmut Krug,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,9,17,17,NaN,NaN,160,NaN,NaN,118,21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,1.771242,1.160131,NaN,0.748366,0.522876,NaN,NaN,...,6.196078,4.54902,17.212418,17.362745,6.575163,4.732026,1.921569,2.379085,0.101307,0.186275
std,NaN,NaN,NaN,1.450819,1.123743,NaN,0.926166,0.711360,NaN,NaN,...,2.937734,2.64994,5.065859,5.560026,3.342116,2.533724,1.170845,1.381406,0.302229,0.437513
min,NaN,NaN,NaN,0.000000,0.000000,NaN,0.000000,0.000000,NaN,NaN,...,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,NaN,1.000000,0.000000,NaN,0.000000,0.000000,NaN,NaN,...,4.000000,2.25000,14.000000,13.000000,4.000000,3.000000,1.000000,1.000000,0.000000,0.000000
50%,NaN,NaN,NaN,2.000000,1.000000,NaN,0.000000,0.000000,NaN,NaN,...,6.000000,4.00000,17.000000,17.000000,6.000000,4.000000,2.000000,2.000000,0.000000,0.000000
75%,NaN,NaN,NaN,3.000000,2.000000,NaN,1.000000,1.000000,NaN,NaN,...,8.000000,6.00000,21.000000,21.000000,8.000000,6.000000,3.000000,3.000000,0.000000,0.000000
max,NaN,NaN,NaN,6.000000,5.000000,NaN,5.000000,4.000000,NaN,NaN,...,17.000000,12.00000,30.000000,34.000000,17.000000,16.000000,5.000000,10.000000,1.000000,3.000000

In [18]:
# PremierLiga mezbon kamandalari
df1['HomeTeam'].value_counts()

HomeTeam
Charlton         19
Chelsea          19
Coventry         19
Derby            19
Leeds            19
Leicester        19
Liverpool        19
Sunderland       19
Tottenham        19
Man United       19
Arsenal          19
Bradford         19
Ipswich          19
Middlesbrough    19
Everton          19
Man City         19
Newcastle        19
Southampton      19
West Ham         19
Aston Villa      19
Name: count, dtype: int64

In [19]:
# LaLiga mehmon kamandalari necha marta mehmon bo'lgan ?
df2['AwayTeam'].value_counts()

AwayTeam
Malaga         19
Ath Bilbao     19
Valencia       19
Santander      19
Espanol        19
Alaves         19
Valladolid     19
Oviedo         19
Celta          19
Vallecano      19
Barcelona      19
Real Madrid    19
La Coruna      19
Mallorca       19
Numancia       19
Villarreal     19
Sociedad       19
Osasuna        19
Las Palmas     19
Zaragoza       19
Name: count, dtype: int64

In [20]:
# BundesLiga mehmon jamoalarini nechta gollari qancha takrorlangan ?
df3['FTAG'].value_counts()

FTAG
1    105
0    103
2     58
3     27
4     12
5      1
Name: count, dtype: int64

In [21]:
# PremierLiga datasetida ustunlar bo'yicha takrorlanmedigan qiymatlar qanchadanligini aniqlash
df1.nunique()

Date        97
HomeTeam    20
AwayTeam    20
FTHG         7
FTAG         5
FTR          3
HTHG         5
HTAG         5
HTR          3
Referee     29
HS          30
AS          20
HST         17
AST         13
HF          22
AF          25
HC          18
AC          15
HY           8
AY           7
HR           3
AR           3
dtype: int64

- Date ustuni - bu yerda ma'lumotlar xatosi yoki keraksiz duplikatlar yo'q — shunchaki bitta sanada bir nechta o'yin bo'lib o'tgan

In [22]:
# LaLiga ustunlarida nechta unikal qiymatlar bor
df2.nunique()

Date        79
HomeTeam    20
AwayTeam    20
FTHG         8
FTAG         7
FTR          3
HTHG         6
HTAG         5
HTR          3
Referee      0
HS           0
AS           0
HST          0
AST          0
HF           0
AF           0
HC           0
AC           0
HY           0
AY           0
HR           0
AR           0
dtype: int64

In [23]:
# PremierLiga ustunlaridagi NaN lar sonini aniqlash
df1.isna().sum()

Date        0
HomeTeam    0
AwayTeam    0
FTHG        0
FTAG        0
FTR         0
HTHG        0
HTAG        0
HTR         0
Referee     0
HS          0
AS          0
HST         0
AST         0
HF          0
AF          0
HC          0
AC          0
HY          0
AY          0
HR          0
AR          0
dtype: int64

In [24]:
# LaLiga ustunlaridagi NaN lar sonini aniqlash
df2.isna().sum()

Date          0
HomeTeam      0
AwayTeam      0
FTHG          0
FTAG          0
FTR           0
HTHG          0
HTAG          0
HTR           0
Referee     380
HS          380
AS          380
HST         380
AST         380
HF          380
AF          380
HC          380
AC          380
HY          380
AY          380
HR          380
AR          380
dtype: int64

- Referee ustunidan boshlab ohirgi ustungacha barcha qiymatlar NaN ekan

In [25]:
# BundesLiga ustunlaridagi NaN lar sonini aniqlash
df3.isna().sum()

Date        0
HomeTeam    0
AwayTeam    0
FTHG        0
FTAG        0
FTR         0
HTHG        0
HTAG        0
HTR         0
Referee     1
HS          0
AS          0
HST         0
AST         0
HF          0
AF          0
HC          0
AC          0
HY          0
AY          0
HR          0
AR          0
dtype: int64

- Referee ustunida bir dona NaN bor ekan

In [26]:
# LaLiga ustunlaridagi NaN lar foizlari
(df2.isna().mean()*100).sort_values(ascending=False)

HC          100.0
AST         100.0
HS          100.0
AS          100.0
HST         100.0
Referee     100.0
HY          100.0
AY          100.0
HR          100.0
AC          100.0
AR          100.0
HF          100.0
AF          100.0
Date          0.0
FTR           0.0
FTAG          0.0
FTHG          0.0
AwayTeam      0.0
HomeTeam      0.0
HTAG          0.0
HTR           0.0
HTHG          0.0
dtype: float64

In [27]:
# BundesLiga ustunlaridagi NaN lar foizlarda
(df3.isna().mean()*100).sort_values(ascending=False)

Referee     0.326797
Date        0.000000
AwayTeam    0.000000
FTHG        0.000000
FTAG        0.000000
HomeTeam    0.000000
FTR         0.000000
HTHG        0.000000
HTAG        0.000000
HTR         0.000000
HS          0.000000
AS          0.000000
HST         0.000000
AST         0.000000
HF          0.000000
AF          0.000000
HC          0.000000
AC          0.000000
HY          0.000000
AY          0.000000
HR          0.000000
AR          0.000000
dtype: float64

In [31]:
# LaLiga datasetini Referee ustunidagi NaN lar tashlab yuborish
df2.dropna(subset='Referee')

Empty DataFrame
Columns: [Date, HomeTeam, AwayTeam, FTHG, FTAG, FTR, HTHG, HTAG, HTR, Referee, HS, AS, HST, AST, HF, AF, HC, AC, HY, AY, HR, AR]
Index: []

[0 rows x 22 columns]

In [34]:
# BundesLiga datasini Referee dagi NaN ni tashlab yuborish
df3.dropna(subset='Referee')

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
0,2000-08-11,Dortmund,Hansa Rostock,1,0,H,0,0,D,Jörg Kessler,...,7,2,25,19,7,3,1,5,0,0
1,2000-08-12,Bayern Munich,Hertha,4,1,H,1,0,H,Markus Merk,...,6,5,13,12,4,9,1,0,0,0
2,2000-08-12,Freiburg,Stuttgart,4,0,H,2,0,H,Helmut Krug,...,7,5,22,17,4,7,1,1,0,0
3,2000-08-12,Hamburg,Munich 1860,2,2,D,2,2,D,Herbert Fandel,...,5,7,0,0,5,3,2,2,0,1
4,2000-08-12,Kaiserslautern,Bochum,0,1,A,0,0,D,Helmut Fleischer,...,2,2,9,8,5,5,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300,2001-05-19,Freiburg,Wolfsburg,4,1,H,2,0,H,Alfons Berg,...,8,7,6,9,3,3,2,3,0,0
301,2001-05-19,Hamburg,Bayern Munich,1,1,D,0,0,D,Markus Merk,...,7,5,21,12,5,7,4,2,0,0
302,2001-05-19,Kaiserslautern,Hertha,0,1,A,0,0,D,Bernd Heynemann,...,2,3,9,16,6,3,3,3,0,0
303,2001-05-19,Leverkusen,Bochum,1,0,H,1,0,H,Michael Weiner,...,3,3,10,11,6,4,2,1,0,1
305,2001-05-19,Werder Bremen,Hansa Rostock,3,0,H,2,0,H,Uwe Kemmling,...,9,8,19,9,6,6,1,6,1,1

In [44]:
# BundesLiga Referee ustunidagi NaN ni ko'p takrorlangan qiymat bilan to'ldirish
df3['Referee'].fillna(df3['Referee']).mode()[0]

'Helmut Krug '

**Filtrlash va saralash**

In [163]:
# LaLigada 3 tadan ko'p gol urgan jamoalar
df2[df2['FTHG']>4]['HomeTeam']

37        Valencia
96     Real Madrid
191        Espanol
200      Barcelona
209       Zaragoza
229       Zaragoza
323         Alaves
325         Oviedo
333      Barcelona
351    Real Madrid
Name: HomeTeam, dtype: object

In [166]:
# Real Madridni birinchi bo'limda 2 tadan ko'p gol urgan kamandasi
df2[(df2['HomeTeam'] == 'Real Madrid') & (df2['HTHG'] > 2)]['AwayTeam']

206    Malaga
Name: AwayTeam, dtype: object

In [169]:
# yuqoridagi kodni query bilan yozish
df2.query("HomeTeam == 'Real Madrid' & HTHG > 2")

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
206,2001-02-04,Real Madrid,Malaga,4,3,H,3,2,H,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [172]:
# Real Madridni gollari bo'yicha kamayish tartibidagi 7 ta ma'lumotlar
df2[df2['HomeTeam'] == "Real Madrid"].sort_values(['FTHG'], ascending=False).head(7)

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
96,2000-11-12,Real Madrid,Las Palmas,5,1,H,2,1,H,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
351,2001-05-26,Real Madrid,Alaves,5,0,H,2,0,H,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2000-09-23,Real Madrid,Ath Bilbao,4,1,H,2,0,H,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
257,2001-03-11,Real Madrid,Sociedad,4,0,H,2,0,H,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
292,2001-04-14,Real Madrid,Villarreal,4,0,H,1,0,H,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206,2001-02-04,Real Madrid,Malaga,4,3,H,3,2,H,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
174,2001-01-14,Real Madrid,Oviedo,4,0,H,1,0,H,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [174]:
# LaLigada birinchi bo'limda o'rtacha 1 tadan 3 tagcha gol urgan jamoalar 5 taligi
df2[df2['HTHG'].between(1, 3)]['HomeTeam'].head()

0      Barcelona
6       Mallorca
10    Ath Bilbao
11        Malaga
13      Valencia
Name: HomeTeam, dtype: object

In [177]:
# LaLigada mehmon jamoa yutgani yoki durrang bo'lganligi torisidagi 10 ta ma'lumot
df2[df2['FTR'].isin(['A', 'D'])].head(10)

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
3,2000-09-09,Sociedad,Santander,2,2,D,0,0,D,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2000-09-09,Zaragoza,Espanol,1,2,A,0,0,D,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2000-09-10,Las Palmas,Alaves,0,3,A,0,1,A,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2000-09-10,Mallorca,Valladolid,1,1,D,1,0,H,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2000-09-10,Osasuna,Celta,0,2,A,0,0,D,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2000-09-10,Villarreal,Vallecano,1,5,A,0,3,A,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2000-09-16,Malaga,Real Madrid,3,3,D,1,1,D,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2000-09-16,Santander,La Coruna,0,3,A,0,1,A,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2000-09-17,Alaves,Villarreal,0,1,A,0,0,D,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2000-09-17,Espanol,Osasuna,1,2,A,0,0,D,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**Guruhlash yordamida NaN larni to'ldirish**

- bu amaliyot uchun ai yordamida oddiyroq DF yaratildi va shu DF bilan ishlandi

In [76]:
data = {
    'Category': [
        'Drinks',
        'Drinks',
        'Drinks',
        'Food',
        'Food',
        'Food',
        'Dessert',
        'Dessert',
    ],
    'Item': [
        'Cola',
        'Cola',
        'Fanta',
        'Burger',
        'Burger',
        'Pizza',
        'Cake',
        'Cake',
    ],
    'Price': [10000, np.nan, 10000, 35000, 35000, np.nan, 20000, np.nan],
    'Portion_Weight': [
        np.nan,
        '0.5L',
        '0.5L',
        '250g',
        '250g',
        '400g',
        '150g',
        np.nan,
    ],
    'Payment_Method': [
        'Card',
        'Card',
        np.nan,
        'Cash',
        'Cash',
        'Card',
        np.nan,
        'Cash',
    ],
}

df = pd.DataFrame(data)
df.head()

  Category    Item    Price Portion_Weight Payment_Method
0   Drinks    Cola  10000.0            NaN           Card
1   Drinks    Cola      NaN           0.5L           Card
2   Drinks   Fanta  10000.0           0.5L            NaN
3     Food  Burger  35000.0           250g           Cash
4     Food  Burger  35000.0           250g           Cash

In [98]:
# narx ustunidagi NaN larni mahsulot nomi bo'yicha guruhlab o'rtacha qiymat bilan to'ldirish
df['Price'] = df['Price'].fillna(df.groupby('Item')['Price'].transform('mean'))
df['Price']

0    10000.0
1    10000.0
2    10000.0
3    35000.0
4    35000.0
5    50000.0
6    20000.0
7    20000.0
Name: Price, dtype: float64

In [78]:
df[df.Price.isna()]

  Category   Item  Price Portion_Weight Payment_Method
5     Food  Pizza    NaN           400g           Card

In [79]:
df.Price = df['Price'].fillna(50000)

In [51]:
df['Item'].unique()

array(['Cola', 'Fanta', 'Burger', 'Pizza', 'Cake'], dtype=object)

In [81]:
df.isna().sum()

Category          0
Item              0
Price             0
Portion_Weight    2
Payment_Method    2
dtype: int64

In [83]:
df[df['Portion_Weight'].isna()]

  Category  Item    Price Portion_Weight Payment_Method
0   Drinks  Cola  10000.0            NaN           Card
7  Dessert  Cake  20000.0            NaN           Cash

In [90]:
df['Portion_Weight'] = df.groupby('Item')['Portion_Weight'].transform(lambda x: x.fillna(x.mode()[0] if not x.mode().empty else np.nan))

In [91]:
df

  Category    Item    Price Portion_Weight Payment_Method
0   Drinks    Cola  10000.0           0.5L           Card
1   Drinks    Cola  10000.0           0.5L           Card
2   Drinks   Fanta  10000.0           0.5L            NaN
3     Food  Burger  35000.0           250g           Cash
4     Food  Burger  35000.0           250g           Cash
5     Food   Pizza  50000.0           400g           Card
6  Dessert    Cake  20000.0           150g            NaN
7  Dessert    Cake  20000.0           150g           Cash

In [97]:
df['Payment_Method'] = df.groupby('Category')['Payment_Method'].transform(lambda x: x.fillna(x.mode()[0] if not x.mode().empty else np.nan))
df

  Category    Item    Price Portion_Weight Payment_Method
0   Drinks    Cola  10000.0           0.5L           Card
1   Drinks    Cola  10000.0           0.5L           Card
2   Drinks   Fanta  10000.0           0.5L           Card
3     Food  Burger  35000.0           250g           Cash
4     Food  Burger  35000.0           250g           Cash
5     Food   Pizza  50000.0           400g           Card
6  Dessert    Cake  20000.0           150g           Cash
7  Dessert    Cake  20000.0           150g           Cash

**DataFrame ma'lumotlarini to'g'rilash**

- DF ai yordamida yaratiladi

In [124]:
dirty = pd.DataFrame({
    " Ism ": [" Ali", "vali ", "ALI", "Sardor", None],
    "Yosh": ["21", "25", "21", "abc", "30"],
    "Sana": ["2026-01-05", "2026/02/10", "2026-01-05", "2026-03-01", None],
    "Maosh": [500, 1200, 500, 99999, np.nan],
})
dirty

     Ism  Yosh        Sana    Maosh
0     Ali   21  2026-01-05    500.0
1   vali    25  2026/02/10   1200.0
2     ALI   21  2026-01-05    500.0
3  Sardor  abc  2026-03-01  99999.0
4    None   30        None      NaN

- ustun nomlarini tekshirish va to'g'rilash

In [125]:
dirty.columns

Index([' Ism ', 'Yosh', 'Sana', 'Maosh'], dtype='object')

In [126]:
# ustun nomlaridagi bo'sh joylarni olib tashlash va kichik harflar qilish
dirty.columns = dirty.columns.str.strip().str.lower()
dirty.columns

Index(['ism', 'yosh', 'sana', 'maosh'], dtype='object')

In [127]:
# ism ustunidagi qiymatlarni bir xil korinishga keltirish
dirty['ism'] = dirty['ism'].str.strip().str.title()
dirty['ism']

0       Ali
1      Vali
2       Ali
3    Sardor
4      None
Name: ism, dtype: object

In [128]:
dirty.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ism     4 non-null      object
 1   yosh    5 non-null      object
 2   sana    4 non-null      object
 3   maosh   4 non-null      float64
dtypes: float64(1), object(3)
memory usage: 292.0+ bytes

In [129]:
# yosh ustunini numeric qilish va matnli qiymatni NaN qilish
dirty['yosh'] = pd.to_numeric(dirty['yosh'], errors='coerce')
dirty['yosh']

0    21.0
1    25.0
2    21.0
3     NaN
4    30.0
Name: yosh, dtype: float64

In [130]:
dirty['yosh'].dtype

dtype('float64')

In [135]:
# sana ustunini datetime formatiga o'tkizish
dirty['sana'] = pd.to_datetime(dirty['sana'], errors='coerce')
dirty['sana']

0   2026-01-05
1          NaT
2   2026-01-05
3   2026-03-01
4          NaT
Name: sana, dtype: datetime64[ns]

In [133]:
dirty.isna().sum()

ism      1
yosh     1
sana     2
maosh    1
dtype: int64

In [142]:
# takrorlangan bir xil ma'lumotlarni tekshirish
dirty.duplicated()

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [144]:
# takrorlangan bir xil qatorlarni o'chirish
dirty = dirty.drop_duplicates()
dirty

      ism  yosh       sana    maosh
0     Ali  21.0 2026-01-05    500.0
1    Vali  25.0        NaT   1200.0
3  Sardor   NaN 2026-03-01  99999.0
4    None  30.0        NaT      NaN

In [155]:
# ustun nomlarini o'zgartirish
dirty.rename(columns={'ism':'name', 'yosh':'age', 'sana':'date', 'maosh':'salary'})

     name   age       date   salary
0     Ali  21.0 2026-01-05    500.0
1    Vali  25.0        NaT   1200.0
3  Sardor  23.0 2026-03-01  99999.0
4    None  30.0        NaT      NaN