<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/pandas/MA%CA%BCLUMOTLARNI_TAYYORLASH_11_28_YAKUNIY_AMALIY_VAZIFA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![Imgur](https://i.imgur.com/h4PPC71.png)
#11-modul. Maʼlumotlarga ishlov berish. Maʼlumotlarni tayyorlash
# 11.28. Modul boʻyicha yakuniy amaliy vazifa

**Bu vazifalarni bajargach, maʼlumotlarni yuklash, tozalash, oʻzgartirish, matnlarni normalizatsiya qilish, qiymatlarni tekshirish, guruhlash va tahlil qilish kabi maʼlumotlarga ishlov berish (data processing) koʻnikmalarini egallaysiz.**

#**Umumiy maʼlumotlar bilan ishlash**

#Dataset haqida qisqacha maʼlumot
Restoran savdosi boʻyicha maʼlumotlar toʻplami 17 534 tranzaksiya uchun maʼlumotlarni oʻz ichiga oladi. Maʼlumotlar yetishmayotgan yoki baʼzilari toʻliq kiritilmagan boʻlishi mumkin. Maʼlumotlar toʻplamida asosiy taomlar, shirinliklar, ichimliklar kabi bir nechta toifadagi savdo tafsilotlari mavjud.


 0.   **Unnamed 0** – indekslarni;
 1.   **Order ID** – buyurtma IDʼsini;
 2.   **Customer ID** – mijoz IDʼsini;
 3.   **Category** – mahsulotlar kategoriyasini;
 4.   **Item** – mahsulot nomini;
 5.   **Price** – mahsulotning narxini;
 6.   **Quantity** – qancha mahsulot sotilgani miqdorini;
 7.   **Order Total** – umumiy narx qancha ekanini;
 8.   **Order Date** – buyurtma berilgan sanani (vaqt);
 9.   **Payment Method** – toʻlov usuli turini saqlaydi.

#1) Quyida berilgan datasetni yuklab olib, ustun nomlarini koʻring va ularni maʼno jihatdan tushunarli shaklga keltiring. `Unnamed: 0` ustunini tashlab yuboring!

In [97]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/alishermutalov/praktikum-datasets/refs/heads/praktikum/restaurant_sales.csv"
df = pd.read_csv(url)
df.head()

,Unnamed: 0,Order ID,Customer ID,Category,Item,Price,Quantity,Order Total,Order Date,Payment Method
0,0,ORD_705844,CUST_092,NaN,side salad#?,3.0,1.0,3.0,2023-12-21,Credit Card
1,1,ORD_338528,CUST_021,Side Dishes,Mashed Potatoes,4.0,3.0,12.0,2023-05-19,Digital Wallet
2,2,ORD_443849,CUST_029,Main Dishes,Grilled Chicken,15.0,4.0,60.0,2023-09-27,Credit Card
3,3,ORD_630508,CUST_075,Drinks,NaN,-1.0,2.0,5.0,2022-08-09,Credit Card
4,4,ORD_648269,CUST_031,Main Dishes,Pasta Alfredo,12.0,4.0,48.0,2022-05-15,Cash

In [98]:
#javobni shu yerda yozing
df = df.drop('Unnamed: 0', axis=1)
df.columns

Index(['Order ID', 'Customer ID', 'Category', 'Item', 'Price', 'Quantity',
       'Order Total', 'Order Date', 'Payment Method'],
      dtype='object')

#2) Maʼlumotlarning umumiy holatini (info(), describe()) tekshiring.

In [99]:
#javobni shu yerda yozing
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17534 entries, 0 to 17533
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        17534 non-null  object
 1   Customer ID     17534 non-null  object
 2   Category        17498 non-null  object
 3   Item            15776 non-null  object
 4   Price           17534 non-null  float64
 5   Quantity        17104 non-null  float64
 6   Order Total     17104 non-null  float64
 7   Order Date      17534 non-null  object
 8   Payment Method  16452 non-null  object
dtypes: float64(3), object(6)
memory usage: 1.2+ MB

- ba'zi ustunlarda NaN qiymatlar mavjud

In [100]:
df.describe()

              Price      Quantity   Order Total
count  17534.000000  17104.000000  17104.000000
mean       6.207312      3.014149     19.914494
std        4.993782      1.414598     18.732549
min       -1.000000      1.000000      1.000000
25%        3.000000      2.000000      7.500000
50%        5.000000      3.000000     15.000000
75%        7.000000      4.000000     25.000000
max       20.000000      5.000000    100.000000

- Price ustunida manfiy qiymatlar bor , aslida bo'lmasligi kerak

#3) Har bir ustundagi boʻsh qiymatlarni aniqlang va ularni toʻldirish strategiyasini ishlab chiqing.

In [101]:
#javobni shu yerda yozing
df.isnull().sum()

Order ID             0
Customer ID          0
Category            36
Item              1758
Price                0
Quantity           430
Order Total        430
Order Date           0
Payment Method    1082
dtype: int64

In [102]:
# har bir mahsulotni miqdori bo'yicha medianini hisoblab , NaN larni shu qiymat bilan to'ldirish
df['Quantity'] = df["Quantity"].fillna(df.groupby("Item")["Quantity"].transform("median"))
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].median())
df.isnull().sum()

Order ID             0
Customer ID          0
Category            36
Item              1758
Price                0
Quantity             0
Order Total        430
Order Date           0
Payment Method    1082
dtype: int64

In [103]:
# mahsulot narxini uning miqdoriga ko'paytirish bilan umumiy narxini aniqlemiz
df['Order Total'] = df['Order Total'].fillna(df['Price']*df['Quantity'])
df.isnull().sum()

Order ID             0
Customer ID          0
Category            36
Item              1758
Price                0
Quantity             0
Order Total          0
Order Date           0
Payment Method    1082
dtype: int64

In [104]:
def get_mode(x):
    m = x.dropna().mode()
    return m.iloc[0] if not m.empty else np.nan

# Kategoriya bo'yicha to'ldirish (transform bilan)
df['Category'] = df['Category'].fillna(df.groupby('Item')['Category'].transform(get_mode))

In [105]:
df.isnull().sum()

Order ID             0
Customer ID          0
Category             9
Item              1758
Price                0
Quantity             0
Order Total          0
Order Date           0
Payment Method    1082
dtype: int64

In [106]:
# qolgan NaN larni Price bo'yicha moda topib to'ldirish
price_category_mode = df.groupby('Price')['Category'].transform(get_mode)
df['Category'] = df['Category'].fillna(price_category_mode)

In [107]:
df.isnull().sum()

Order ID             0
Customer ID          0
Category             0
Item              1758
Price                0
Quantity             0
Order Total          0
Order Date           0
Payment Method    1082
dtype: int64

In [108]:
# mahsulot nomidagi nanlarni Category va Price kesimida eng ko'p uchragan Item bilan to'ldirish
cat_price_mode = df.groupby(['Category', 'Price'])['Item'].transform(get_mode)
df['Item'] = df['Item'].fillna(cat_price_mode)

In [109]:
df['Item'].isnull().sum()

np.int64(876)

In [110]:
# Itemdagi qolgan nanlarni Unknown bilan to'ldirish
df['Item'] = df['Item'].fillna('Unknown')
df['Item'].isnull().sum()

np.int64(0)

In [111]:
df.isnull().sum()

Order ID             0
Customer ID          0
Category             0
Item                 0
Price                0
Quantity             0
Order Total          0
Order Date           0
Payment Method    1082
dtype: int64

In [112]:
# payment methoddagi nanlarni mijoz eng ko'p ishlatgan to'lov usuli bilan to'ldirish
cust_payment_mode = df.groupby('Customer ID')['Payment Method'].transform(get_mode)
df['Payment Method'] = df['Payment Method'].fillna(cust_payment_mode)
df.isnull().sum()

Order ID          0
Customer ID       0
Category          0
Item              0
Price             0
Quantity          0
Order Total       0
Order Date        0
Payment Method    0
dtype: int64

#4) Har bir ustundagi takroriy qiymatlarni toping va ularga qanday oʻzgartirish kiritish kerakligini hal qiling.

In [113]:
#javobni shu yerda yozing
df.duplicated().sum()

np.int64(0)

In [114]:
for col in df.columns:
    print("\nEng ko'p takrorlangan 3 ta qiymat:")
    print(df[col].value_counts().head(3))

Eng ko'p takrorlangan 3 ta qiymat:
Order ID
ORD_680707    1
ORD_705844    1
ORD_338528    1
Name: count, dtype: int64

Eng ko'p takrorlangan 3 ta qiymat:
Customer ID
CUST_066    207
CUST_100    200
CUST_055    199
Name: count, dtype: int64

Eng ko'p takrorlangan 3 ta qiymat:
Category
Main Dishes    3550
Starters       3526
Desserts       3496
Name: count, dtype: int64

Eng ko'p takrorlangan 3 ta qiymat:
Item
Side Salad       990
Pasta Alfredo    988
Water (0.5)      968
Name: count, dtype: int64

Eng ko'p takrorlangan 3 ta qiymat:
Price
5.0    3221
4.0    2673
3.0    2180
Name: count, dtype: int64

Eng ko'p takrorlangan 3 ta qiymat:
Quantity
3.0    3883
5.0    3479
4.0    3418
Name: count, dtype: int64

Eng ko'p takrorlangan 3 ta qiymat:
Order Total
12.0    1485
20.0    1402
15.0    1229
Name: count, dtype: int64

Eng ko'p takrorlangan 3 ta qiymat:
Order Date
2023-11-25    42
2022-03-31    41
2022-04-02    40
Name: count, dtype: int64

Eng ko'p takrorlangan 3 ta qiymat:
Payment Method
Credit Card       5872
Cash              5865
Digital Wallet    5797
Name: count, dtype: int64

- `Order ID` va `Customer ID` larga tegilmaydi . Chunki bitta buyurtmada bir nechta mahsulot bo'lishi mumkin. Shuning uchun bitta Order ID bir nechta qatorda takrorlanishi normal holat . Hamda doimiy mijozlar restoranga bir necha bor kelishi yoki bir nechta buyurtma berishi mumkin. Takrorlanish juda yuqori bo'ladi
- Kategoriya va mahsulot nomlariyam takrorlanishi tabiiy
- `Price`, `Quantity`, `Order Total`, bir xil narx va miqdorlar minglab savdolarda takrorlanadi , bu ham tabiiy

#5) Maʼlumotlar toʻplamidagi noto‘g‘ri maʼlumotlar (masalan, son turishi kerak bo‘lgan ustunda matn bo‘lsa) mavjudligini tekshiring va to‘g‘rilang.

In [115]:
#javobni shu yerda yozing
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17534 entries, 0 to 17533
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        17534 non-null  object
 1   Customer ID     17534 non-null  object
 2   Category        17534 non-null  object
 3   Item            17534 non-null  object
 4   Price           17534 non-null  float64
 5   Quantity        17534 non-null  float64
 6   Order Total     17534 non-null  float64
 7   Order Date      17534 non-null  object
 8   Payment Method  17534 non-null  object
dtypes: float64(3), object(6)
memory usage: 1.2+ MB

- `Order Date` ustuni datetime formatida bo'lishi kerak
- `Price` , `Quantity` va `Order Total` ustunlari float64 turida turibdi , bu esa - ushbu ustunlarda hech qanday matnli qiymat yo'qligini bildiradi

In [116]:
df.head(3)

,Order ID,Customer ID,Category,Item,Price,Quantity,Order Total,Order Date,Payment Method
0,ORD_705844,CUST_092,Drinks,side salad#?,3.0,1.0,3.0,2023-12-21,Credit Card
1,ORD_338528,CUST_021,Side Dishes,Mashed Potatoes,4.0,3.0,12.0,2023-05-19,Digital Wallet
2,ORD_443849,CUST_029,Main Dishes,Grilled Chicken,15.0,4.0,60.0,2023-09-27,Credit Card

#6) Maʼlumotlar toʻplamidagi **katta/kichik harf** muammolari boʻlgan joylarni toping va bir xil formatga keltiring.

In [117]:
#javobni shu yerda yozing
df['Category'].value_counts()

Category
Main Dishes    3550
Starters       3526
Desserts       3496
Drinks         3493
Side Dishes    3469
Name: count, dtype: int64

In [118]:
df['Item'].value_counts()

Item
Side Salad             990
Pasta Alfredo          988
Water (0.5)            968
Ice Cream              943
French Fries           890
                      ...
vegetarian platter#      1
mashed potatoes#         1
Onion Rings?             1
ONION RINGS              1
GRILLED VEGETABLES?      1
Name: count, Length: 177, dtype: int64

In [119]:
df['Item'] = df['Item'].astype(str).str.title()
df['Item'].value_counts()

Item
Pasta Alfredo        1038
Side Salad           1025
Ice Cream             981
Water (0.5)           968
French Fries          931
                     ...
Lemonade#?              1
Chocolate Cake#?        1
Pasta Alfredo#?         1
Cheesecake#             1
Mashed Potatoes#?       1
Name: count, Length: 89, dtype: int64

#7) Maʼlumotlar turini oʻzgartirish.
 * Ustunlarning maʼlumot turlarini tekshiring. Notoʻgʻri turlarga ega boʻlgan ustunlarni toʻgʻri formatga oʻtkazing.
 * `order_date` yoki unga oʻxshash ustunni datetime formatiga oʻtkazing.

In [120]:
# Order Date ustunini datetime formatiga o'girish
df['Order Date'] = pd.to_datetime(df['Order Date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17534 entries, 0 to 17533
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        17534 non-null  object
 1   Customer ID     17534 non-null  object
 2   Category        17534 non-null  object
 3   Item            17534 non-null  object
 4   Price           17534 non-null  float64
 5   Quantity        17534 non-null  float64
 6   Order Total     17534 non-null  float64
 7   Order Date      17534 non-null  datetime64[ns]
 8   Payment Method  17534 non-null  object
dtypes: datetime64[ns](1), float64(3), object(5)
memory usage: 1.2+ MB

#8) Mahsulot nomlarida noto‘g‘ri yoki nomaʼlum belgilar (?, NaN, #) mavjudligini tekshiring va ularni tuzating.

In [121]:
# Item ustunidagi qiymatlarni ortiqcha narsalardan tozalash
df['Item'] = df['Item'].astype(str).str.replace(r'[^a-zA-Z0-9\s]', '', regex=True)
df['Item'].value_counts()

Item
Pasta Alfredo         1059
Side Salad            1041
Ice Cream              998
Water 05               968
French Fries           946
Unknown                876
Chocolate Cake         868
Grilled Chicken        866
Mashed Potatoes        849
Coca Cola              816
Cheese Fries           729
Orange Juice           660
Grilled Vegetables     650
Steak                  597
Cheesecake             502
Beef Chili             496
Fruit Salad            479
Lemonade               473
Sweet Potato Fries     471
Brownie                469
Chicken Melt           466
Salmon                 445
Vegetarian Platter     403
Garlic Bread           399
Onion Rings            373
Iced Tea               328
Nachos Grande          247
Water                   54
Lemonade 10              6
Name: count, dtype: int64

#**Maʼlumotlarni filtrlash va qayta ishlash**

#9) Manfiy narx yoki 0 ga teng narx qiymatlarini toping va ularni qanday oʻzgartirish kerakligini hal qiling.

In [122]:
#javobni shu yerda yozing
df[df['Price']<=0]

,Order ID,Customer ID,Category,Item,Price,Quantity,Order Total,Order Date,Payment Method
3,ORD_630508,CUST_075,Drinks,Unknown,-1.0,2.0,5.0,2022-08-09,Credit Card
75,ORD_367023,CUST_055,Side Dishes,Unknown,-1.0,3.0,-3.0,2022-05-29,Digital Wallet
83,ORD_167858,CUST_056,Side Dishes,Unknown,-1.0,5.0,25.0,2022-04-01,Cash
112,ORD_289733,CUST_057,Drinks,Unknown,-1.0,5.0,5.0,2022-01-05,Cash
118,ORD_627458,CUST_058,Side Dishes,Unknown,-1.0,3.0,-3.0,2023-08-24,Digital Wallet
...,...,...,...,...,...,...,...,...,...
17497,ORD_205432,CUST_090,Drinks,Unknown,-1.0,3.0,-3.0,2022-03-03,Cash
17499,ORD_118085,CUST_089,Drinks,Unknown,-1.0,4.0,12.0,2023-04-09,Digital Wallet
17506,ORD_563553,CUST_044,Main Dishes,Unknown,-1.0,3.0,-3.0,2022-07-20,Digital Wallet
17509,ORD_239707,CUST_056,Starters,Unknown,-1.0,1.0,8.0,2023-07-27,Credit Card
17529,ORD_320102,CUST_021,Drinks,Unknown,-1.0,4.0,4.0,2023-12-23,Cash

In [123]:
df.groupby('Item')['Price'].median()

Item
Beef Chili             7.0
Brownie                6.0
Cheese Fries           5.0
Cheesecake             7.0
Chicken Melt           8.0
Chocolate Cake         6.0
Coca Cola              2.5
French Fries           4.0
Fruit Salad            4.0
Garlic Bread           4.0
Grilled Chicken       15.0
Grilled Vegetables     5.0
Ice Cream              5.0
Iced Tea               2.5
Lemonade               3.0
Lemonade 10            3.0
Mashed Potatoes        4.0
Nachos Grande         10.0
Onion Rings            5.0
Orange Juice           3.0
Pasta Alfredo         12.0
Salmon                18.0
Side Salad             3.0
Steak                 20.0
Sweet Potato Fries     5.0
Unknown               -1.0
Vegetarian Platter    14.0
Water                  1.0
Water 05               1.0
Name: Price, dtype: float64

In [124]:
# manfiy va 0 ga teng narxlarni nan qilish
df.loc[df['Price']<=0, 'Price'] = np.nan

# mahsulot nomi bo'yicha guruhlab , median bilan to'ldirish
item_price_mode = df.groupby('Item')['Price'].transform('median')
df['Price'] = df['Price'].fillna(item_price_mode)
df.isnull().sum()

Order ID            0
Customer ID         0
Category            0
Item                0
Price             876
Quantity            0
Order Total         0
Order Date          0
Payment Method      0
dtype: int64

In [125]:
df[df['Price']<=0]

Empty DataFrame
Columns: [Order ID, Customer ID, Category, Item, Price, Quantity, Order Total, Order Date, Payment Method]
Index: []

In [137]:
df['Price'] = df['Price'].fillna(df['Order Total']/df['Quantity'])
df.isnull().sum()

Order ID          0
Customer ID       0
Category          0
Item              0
Price             0
Quantity          0
Order Total       0
Order Date        0
Payment Method    0
dtype: int64

In [138]:
df[df['Price']<=0]

,Order ID,Customer ID,Category,Item,Price,Quantity,Order Total,Order Date,Payment Method
75,ORD_367023,CUST_055,Side Dishes,Unknown,-1.0,3.0,-3.0,2022-05-29,Digital Wallet
118,ORD_627458,CUST_058,Side Dishes,Unknown,-1.0,3.0,-3.0,2023-08-24,Digital Wallet
131,ORD_467157,CUST_099,Drinks,Unknown,-1.0,3.0,-3.0,2023-11-30,Cash
240,ORD_467033,CUST_032,Side Dishes,Unknown,-1.0,3.0,-3.0,2023-03-04,Digital Wallet
253,ORD_722632,CUST_027,Desserts,Unknown,-1.0,3.0,-3.0,2022-12-11,Credit Card
...,...,...,...,...,...,...,...,...,...
17410,ORD_882909,CUST_023,Drinks,Unknown,-1.0,3.0,-3.0,2023-07-11,Credit Card
17451,ORD_529422,CUST_068,Drinks,Unknown,-1.0,3.0,-3.0,2022-07-17,Credit Card
17473,ORD_342327,CUST_096,Desserts,Unknown,-1.0,3.0,-3.0,2022-12-29,Cash
17497,ORD_205432,CUST_090,Drinks,Unknown,-1.0,3.0,-3.0,2022-03-03,Cash
17506,ORD_563553,CUST_044,Main Dishes,Unknown,-1.0,3.0,-3.0,2022-07-20,Digital Wallet

#10) Boʻsh toifalar (kategoriya) mavjudligini tekshiring va toʻgʻri kategoriya berish strategiyasini ishlab chiqing.

In [126]:
#javobni shu yerda yozing

#11) Bir xil, lekin turlicha yozilgan qiymatlar (Coffee, cofee, COFEE) mavjudligini tekshiring va tuzating.

In [127]:
#javobni shu yerda yozing

#12) `Customer ID` yoki boshqa identifikatorlarning takrorlanishini tekshiring.

In [128]:
#javobni shu yerda yozing

#13) Mahsulotning ortiqcha taʼriflarini olib tashlang (Water (0.5), Water (1.0), Water → faqat Water qoldirish).

In [129]:
#javobni shu yerda yozing

#**Qayta ishlangan maʼlumotlar bilan tahlil**

#14) Eng koʻp sotilgan 5 ta mahsulotni aniqlang.

In [130]:
#javobni shu yerda yozing

#15) Har bir mijoz oʻrtacha qancha pul sarflaganini hisoblang.

In [131]:
#javobni shu yerda yozing

#16) Mijozlarning qaysi kunlarda koʻproq xarid qilgani bo‘yicha tahlil qiling.

In [132]:
#javobni shu yerda yozing

#17) Narxi oʻrtacha narxdan ikki barobar yuqori boʻlgan mahsulotlarni toping.

In [133]:
#javobni shu yerda yozing

#18) Mahsulotlar kategoriyalari bo‘yicha tahlil qiling va eng ko‘p sotiladigan kategoriyalarni aniqlang.

In [134]:
#javobni shu yerda yozing

#19) Har bir mijozning oʻrtacha xarid miqdorini (`groupby("customer_id")`) hisoblang.

In [135]:
#javobni shu yerda yozing

#20) Qanday omillar sotuv hajmiga ta’sir qiladi? Bu bo‘yicha umumiy xulosa chiqaring. Javobni quyida kommentariya sifatida yozing!

In [136]:
#javobni shu yerda yozing