<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/pandas/multi_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

1. Dataset sun'iy intellektdan olinadi
2. Dataset : Xususiy klinikaning 3 yillik bemorlar va shifokorlar tahlili bazasi

In [2]:
data = {
    'Filial': ['Toshkent', 'Toshkent', 'Toshkent', 'Toshkent', 'Samarqand', 'Samarqand', 'Samarqand', 'Samarqand'],
    'Yonalish': ['Kardiologiya', 'Kardiologiya', 'Pediatriya', 'Pediatriya', 'Kardiologiya', 'Kardiologiya', 'Pediatriya', 'Pediatriya'],
    'Yil': [2024, 2025, 2024, 2025, 2024, 2025, 2024, 2025],
    'Bemorlar_Soni': [120, 150, 300, 280, 80, 95, 210, 240],
    'Umumiy_Tushum': [45000000, 60000000, 35000000, 42000000, 28000000, 35000000, 22000000, 29000000]
}

df_clinic = pd.DataFrame(data)
df_clinic

      Filial      Yonalish   Yil  Bemorlar_Soni  Umumiy_Tushum
0   Toshkent  Kardiologiya  2024            120       45000000
1   Toshkent  Kardiologiya  2025            150       60000000
2   Toshkent    Pediatriya  2024            300       35000000
3   Toshkent    Pediatriya  2025            280       42000000
4  Samarqand  Kardiologiya  2024             80       28000000
5  Samarqand  Kardiologiya  2025             95       35000000
6  Samarqand    Pediatriya  2024            210       22000000
7  Samarqand    Pediatriya  2025            240       29000000

In [5]:
# Filial va Yonalish ustunlarini irarxik indeks qilish
df_irar = pd.pivot_table(df_clinic,
               index=['Filial', 'Yonalish'])
df_irar

                        Bemorlar_Soni  Umumiy_Tushum     Yil
Filial    Yonalish
Samarqand Kardiologiya           87.5     31500000.0  2024.5
          Pediatriya            225.0     25500000.0  2024.5
Toshkent  Kardiologiya          135.0     52500000.0  2024.5
          Pediatriya            290.0     38500000.0  2024.5

In [7]:
# irarxik jadvalni indekslarini tartiblash
df_irar = df_irar.sort_index()
df_irar

                        Bemorlar_Soni  Umumiy_Tushum     Yil
Filial    Yonalish
Samarqand Kardiologiya           87.5     31500000.0  2024.5
          Pediatriya            225.0     25500000.0  2024.5
Toshkent  Kardiologiya          135.0     52500000.0  2024.5
          Pediatriya            290.0     38500000.0  2024.5

In [9]:
# Toshkentning ma'lumotlarini olish
df_irar.loc['Toshkent']

              Bemorlar_Soni  Umumiy_Tushum     Yil
Yonalish
Kardiologiya          135.0     52500000.0  2024.5
Pediatriya            290.0     38500000.0  2024.5

In [15]:
# barcha filialdagi Pediatriyalar ma'lumotlarini olish
df_irar.xs('Pediatriya', level=1)

           Bemorlar_Soni  Umumiy_Tushum     Yil
Filial
Samarqand          225.0     25500000.0  2024.5
Toshkent           290.0     38500000.0  2024.5

In [24]:
# Yonalish indeksini ustun qilish
df_irar.reset_index(level=1)

               Yonalish  Bemorlar_Soni  Umumiy_Tushum     Yil
Filial
Samarqand  Kardiologiya           87.5     31500000.0  2024.5
Samarqand    Pediatriya          225.0     25500000.0  2024.5
Toshkent   Kardiologiya          135.0     52500000.0  2024.5
Toshkent     Pediatriya          290.0     38500000.0  2024.5

In [23]:
# irarxik indekslarni yo'q qilib , jadvalni eski holatiga qaytarish
df_irar.reset_index()

      Filial      Yonalish  Bemorlar_Soni  Umumiy_Tushum     Yil
0  Samarqand  Kardiologiya           87.5     31500000.0  2024.5
1  Samarqand    Pediatriya          225.0     25500000.0  2024.5
2   Toshkent  Kardiologiya          135.0     52500000.0  2024.5
3   Toshkent    Pediatriya          290.0     38500000.0  2024.5