<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/pandas/multi_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

1. Dataset sun'iy intellektdan olinadi
2. Dataset : Xususiy klinikaning 3 yillik bemorlar va shifokorlar tahlili bazasi

In [2]:
data = {
    'Filial': ['Toshkent', 'Toshkent', 'Toshkent', 'Toshkent', 'Samarqand', 'Samarqand', 'Samarqand', 'Samarqand'],
    'Yonalish': ['Kardiologiya', 'Kardiologiya', 'Pediatriya', 'Pediatriya', 'Kardiologiya', 'Kardiologiya', 'Pediatriya', 'Pediatriya'],
    'Yil': [2024, 2025, 2024, 2025, 2024, 2025, 2024, 2025],
    'Bemorlar_Soni': [120, 150, 300, 280, 80, 95, 210, 240],
    'Umumiy_Tushum': [45000000, 60000000, 35000000, 42000000, 28000000, 35000000, 22000000, 29000000]
}

df_clinic = pd.DataFrame(data)
df_clinic

      Filial      Yonalish   Yil  Bemorlar_Soni  Umumiy_Tushum
0   Toshkent  Kardiologiya  2024            120       45000000
1   Toshkent  Kardiologiya  2025            150       60000000
2   Toshkent    Pediatriya  2024            300       35000000
3   Toshkent    Pediatriya  2025            280       42000000
4  Samarqand  Kardiologiya  2024             80       28000000
5  Samarqand  Kardiologiya  2025             95       35000000
6  Samarqand    Pediatriya  2024            210       22000000
7  Samarqand    Pediatriya  2025            240       29000000

In [5]:
# Filial va Yonalish ustunlarini irarxik indeks qilish
df_irar = pd.pivot_table(df_clinic,
               index=['Filial', 'Yonalish'])
df_irar

                        Bemorlar_Soni  Umumiy_Tushum     Yil
Filial    Yonalish
Samarqand Kardiologiya           87.5     31500000.0  2024.5
          Pediatriya            225.0     25500000.0  2024.5
Toshkent  Kardiologiya          135.0     52500000.0  2024.5
          Pediatriya            290.0     38500000.0  2024.5

In [7]:
# irarxik jadvalni indekslarini tartiblash
df_irar = df_irar.sort_index()
df_irar

                        Bemorlar_Soni  Umumiy_Tushum     Yil
Filial    Yonalish
Samarqand Kardiologiya           87.5     31500000.0  2024.5
          Pediatriya            225.0     25500000.0  2024.5
Toshkent  Kardiologiya          135.0     52500000.0  2024.5
          Pediatriya            290.0     38500000.0  2024.5

In [9]:
# Toshkentning ma'lumotlarini olish
df_irar.loc['Toshkent']

              Bemorlar_Soni  Umumiy_Tushum     Yil
Yonalish
Kardiologiya          135.0     52500000.0  2024.5
Pediatriya            290.0     38500000.0  2024.5

In [15]:
# barcha filialdagi Pediatriyalar ma'lumotlarini olish
df_irar.xs('Pediatriya', level=1)

           Bemorlar_Soni  Umumiy_Tushum     Yil
Filial
Samarqand          225.0     25500000.0  2024.5
Toshkent           290.0     38500000.0  2024.5

In [24]:
# Yonalish indeksini ustun qilish
df_irar.reset_index(level=1)

               Yonalish  Bemorlar_Soni  Umumiy_Tushum     Yil
Filial
Samarqand  Kardiologiya           87.5     31500000.0  2024.5
Samarqand    Pediatriya          225.0     25500000.0  2024.5
Toshkent   Kardiologiya          135.0     52500000.0  2024.5
Toshkent     Pediatriya          290.0     38500000.0  2024.5

In [23]:
# irarxik indekslarni yo'q qilib , jadvalni eski holatiga qaytarish
df_irar.reset_index()

      Filial      Yonalish  Bemorlar_Soni  Umumiy_Tushum     Yil
0  Samarqand  Kardiologiya           87.5     31500000.0  2024.5
1  Samarqand    Pediatriya          225.0     25500000.0  2024.5
2   Toshkent  Kardiologiya          135.0     52500000.0  2024.5
3   Toshkent    Pediatriya          290.0     38500000.0  2024.5

#####**Yangi dataset bilan ishlash**

In [25]:
data2 = {
    'Shifokor': ['Anvarov', 'Anvarov', 'Karimova', 'Karimova', 'Anvarov', 'Anvarov', 'Karimova', 'Karimova'],
    'Yonalish': ['Kardiologiya', 'Kardiologiya', 'Pediatriya', 'Pediatriya', 'Kardiologiya', 'Kardiologiya', 'Pediatriya', 'Pediatriya'],
    'Filial': ['Toshkent', 'Samarqand', 'Toshkent', 'Samarqand', 'Toshkent', 'Samarqand', 'Toshkent', 'Samarqand'],
    'Yil': [2024, 2024, 2024, 2024, 2025, 2025, 2025, 2025],
    'Xizmatlar_Soni': [150, 90, 310, 220, 180, 110, 290, 260],
    'Reyting': [4.8, 4.2, 4.9, 4.5, 4.9, 4.4, 5.0, 4.7]
}

df_raw = pd.DataFrame(data2)
df_raw

   Shifokor      Yonalish     Filial   Yil  Xizmatlar_Soni  Reyting
0   Anvarov  Kardiologiya   Toshkent  2024             150      4.8
1   Anvarov  Kardiologiya  Samarqand  2024              90      4.2
2  Karimova    Pediatriya   Toshkent  2024             310      4.9
3  Karimova    Pediatriya  Samarqand  2024             220      4.5
4   Anvarov  Kardiologiya   Toshkent  2025             180      4.9
5   Anvarov  Kardiologiya  Samarqand  2025             110      4.4
6  Karimova    Pediatriya   Toshkent  2025             290      5.0
7  Karimova    Pediatriya  Samarqand  2025             260      4.7

In [29]:
# shifokor, yonalishi va filialini irarxik indeks qilib ma'lumotlarni ko'rish
df_3idx = df_raw.set_index(['Shifokor', 'Yonalish', 'Filial'])
df_3idx

                                  Yil  Xizmatlar_Soni  Reyting
Shifokor Yonalish     Filial
Anvarov  Kardiologiya Toshkent   2024             150      4.8
                      Samarqand  2024              90      4.2
Karimova Pediatriya   Toshkent   2024             310      4.9
                      Samarqand  2024             220      4.5
Anvarov  Kardiologiya Toshkent   2025             180      4.9
                      Samarqand  2025             110      4.4
Karimova Pediatriya   Toshkent   2025             290      5.0
                      Samarqand  2025             260      4.7

In [30]:
# faqat indekslarni ko'rish
df_3idx.index

MultiIndex([( 'Anvarov', 'Kardiologiya',  'Toshkent'),
            ( 'Anvarov', 'Kardiologiya', 'Samarqand'),
            ('Karimova',   'Pediatriya',  'Toshkent'),
            ('Karimova',   'Pediatriya', 'Samarqand'),
            ( 'Anvarov', 'Kardiologiya',  'Toshkent'),
            ( 'Anvarov', 'Kardiologiya', 'Samarqand'),
            ('Karimova',   'Pediatriya',  'Toshkent'),
            ('Karimova',   'Pediatriya', 'Samarqand')],
           names=['Shifokor', 'Yonalish', 'Filial'])

In [33]:
# shifokor va yonalish indekslar o'rnini almashtirish
df_3idx = df_3idx.swaplevel('Shifokor', 'Yonalish').sort_index()
df_3idx

                                  Yil  Xizmatlar_Soni  Reyting
Yonalish     Shifokor Filial
Kardiologiya Anvarov  Samarqand  2024              90      4.2
                      Samarqand  2025             110      4.4
                      Toshkent   2024             150      4.8
                      Toshkent   2025             180      4.9
Pediatriya   Karimova Samarqand  2024             220      4.5
                      Samarqand  2025             260      4.7
                      Toshkent   2024             310      4.9
                      Toshkent   2025             290      5.0

In [37]:
# faqatgina Samarqand filiali ma'lumotlarini olish
df_samarqand = df_3idx.xs('Samarqand', level=2)
df_samarqand

                        Yil  Xizmatlar_Soni  Reyting
Yonalish     Shifokor
Kardiologiya Anvarov   2024              90      4.2
             Anvarov   2025             110      4.4
Pediatriya   Karimova  2024             220      4.5
             Karimova  2025             260      4.7

In [36]:
# barcha irarxik indekslarni eski holga keltirish
df_3idx.reset_index()

       Yonalish  Shifokor     Filial   Yil  Xizmatlar_Soni  Reyting
0  Kardiologiya   Anvarov  Samarqand  2024              90      4.2
1  Kardiologiya   Anvarov  Samarqand  2025             110      4.4
2  Kardiologiya   Anvarov   Toshkent  2024             150      4.8
3  Kardiologiya   Anvarov   Toshkent  2025             180      4.9
4    Pediatriya  Karimova  Samarqand  2024             220      4.5
5    Pediatriya  Karimova  Samarqand  2025             260      4.7
6    Pediatriya  Karimova   Toshkent  2024             310      4.9
7    Pediatriya  Karimova   Toshkent  2025             290      5.0